### ISSUE TITLE
Exception during linting: "Applying rule L016 threw an Exception: Fixes must provide an anchor."

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#1047]
-- If this is a parsing or linting issue, please include a minimal SQL example which reproduces the issue, along with the `sqlfluff parse` output, `sqlfluff lint` output and `sqlfluff fix` output when relevant. Finally, please add any labels that are related to the issue before submitting so that it can be addressed easily! --

## Expected Behaviour

`sqlfluff lint` should run without reporting exceptions.

## Observed Behaviour

Saw this output:
```
CRITICAL   [L016] Applying rule L016 threw an Exception: Fixes must provide an anchor.
Traceback (most recent call last):
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/core/rules/base.py", line 310, in crawl
    templated_file=templated_file,
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/rules/L016.py", line 450, in _eval
    fixes = self._eval_line_for_breaks(this_line)
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/rules/L016.py", line 351, in _eval_line_for_breaks
    segments, indent_section, self, indent
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/rules/L016.py", line 165, in generate_fixes_to_coerce
    WhitespaceSegment(new_indent),
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/core/rules/base.py", line 117, in __init__
    raise ValueError("Fixes must provide an anchor.")
ValueError: Fixes must provide an anchor.
```
## Steps to Reproduce

Run `sqlfluff lint` on this  SQL file:
```
CREATE OR REPLACE MODEL
  `{{project}}.{{dataset}}.paid_propensity_gbm` OPTIONS(model_type='BOOSTED_TREE_REGRESSOR',
    input_label_cols= ['convert']) AS

   select    convert, days_since_activity, index_age , list_size_modified, country_modified, ecomm_level, pro, mandrill,sent_email from
`{{project}}.{{dataset}}.user_starts_and_paid_with_active`
 where rn < 0.8
```

## Version
Include the output of `sqlfluff --version` along with your Python version
SQLFluff: 0.5.4
Python: 3.7.3

## Configuration
```
[sqlfluff]
verbose = 0
nocolor = False
dialect = bigquery
templater = jinja
rules = None
exclude_rules = L029,L031,L032,L034
recurse = 0

[sqlfluff:templater:jinja:macros]

# Some rules can be configured directly from the config common to other rules.
[sqlfluff:rules]
tab_space_size = 4
max_line_length = 120

# Some rules have their own specific config.
[sqlfluff:rules:L010]
capitalisation_policy = consistent

[sqlfluff:rules:L014]
capitalisation_policy = consistent

[sqlfluff:rules:L030]
capitalisation_policy = consistent

# Settings in this section will be provided to SQL templates during the SQL
# formatting/linting process. Generally, the exact values don't matter as long
# as they result in valid SQL syntax when substituted in the file.
[sqlfluff:templater:jinja:context]
gcp_project=gcp_project
project=gcp_project
dataset=dataset
user_filter=
date_filter=
```

**Comment by barrywhart** [comment]
I did some preliminary investigation of this issue. It did not occur in SQLFluff 0.5.3.  I suspect this new issue is related to the big segment refactoring.

Here's what I looked at and my findings:

The `find_segment_at()` function is returning `None`, which in turn causes the rule to try and create a `LintFix` with a `None` anchor, which is illegal.

`find_segment_at()` wants to find a segment whose end location **exactly matches** that of the given segment. I added some print statements and determined that in this case, there is no such segment, but there **is** a segment whose position is off by one from the desired location.

```
                create_anchor = self.find_segment_at(
                    segments, self.segments[-1].get_end_loc()
                )
                if create_anchor is None:  # Added debugging code
                    print(self.segments[-1].get_end_loc())
                    print([seg.pos_marker.working_loc for seg in segments if not seg.is_meta])
                    import pdb; pdb.set_trace()
```

Output:
```
(5, 13)
[(5, 0), (5, 3), (5, 9), (5, 14), (5, 20), (5, 21), (5, 23), (5, 41), (5, 42), (5, 44), (5, 52), (5, 53), (5, 54), (5, 56), (5, 73), (5, 74), (5, 76), (5, 91), (5, 92), (5, 94), (5, 104), (5, 105), (5, 107), (5, 109), (5, 110), (5, 112), (5, 119), (5, 121), (5, 130), (5, 131)]
``` 

I created an alternate implementation of `find_segment_at()` which looks for the **closest** match rather than an exact match. This avoids the exception, but the nature of this bug makes me think the real issue may be deeper, somewhere in the code that computes segment positions.

```
            @staticmethod
            def find_segment_at(segments, loc: Tuple[int, int]):
                distance = None
                result = None
                for seg in segments:
                    if not seg.is_meta:
                        working_loc = seg.pos_marker.working_loc
                        if working_loc[0] == loc[0]:  # Same line
                            this_distance = abs(working_loc[0] - loc[0])
                            if distance is None or this_distance < distance:
                                distance = this_distance
                                result = seg
                return result
```

**Comment by barrywhart** [comment]
@alanmcruickshank

**Comment by alanmcruickshank** [comment]
Thanks for the great bug report - I'll see if I can recreate it.

**Comment by alanmcruickshank** [comment]
I know what the *problem* is. Not yet the fix....

When the first round of fixes are applied, they're not repositioning properly....

**Comment by alanmcruickshank** [comment]
ok - found the issue. Off by one error. It's a 2 character fix.

Mind if I use a simplified version of your query in a test case?
