### ISSUE TITLE
Fatal. Unable to lex characters: 0

### ISSUE THREAD

**Issue by SpokeyWheeler** [sqlfluff/sqlfluff#1129]
I've done a `git pull` of the latest version of the code and a `pip3 install sqlfluff`. I've created a `test/fixtures/parser/cockroach` subdirectory as per https://github.com/sqlfluff/sqlfluff/issues/1121 and copied my files into that. My `PYTHONPATH` is set to `~/Library/Python/3.7/lib/python/site-packages/`

```
$ sqlfluff --version
sqlfluff, version 0.5.6
```
```
$ cd ~/workspace/sqlfluff
$ python3 test/generate_parse_fixture_yml.py
Zero length Lex item returned from '<unlexable>'. Report this as a bug.
Traceback (most recent call last):
  File "/Users/William.Wheeler/workspace/sqlfluff/test/generate_parse_fixture_yml.py", line 22, in <module>
    tokens, _ = Lexer(config=config).lex(raw)
  File "/Users/William.Wheeler/Library/Python/3.7/lib/python/site-packages/sqlfluff/core/parser/lexer.py", line 302, in lex
    raise SQLLexError(
sqlfluff.core.errors.SQLLexError: Fatal. Unable to lex characters: 0
```

The following files have been "changed" as far as I can tell:
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   test/fixtures/parser/ansi/arithmetic_a.yml
	modified:   test/fixtures/parser/ansi/create_index_if_not_exists.yml
	modified:   test/fixtures/parser/ansi/create_model_options.yml
	modified:   test/fixtures/parser/ansi/create_table_a_c1_c2.yml
	modified:   test/fixtures/parser/ansi/create_table_a_column_constraints.yml
	modified:   test/fixtures/parser/ansi/create_table_as_select_cte_parentheses.yml
	modified:   test/fixtures/parser/ansi/create_table_auto_increment.yml
	modified:   test/fixtures/parser/ansi/create_table_column_comment.yml
	modified:   test/fixtures/parser/ansi/create_table_table_comment.yml
	modified:   test/fixtures/parser/ansi/create_table_varchar.yml
	modified:   test/fixtures/parser/ansi/create_view_a.yml
	modified:   test/fixtures/parser/ansi/create_zero_argument_function.yml
	modified:   test/fixtures/parser/ansi/functions_a.yml
	modified:   test/fixtures/parser/ansi/functions_b.yml
	modified:   test/fixtures/parser/ansi/grant_select_col1_col2_update_col1_on_mytable_to_public.yml
	modified:   test/fixtures/parser/ansi/insert_a.yml
	modified:   test/fixtures/parser/ansi/multi_statement_b.yml
	modified:   test/fixtures/parser/ansi/multi_statement_c.yml
	modified:   test/fixtures/parser/ansi/select_fn_square_bracket_array_parameter.yml
	modified:   test/fixtures/parser/ansi/select_function_in_group_by.yml
	modified:   test/fixtures/parser/ansi/select_h.yml
	modified:   test/fixtures/parser/ansi/select_in_multiline_comment.yml
	modified:   test/fixtures/parser/ansi/select_j.yml
	modified:   test/fixtures/parser/ansi/select_l.yml
	modified:   test/fixtures/parser/ansi/select_m.yml
	modified:   test/fixtures/parser/ansi/select_many_join.yml
	modified:   test/fixtures/parser/ansi/select_named_windows_each_window_specification.yml
	modified:   test/fixtures/parser/ansi/select_simple_h.yml
	modified:   test/fixtures/parser/ansi/select_simple_i.yml
	modified:   test/fixtures/parser/ansi/select_where_in_unnest.yml
	modified:   test/fixtures/parser/ansi/select_with_b.yml
	modified:   test/fixtures/parser/ansi/select_with_recursive.yml
	modified:   test/fixtures/parser/ansi/set_order_by_complex.yml
	modified:   test/fixtures/parser/ansi/table_expression.yml
	modified:   test/fixtures/parser/teradata/collect_stats.yml
	modified:   test/fixtures/parser/teradata/create_table_stmt.yml
	modified:   test/fixtures/parser/teradata/create_table_stmt_2.yml
	modified:   test/fixtures/parser/teradata/create_table_stmt_3.yml
	modified:   test/fixtures/parser/teradata/select_stmt.yml
	modified:   test/fixtures/parser/teradata/select_stmt_cast.yml
	modified:   test/fixtures/parser/teradata/update_from.yml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	test/fixtures/parser/cockroach/
```
Let me know if you need any further information.

**Comment by SpokeyWheeler** [comment]
After some help from my tame Python guru, I made this change to the script:

```
    # tokens, _ = Lexer(config=config).lex(raw)
    try:
        tokens, _ = Lexer(config=config).lex(raw)
    except:
        print(raw)
        raise
```
This revealed:
```
$ python3 test/generate_parse_fixture_yml.py
Zero length Lex item returned from '<unlexable>'. Report this as a bug.
select
    c1 & c2,
    c3 | c4,
    c5 ^ c6,
    c7 << c8,
    c9 >> c10

Traceback (most recent call last):
  File "/Users/William.Wheeler/workspace/sqlfluff/test/generate_parse_fixture_yml.py", line 24, in <module>
    tokens, _ = Lexer(config=config).lex(raw)
  File "/Users/William.Wheeler/Library/Python/3.7/lib/python/site-packages/sqlfluff/core/parser/lexer.py", line 302, in lex
    raise SQLLexError(
sqlfluff.core.errors.SQLLexError: Fatal. Unable to lex characters: 0
```

**Comment by barrywhart** [comment]
When you saw this, had you already added your test cases, or were you running with a "clean" clone of the SQLFluff repo?

Can you try and determine which file it's failing on? To determine this, you can probably just add a line `print(sqlfile)` [here](https://github.com/sqlfluff/sqlfluff/blob/master/test/generate_parse_fixture_yml.py#L18).

**Comment by SpokeyWheeler** [comment]
select_bitwise_operators.sql

**Comment by barrywhart** [comment]
You mention that you did a `git pull` to get the latest code and also run `pip3 install sqlfluff`. If you run that `pip install` command, it's going to install a release, rather than using the local clone of the code. I think what's happening is that you're running the **latest** SQLFluff test case `.sql` files using the **most recent release** (which is several weeks old). Thus, some of the newer test cases are not working in the older 0.5.6 code.

Have you read the [documentation](https://github.com/sqlfluff/sqlfluff/blob/master/CONTRIBUTING.md) for new contributors? That will help you get your local copy of the code set up correctly.

**Comment by SpokeyWheeler** [comment]
My bad. Sorry.

**Comment by SpokeyWheeler** [comment]
OK, I've now moved on to 
```
python3 test/generate_parse_fixture_yml.py
Traceback (most recent call last):
  File "/Users/William.Wheeler/workspace/sqlfluff/test/generate_parse_fixture_yml.py", line 18, in <module>
    config = FluffConfig(overrides=dict(dialect=dialect))
  File "/Users/William.Wheeler/workspace/sqlfluff/src/sqlfluff/core/config.py", line 435, in __init__
    self._configs["core"]["dialect_obj"] = dialect_selector(
  File "/Users/William.Wheeler/workspace/sqlfluff/src/sqlfluff/core/dialects/__init__.py", line 59, in dialect_selector
    dialect = load_raw_dialect(s or "ansi")
  File "/Users/William.Wheeler/workspace/sqlfluff/src/sqlfluff/core/dialects/__init__.py", line 34, in load_raw_dialect
    module, name = _dialect_lookup[label]
KeyError: 'cockroach'
```
which I can understand and work with. Sorry for wasting your time!

**Comment by barrywhart** [comment]
@SpokeyWheeler: No problem at all! We're happy to help people, especially potential contributors. 😉 

Have you joined the SQLFluff [Slack community](https://docs.sqlfluff.com/en/stable/jointhecommunity.html)? That can be a good place to ask general questions around project process, how to contribute, etc. In particular, see the "help" and "contributing" channels.

You may encounter a few challenges getting started with a new dialect, but we're happy to help. It tends become a lot easier after the beginning.

Another user began work on a TSQL dialect not long ago, and you may find it helpful to look at their in-progress [PR](https://github.com/sqlfluff/sqlfluff/pull/960).

**Comment by swanderz** [comment]
@barrywhart @SpokeyWheeler @tunetheweb
I started #960 a long time ago, and I believe the dialect/plug-in model has changed significantly since then. It's been at the top of my "to-do when I next have free time" list for quite a while! My team and I would love to collaborate on getting TSQL support. Let us know how we might help. I'm on PTO for ~2 more weeks, but am happy to prioritize it when I get back.
cc: @alieus @timdenouden
