### ISSUE TITLE
[L001] Applying rule L001 threw an Exception: tuple index out of range

### ISSUE THREAD

**Issue by CyberShadow** [sqlfluff/sqlfluff#1371]
Testing SQLFluff again after https://github.com/sqlfluff/sqlfluff/pull/1364.

## Expected Behaviour

Not crash, and maybe delete the space character on the first line.

## Observed Behaviour

Prints the following error message:
```
==== finding fixable violations ====
CRITICAL   [L001] Applying rule L001 threw an Exception: tuple index out of range 
Traceback (most recent call last):
  File "/home/vladimir/work/extern/sqlfluff/venv/lib/python3.9/site-packages/sqlfluff/core/rules/base.py", line 301, in crawl
    res = self._eval(
  File "/home/vladimir/work/extern/sqlfluff/venv/lib/python3.9/site-packages/sqlfluff/rules/L001.py", line 44, in _eval
    while raw_stack[idx].is_type("whitespace"):
IndexError: tuple index out of range
==== no fixable linting violations found ====
  [1 unfixable linting violations found]
All Finished 📜 🎉!
```

sqlfluff parse output:
```
$ sqlfluff parse test.sql
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    whitespace:                                               ' '
[L:  1, P:  2]      |    newline:                                                  '\n'
[L:  2, P:  1]      |    statement:
[L:  2, P:  1]      |        select_statement:
[L:  2, P:  1]      |            select_clause:
[L:  2, P:  1]      |                keyword:                                      'SELECT'
[L:  2, P:  7]      |                [META] indent:
[L:  2, P:  7]      |                whitespace:                                   ' '
[L:  2, P:  8]      |                select_clause_element:
[L:  2, P:  8]      |                    literal:                                  '1'
[L:  2, P:  9]      |            [META] dedent:
[L:  2, P:  9]      |    newline:                                                  '\n'
```

## Steps to Reproduce

```console
$ printf ' \nSELECT 1\n' > test.sql
$ sqlfluff fix test.sql
```

## Dialect

None

## Version

SQLFluff 17e15d1dc09442596c83c7f56826f24659c877a0, Python 3.9.6

## Configuration

None

**Comment by tunetheweb** [comment]
See the issue and have a fix. PR incoming...
