### ISSUE TITLE
dbt.exceptions.InternalException: Asked to compile <class 'dbt.contracts.graph.compiled.CompiledModelNode'> node, but it has no compiled form

### ISSUE THREAD

**Issue by pecigonzalo** [sqlfluff/sqlfluff#1518]
When running `sqlfluff` with DBT, we see some internal DBT error

I tried doing to find files to share here, but it works when ran against individual files
```
find models/* -type d | xargs -I {} sh -c 'echo Running {} && sqlfluff lint -v {}'
```

I trimmed it down to a folder I can reproduce on, but I cant share the exact files as you might expect.

## Expected Behaviour
No exception.

## Observed Behaviour

```
sqlfluff fix -v --force \
  dbt/projectFoo/models/source/bar/src__bar.sql \
  dbt/projectFoo/models/source/bar/src__bar_callback.sql \
  dbt/projectFoo/models/source/bar/src__bar_csv.sql

==== sqlfluff ====
sqlfluff:                0.6.8 python:                  3.9.6
implementation:        cpython dialect:             snowflake
verbosity:                   1 templater:                 dbt
dbt:                   =0.21.0

==== finding fixable violations ====
=== [ path: dbt/projectFoo/models/source/bar/src__bar.sql ] ===

=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
== [dbt/projectFoo/models/source/bar/src__bar_csv.sql] PASS
== [dbt/projectFoo/models/source/bar/src__bar_callback.sql] PASS
== [dbt/projectFoo/models/source/bar/src__bar.sql] PASS
=== [ path: dbt/projectFoo/models/source/bar/src__bar_csv.sql ] ===
[...]
Traceback (most recent call last):
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 507, in fix
    result = lnt.lint_paths(
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 845, in lint_paths
    self.lint_path(
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 819, in lint_path
    for linted_file in runner.run(fnames, fix):
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 96, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 49, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 42, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 578, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 555, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/core/templaters/dbt.py", line 353, in process
    processed_result = self._unsafe_process(fname_absolute_path, in_str, config)
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/core/templaters/dbt.py", line 422, in _unsafe_process
    node = self.dbt_compiler.compile_node(
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/dbt/compilation.py", line 543, in compile_node
    node = self._compile_node(node, manifest, extra_context)
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/dbt/compilation.py", line 377, in _compile_node
    compiled_node = _compiled_type_for(node).from_dict(data)
  File "/Users/gonzalopeci/.cache/pre-commit/repo2fi0qiio/py_env-python3.9/lib/python3.9/site-packages/dbt/compilation.py", line 39, in _compiled_type_for
    raise InternalException(
dbt.exceptions.InternalException: Asked to compile <class 'dbt.contracts.graph.compiled.CompiledModelNode'> node, but it has no compiled form
```

### Example redacted files

**src__bar**
```
{{
    config(
        materialized='incremental',
        cluster_by=['created_at']
    )
}}


SELECT
    *
FROM
    {{ ref('src__bar_csv') }}
WHERE
    created_at <= current_date + 1
    AND created_at >= '2021-03-26'

    {% if is_incremental() %}
        AND _metadata__load_timestamp >= (
            SELECT max(_metadata__load_timestamp) FROM {{ this }}
        )
{% endif %}

UNION ALL

SELECT
    *
FROM
    {{ ref('src__bar_callback') }}
-- The date format in the where condition is different because of different source table
WHERE
    created_at::DATE <= '2021-03-25'
    {% if is_incremental() %}
        AND _metadata__load_timestamp >= (
            SELECT max(_metadata__load_timestamp) FROM {{ this }}
        )
{% endif %}

```

**src__bar_callback**
```
SELECT
    app_id::TEXT AS app_id,
    app_name::TEXT AS app_name,
    app_version::TEXT AS app_version,
    [...]
FROM
    {{ source('fizz', 'buzz') }}
WHERE date_trunc('day', created_at::TIMESTAMPLTZ) <= '2021-03-25'

UNION ALL

SELECT
    app_id::TEXT AS app_id,
    app_name::TEXT AS app_name,
    app_version::TEXT AS app_version,
    app_version_short::TEXT AS app_version_short,
  [...]
FROM
    {{ source('this', 'that') }}
WHERE date_trunc('day', created_at::TIMESTAMPLTZ) <= '2021-03-25'
```

**src__bar_csv**

```
{{
    config(
        materialized='incremental',
        cluster_by=['created_at']
    )
}}

SELECT
    "app_id"::TEXT AS app_id,
    "app_name"::TEXT AS app_name,
    "app_version"::TEXT AS app_version,
    [...]
FROM
    {{ source('bar', 'bar_csv_data') }}
WHERE "created_at" <= current_date + 1
{% if is_incremental() %}
  AND "_metadata__load_timestamp" >= (select max(_metadata__load_timestamp) from {{ this }} )
{% endif %}

```

## Dialect

`snowflake`

## Version
Python: `3.9`
SQLFluff: `sqlfluff, version 0.6.8`

## Configuration
```
[sqlfluff]
templater = dbt
dialect = snowflake

[sqlfluff:indentation]
indented_joins = False
template_blocks_indent = True

[sqlfluff:templater]
unwrap_wrapped_queries = True

[sqlfluff:templater:dbt]
project_dir = dbt/projectFoo
profiles_dir = dbt/projectFoo
profile = projectFoo

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 80
indent_unit = space
comma_style = trailing
allow_scalar = True
single_table_references = consistent
unquoted_identifiers_policy = all

[sqlfluff:rules:L003]
lint_templated_tokens = True

[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = upper

[sqlfluff:rules:L014]  # Unquoted identifiers
extended_capitalisation_policy = lower
unquoted_identifiers_policy = column_aliases

[sqlfluff:rules:L016]
ignore_comment_lines = True

[sqlfluff:rules:L029]  # Keyword identifiers
unquoted_identifiers_policy = aliases

[sqlfluff:rules:L030]  # Function names
capitalisation_policy = lower

[sqlfluff:rules:L038]
select_clause_trailing_comma = forbid

[sqlfluff:rules:L040]  # Null & Boolean Literals
capitalisation_policy = consistent

[sqlfluff:rules:L042]
# By default, allow subqueries in from clauses, but not join clauses.
forbid_subquery_in = join```

**Comment by pecigonzalo** [comment]
I found it odd that it tries to do the same file twice in:
```
==== finding fixable violations ====
=== [ path: dbt/projectFoo/models/source/bar/src__bar.sql ] ===

=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
== [dbt/projectFoo/models/source/bar/src__bar_csv.sql] PASS
== [dbt/projectFoo/models/source/bar/src__bar_callback.sql] PASS
== [dbt/projectFoo/models/source/bar/src__bar.sql] PASS
=== [ path: dbt/projectFoo/models/source/bar/src__bar_csv.sql ] ===
```

Maybe its not parsing the depenendency graph properly.

**Comment by pecigonzalo** [comment]
Some additional context, I have replicated the commands to open this issue and I have been testing this with direct `sqlfluff` but the original situation was when using this with `pre-commit`, which might be why its passing each file and not a folder, and potentially whats causing the overall issue (passing multiple cross-referenced files).

**Comment by pecigonzalo** [comment]
I have verified this works when ran directly against the folder
```
sqlfluff fix -v --force dbt/projectFoo/models/source/bar     ==== sqlfluff ====
sqlfluff:                0.6.8 python:                  3.9.6
implementation:        cpython dialect:             snowflake
verbosity:                   1 templater:                 dbt
dbt:                   =0.21.0

==== finding fixable violations ====
=== [ path: dbt/projectFoo/models/source/bar ] ===

=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
== [dbt/projectFoo/models/source/bar/src__bar_csv.sql] PASS
== [dbt/projectFoo/models/source/bar/src__bar_callback.sql] PASS
== [dbt/projectFoo/models/source/bar/src__bar.sql] PASS
==== no fixable linting violations found ====
All Finished 📜 🎉!
  [5 unfixable linting violations found]
```

Im quite sure this is related to processing multiple related files as individual units instead of processing the folder.

**Comment by pecigonzalo** [comment]
@alanmcruickshank I did a quick test and over known failing folder selecting all files (like pre-commit does) and it worked 🎉 

```
==== sqlfluff ====
sqlfluff:                0.6.8 python:                  3.9.6
implementation:        cpython dialect:             snowflake
verbosity:                   1 templater:                 dbt
dbt:                   =0.21.0

==== finding fixable violations ====
=== [ path: models/source/bar/schema__src__bar.yml ] ===

=== [dbt templater] Sorting Nodes...
=== [ path: models/source/bar/src__bar.sql ] ===

=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
== [models/source/bar/src__bar.sql] PASS
=== [ path: models/source/bar/src__bar_callback.sql ] ===

=== [dbt templater] Sorting Nodes...
== [models/source/bar/src__bar_callback.sql] PASS
=== [ path: models/source/bar/src__bar_csv.sql ] ===

=== [dbt templater] Sorting Nodes...
== [models/source/bar/src__bar_csv.sql] PASS
==== no fixable linting violations found ====
All Finished 📜 🎉!
  [5 unfixable linting violations found]
```

Something interesting, when pointing at a folder, it behaves slightly different.

```
==== sqlfluff ====
sqlfluff:                0.6.8 python:                  3.9.6
implementation:        cpython dialect:             snowflake
verbosity:                   1 templater:                 dbt
dbt:                   =0.21.0

==== finding fixable violations ====
=== [ path: models/source/bar/ ] ===

=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
== [models/source/bar/src__bar.sql] PASS
== [models/source/bar/src__bar_callback.sql] PASS
== [models/source/bar/src__bar_csv.sql] PASS
==== no fixable linting violations found ====
All Finished 📜 🎉!
  [5 unfixable linting violations found]
```

The first run (file per file) took `17.133s` the second one (pointing at folder) took `15.581s` I think this increases exponentially per number of files as each file does `Sorting Nodes...`. The problem would be that to make this work efficiently, we will need to point to the folder when all files in the folder are included and to the file, when not all. It might not be worth it given in most cases with `pre-commit` (which is the one that points per file) we should be getting just a few files most of the time.

---

While writing this I did a full run over my enter structure with all files in the list (as this is how I discovered this through pre-commit --all-files to initially correct all) and it worked 🎉

**Comment by tunetheweb** [comment]
Closing as original issue seems to be resolved. Feel free to open an new issue for your other ask in the last comment.
