### ISSUE TITLE
Creating a .sqlfluffignore causes SQLFluff to crash if symlinks are present

### ISSUE THREAD

**Issue by CyberShadow** [sqlfluff/sqlfluff#1646]
`python -m venv venv` creates a structure with a symlink pointing to its own directory, which would confuse naive recursive directory iterators.

It looks like SQLFluff does something to that effect when parsing `.sqlfluffignore`, resulting in a `RecursionError`:

```
Traceback (most recent call last):
  File "/home/vladimir/work/extern/sqlfluff/venv/bin/sqlfluff", line 33, in <module>
    sys.exit(load_entry_point('sqlfluff', 'console_scripts', 'sqlfluff')())
  File "/home/vladimir/work/extern/sqlfluff/venv/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/vladimir/work/extern/sqlfluff/venv/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/vladimir/work/extern/sqlfluff/venv/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vladimir/work/extern/sqlfluff/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vladimir/work/extern/sqlfluff/venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/vladimir/work/extern/sqlfluff/src/sqlfluff/cli/commands.py", line 713, in parse
    for parsed_string in result:
  File "/home/vladimir/work/extern/sqlfluff/src/sqlfluff/core/linter/linter.py", line 860, in parse_path
    for fname in self.paths_from_path(path):
  File "/home/vladimir/work/extern/sqlfluff/src/sqlfluff/core/linter/linter.py", line 739, in paths_from_path
    for m in matches:
  File "/home/vladimir/work/extern/sqlfluff/venv/lib/python3.9/site-packages/pathspec/pathspec.py", line 190, in match_files
    file_map = util.normalize_files(files, separators=separators)
  File "/home/vladimir/work/extern/sqlfluff/venv/lib/python3.9/site-packages/pathspec/util.py", line 392, in normalize_files
    for path in files:
  File "/home/vladimir/work/extern/sqlfluff/venv/lib/python3.9/site-packages/pathspec/util.py", line 170, in iter_tree_files
    for entry in _iter_tree_entries_next(os.path.abspath(root), '', {}, on_error, follow_links):
  File "/home/vladimir/work/extern/sqlfluff/venv/lib/python3.9/site-packages/pathspec/util.py", line 242, in _iter_tree_entries_next
    for entry in _iter_tree_entries_next(root_full, node_rel, memo, on_error, follow_links):
  File "/home/vladimir/work/extern/sqlfluff/venv/lib/python3.9/site-packages/pathspec/util.py", line 242, in _iter_tree_entries_next
    for entry in _iter_tree_entries_next(root_full, node_rel, memo, on_error, follow_links):
  File "/home/vladimir/work/extern/sqlfluff/venv/lib/python3.9/site-packages/pathspec/util.py", line 242, in _iter_tree_entries_next
    for entry in _iter_tree_entries_next(root_full, node_rel, memo, on_error, follow_links):
  [Previous line repeated 2 more times]
  File "/home/vladimir/work/extern/sqlfluff/venv/lib/python3.9/site-packages/pathspec/util.py", line 210, in _iter_tree_entries_next
    raise RecursionError(real_path=dir_real, first_path=memo[dir_real], second_path=dir_rel)
pathspec.util.RecursionError: ('/home/vladimir/.../venv', '.../venv', '.../venv/venv')
```

(SQLFluff ed23bf6b98396a76efeff816d4ff2700f6fdd4f5)

**Comment by CyberShadow** [comment]
https://github.com/sqlfluff/sqlfluff/blob/8619f79d3304fe1ff6316d537dfad8098e513f17/src/sqlfluff/core/linter/linter.py#L740-L741

This seems like a really wasteful and inefficient way to check if a path matches a mask.
