### ISSUE TITLE
Unexpected exception for long jinja line

### ISSUE THREAD

**Issue by puetsch** [sqlfluff/sqlfluff#1666]
```sql
{{ config (schema='bronze', materialized='view', sort =['id','number'], dist = 'all', tags =['longlonglonglonglong']) }} 

select 1
```

## Expected Behaviour
Parses fine

## Observed Behaviour
```
CRITICAL   [L016] Applying rule L016 threw an Exception: Is this possible? 
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/sqlfluff/core/rules/base.py", line 313, in crawl
    templated_file=templated_file,
  File "/opt/anaconda3/lib/python3.7/site-packages/sqlfluff/rules/L016.py", line 520, in _eval
    fixes = self._eval_line_for_breaks(this_line)
  File "/opt/anaconda3/lib/python3.7/site-packages/sqlfluff/rules/L016.py", line 266, in _eval_line_for_breaks
    raise ValueError("Is this possible?")  # pragma: no cover
ValueError: Is this possible?
CRITICAL   [L016] Applying rule L016 threw an Exception: Is this possible? 
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/sqlfluff/core/rules/base.py", line 313, in crawl
    templated_file=templated_file,
  File "/opt/anaconda3/lib/python3.7/site-packages/sqlfluff/rules/L016.py", line 520, in _eval
    fixes = self._eval_line_for_breaks(this_line)
  File "/opt/anaconda3/lib/python3.7/site-packages/sqlfluff/rules/L016.py", line 266, in _eval_line_for_breaks
    raise ValueError("Is this possible?")  # pragma: no cover
ValueError: Is this possible?
== [test.sql] FAIL
L:   1 | P: 122 | L016 | Unexpected exception: Is this possible?; Could you open an issue at https://github.com/sqlfluff/sqlfluff/issues ? You can ignore this
                       | exception for now, by adding '--noqa: L016' at the end of line 1
L:   2 | P:   1 | L016 | Unexpected exception: Is this possible?; Could you open an issue at https://github.com/sqlfluff/sqlfluff/issues ? You can ignore this
                       | exception for now, by adding '--noqa: L016' at the end of line 2
L:   3 | P:   9 | L016 | Line is too long
==== summary ====

```

## Steps to Reproduce
`sqlfluff lint -v` on the above file

## Dialect
postgres

## Version
0.7.0
Python 3.7.6

## Configuration
```
[sqlfluff]
verbose = 0
nocolor = False
dialect = postgres
templater = jinja
rules = None
exclude_rules = L009,L011,L019,L031,L034
recurse = 0
output_line_length = 160
runaway_limit = 10
ignore_templated_areas = True
encoding = autodetect
# Comma separated list of file extensions to lint.

# NB: This config will only apply in the root folder.
sql_file_exts = .sql,.sql.j2,.dml,.ddl

[sqlfluff:indentation]
indented_joins = False
indented_using_on = True
template_blocks_indent = True

[sqlfluff:templater]
unwrap_wrapped_queries = True

[sqlfluff:templater:jinja]
apply_dbt_builtins = True

[sqlfluff:templater:jinja:macros]
# Macros provided as builtins for dbt projects
dbt_ref = {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
dbt_source = {% macro source(source_name, table) %}{{source_name}}_{{table}}{% endmacro %}
dbt_config = {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}
dbt_var = {% macro var(variable) %}item{% endmacro %}
dbt_is_incremental = {% macro is_incremental() %}True{% endmacro %}

# Some rules can be configured directly from the config common to other rules.
[sqlfluff:rules]
tab_space_size = 4
max_line_length = 120
indent_unit = space
comma_style = trailing
allow_scalar = True
single_table_references = consistent
unquoted_identifiers_policy = all

# Some rules have their own specific config.
[sqlfluff:rules:L003]
lint_templated_tokens = True

[sqlfluff:rules:L007]  # Keywords
operator_new_lines = after

[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = consistent

[sqlfluff:rules:L014]  # Unquoted identifiers
extended_capitalisation_policy = consistent

[sqlfluff:rules:L016]
ignore_comment_lines = False

[sqlfluff:rules:L029]  # Keyword identifiers
unquoted_identifiers_policy = aliases

[sqlfluff:rules:L030]  # Function names
capitalisation_policy = consistent

[sqlfluff:rules:L038]
select_clause_trailing_comma = forbid

[sqlfluff:rules:L040]  # Null & Boolean Literals
capitalisation_policy = consistent

[sqlfluff:rules:L042]
# By default, allow subqueries in from clauses, but not join clauses.
forbid_subquery_in = join

[sqlfluff:rules:L047]  # Consistent syntax to count all rows
prefer_count_1 = False
prefer_count_0 = False

```

**Comment by barrywhart** [comment]
Rule L016 didn't know what to do with the long templated code. Will be fixed in #1795.
