### ISSUE TITLE
Applying rule L043 threw an Exception

### ISSUE THREAD

**Issue by tekumara** [sqlfluff/sqlfluff#2047]
## Expected Behaviour
No exception

## Observed Behaviour
```
CRITICAL   [L043] Applying rule L043 threw an Exception:                                                                                                    
Traceback (most recent call last):                                                                                                                          
  File "/Users/tekumara/code/jaffle-shop/.venv/lib/python3.9/site-packages/sqlfluff/core/rules/base.py", line 324, in crawl
    res = self._eval(
  File "/Users/tekumara/code/jaffle-shop/.venv/lib/python3.9/site-packages/sqlfluff/rules/L043.py", line 218, in _eval
    column_reference_segment = next(
StopIteration
```

## Steps to Reproduce
_models/test.sql_
```
SELECT dv_runid
        ,CASE
                WHEN LEAD(dv_startdateutc) OVER (
                                PARTITION BY rowid ORDER BY dv_startdateutc
                                ) IS NULL
                        THEN 1
                ELSE 0
                END loadstate
FROM d
```
## Version
sqlfluff, version 0.8.2
python 3.9

## Configuration

Default out-of-the-box config.

## Notes

This exception isn't thrown by sqlfluff 0.8.1

**Comment by jpy-git** [comment]
can confirm that I also see this error, I'll take a look this evening

reformatted to only raise the L043 exception
```sql
SELECT
    dv_runid,
    CASE
        WHEN LEAD(dv_startdateutc) OVER (
            PARTITION BY rowid ORDER BY dv_startdateutc
        ) IS NULL
        THEN 1
        ELSE 0
    END AS loadstate
FROM d
```

**Comment by jpy-git** [comment]
Additional test case courtesy of @pwildenhain 

```sql
select
    field_1,
    field_2,
    field_3,
    case
        when coalesce(field_2, field_3) is null then 1 else 0
    end as field_4
from my_table
```
