### ISSUE TITLE
Runtime error when parsing dbt-utils star macro

### ISSUE THREAD

**Issue by deanja** [sqlfluff/sqlfluff#2140]
## Expected Behaviour
Can parse and lint when dbt-utils star macro is used. https://github.com/dbt-labs/dbt-utils/blob/0.8.0/README.md#star-source

 Last known good version was  SQLFluff 0.8.2 with dbt 0.21.1 and dbt-utils 0.7.1

## Observed Behaviour
`sqlfluff parse`  (and lint) exits with runtime error (see stack trace end of page)
```
dbt.exceptions.InvalidConnectionException: Runtime Error
  connection never acquired for thread (16841, 140649731045184), have []
```

`sqlfluff parse` output:
```
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
```

SQLFluff is able to parse a model using a different dbt-utils macro:  `dbt_utils.safe_add('first_column', 'another_column')  

The dbt project is building ok. 

## Steps to Reproduce

Two model files:

bug_model_1.sql
```
 select 
    1 as first_column
    , 2 as another_column
```

bug_model_2.sql
```
select
        {{ dbt_utils.star(from=ref('bug_model_1')) }}
from {{ ref('bug_model_1') }}
```

```
$ sqlfluff parse models/bug_model_2.sql
```

## Dialect
tsql

## Version
sqlfluff, version 0.9.0  (and same for sqlfluff-templater-dbt
Python 3.8.5
dbt-sqlserver 1.0.0

dbt packages
```
packages:
  - package: dbt-labs/dbt_utils
    version: [">=0.8.0", "<0.9.0"]
  - package: calogica/dbt_date
    version: [">=0.5.0", "<0.6.0"]
  - package: dbt-msft/tsql_utils
    version: [">=0.8.1", "<0.9.0"]
  - package: dbt-labs/codegen
    version: [">=0.5.0", "<0.6.0"]
```

## Configuration
```
[sqlfluff]
dialect = tsql
templater = dbt

exclude_rules = L009,L034

[sqlfluff:rules]

max_line_length = 100

comma_style = leading

[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = lower

[sqlfluff:rules:L014]  # Unquoted identifiers
extended_capitalisation_policy = lower

[sqlfluff:rules:L030]  # Function names
capitalisation_policy = lower

[sqlfluff:rules:L040]  # Null & Boolean Literals
capitalisation_policy = lower
```

Full error message:
```
Traceback (most recent call last):
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/sqlfluff/cli/commands.py", line 866, in parse
    parsed_strings = list(lnt.parse_path(path, recurse=recurse))
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 995, in parse_path
    yield self.parse_string(
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 664, in parse_string
    rendered = self.render_string(in_str, fname, config, encoding)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 619, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/sqlfluff_templater_dbt/templater.py", line 330, in process
    processed_result = self._unsafe_process(fname_absolute_path, in_str, config)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/sqlfluff_templater_dbt/templater.py", line 449, in _unsafe_process
    node = self.dbt_compiler.compile_node(
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/compilation.py", line 550, in compile_node
    node = self._compile_node(node, manifest, extra_context)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/compilation.py", line 388, in _compile_node
    compiled_node.compiled_sql = jinja.get_rendered(
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 597, in get_rendered
    return render_template(template, ctx, node)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 548, in render_template
    return template.render(ctx)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 2, in top-level template code
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 332, in __call__
    return self.call_macro(*args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 259, in call_macro
    return macro(*args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 2, in template
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 332, in __call__
    return self.call_macro(*args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 259, in call_macro
    return macro(*args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 11, in template
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/adapters/sql/impl.py", line 179, in get_columns_in_relation
    return self.execute_macro(
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/adapters/base/impl.py", line 992, in execute_macro
    result = macro_function(**kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 332, in __call__
    return self.call_macro(*args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 259, in call_macro
    return macro(*args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 2, in template
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 332, in __call__
    return self.call_macro(*args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 259, in call_macro
    return macro(*args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 2, in template
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 332, in __call__
    return self.call_macro(*args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 259, in call_macro
    return macro(*args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 10, in template
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/adapters/base/impl.py", line 225, in execute
    return self.connections.execute(
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/adapters/sqlserver/connections.py", line 460, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/adapters/sqlserver/connections.py", line 407, in add_query
    connection = self.get_thread_connection()
  File "/home/deanjackson/.cache/pypoetry/virtualenvs/stack-2-bQukt7Bs-py3.8/lib/python3.8/site-packages/dbt/adapters/base/connections.py", line 69, in get_thread_connection
    raise dbt.exceptions.InvalidConnectionException(
dbt.exceptions.InvalidConnectionException: Runtime Error
  connection never acquired for thread (16841, 140649731045184), have []
```

**Comment by ciklista** [comment]
I receive the same error when parsing a file using a macro from `dbt-date` (https://github.com/calogica/dbt-date)

My model is 

```
{{
    config(
        sort=['date_day'],
        alias='dates'
    )
}}

{{ dbt_date.get_date_dimension('2020-01-01', '2022-12-31') }}

```

Dialect is `redshift`.

**Comment by ciklista** [comment]
I assume that this is very similar, if not the same problem as https://github.com/sqlfluff/sqlfluff/issues/2113

**Comment by deanja** [comment]
Thanks for spotting that.  Will close this - it might be useful as a test case.
