### ISSUE TITLE
dbt running from sqlfluff can't find profile

### ISSUE THREAD

**Issue by wrborigin** [sqlfluff/sqlfluff#2253]
## Expected Behaviour

Running sqlfluff should work.

## Observed Behaviour

When running sqlfluff, I get this error:

```
+ sqlfluff lint
==== sqlfluff ====
sqlfluff:                0.9.0 python:                  3.8.5
implementation:        cpython dialect:              postgres
verbosity:                   1 templater:                 dbt
dbt:                    =1.0.0

==== readout ====

=== [ path: /opt/jenkins/workspace/ranch-job_feature_dbt-1-0 ] ===

=== [dbt templater] Sorting Nodes...
Traceback (most recent call last):
  File "/usr/local/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/cli/commands.py", line 480, in lint
    result = lnt.lint_paths(
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/linter/linter.py", line 964, in lint_paths
    self.lint_path(
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/linter/linter.py", line 916, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/linter/runner.py", line 40, in iter_rendered
    for fname in self.linter.templater.sequence_files(
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff_templater_dbt/templater.py", line 270, in sequence_files
    for key, node in self.dbt_manifest.nodes.items():
  File "/usr/local/lib/python3.8/dist-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff_templater_dbt/templater.py", line 153, in dbt_manifest
    projects = self.dbt_config.load_dependencies()
  File "/usr/local/lib/python3.8/dist-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff_templater_dbt/templater.py", line 100, in dbt_config
    self.dbt_config = DbtRuntimeConfig.from_args(
  File "/usr/local/lib/python3.8/dist-packages/dbt/config/runtime.py", line 242, in from_args
    project, profile = cls.collect_parts(args)
  File "/usr/local/lib/python3.8/dist-packages/dbt/config/runtime.py", line 216, in collect_parts
    profile = cls._get_rendered_profile(
  File "/usr/local/lib/python3.8/dist-packages/dbt/config/runtime.py", line 194, in _get_rendered_profile
    return Profile.render_from_args(
  File "/usr/local/lib/python3.8/dist-packages/dbt/config/profile.py", line 440, in render_from_args
    return cls.from_raw_profiles(
  File "/usr/local/lib/python3.8/dist-packages/dbt/config/profile.py", line 387, in from_raw_profiles
    raise DbtProjectError(
dbt.exceptions.DbtProjectError: Runtime Error
  Could not find profile named 'default'
script returned exit code 1
```

but if I run dbt itself from the same shell, it works:

```
+ dbt debug
11:00:23  Running with dbt=1.0.0
dbt version: 1.0.0
python version: 3.8.5
python path: /usr/bin/python3
os info: Linux-5.8.0-1041-aws-x86_64-with-glibc2.29
Using profiles.yml file at /opt/jenkins/workspace/ranch-job_feature_dbt-1-0/profiles.yml
Using dbt_project.yml file at /opt/jenkins/workspace/ranch-job_feature_dbt-1-0/dbt_project.yml

Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [OK found and valid]

Required dependencies:
 - git [OK found]

Connection:
  host: [redacted]
  port: 443
  user: ****
  database: [redacted]
  schema: [redacted]
  Connection test: [OK connection ok]

All checks passed!
```

## Steps to Reproduce

This happens when I run sqlfluff in Jenkins. I was not able to reproduce this on my local machine, which is pretty strange.

Previous version (using dbt 0.21.0 and sqlfluff 0.7.0) worked with the same setup.

I'm using env variable `DBT_PROFILES_DIR` to point to Jenkins workspace, which has the checked-out git repo.

I am struggling to debug this further - the best would be if I could somehow run `dbt debug` from sqlfluff to see which paths that one sees?

## Dialect

Postgres (it's actually Trino but there's not Trino dialect)

## Version
sqlfluff:                0.9.0 python:                  3.8.5
implementation:        cpython dialect:              postgres
verbosity:                   1 templater:                 dbt
dbt:                    =1.0.0

## Configuration
```
[sqlfluff]
templater = dbt
# dbt templating does not keep trailing new lines (L009)
exclude_rules = L009
dialect = postgres
```

**Comment by barrywhart** [comment]
@NiallRees, any ideas about this?

**Comment by tomasfarias** [comment]
I'm running a very similar setup to @wrborigin: Running `sqlfluff` v0.9.1, with dbt-core==1 and dbt templater, in Jenkins, while setting a custom `DBT_PROFILE_DIR`, causes a RuntimeError. The only difference I see from the logs is I'm running Python3.9.

I was able to workaround the issue by moving my `profiles.yml` to the default `~/.dbt/profiles.yml` just before running sqlfluff, and un-setting my `DBT_PROFILES_DIR` env variable:

Raises RuntimeError:
```
withEnv(["DBT_PROFILES_DIR=${MY_DIR}"]) {
    sh "python -m sqlfluff lint"
}
```

Works:
```
sh "mkdir ~/.dbt"
sh "cp ${MY_DIR}/profiles.yml ~/.dbt/profiles.yml"
sh "python -m sqlfluff lint"
```

Hopefully, this can help debug the issue or at least provide a workaround for other folks like @wrborigin and me.

**Comment by tomasfarias** [comment]
I've been digging a bit into this issue and think it may be a bug with dbt when uppercase characters are used in `DBT_PROFILES_DIR`, as the path is converted to lowercase [here](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/flags.py#L141), but the lowercase path does not exist, so an empty profile is returned!

Example:
```python
In [1]: import os

In [2]: os.environ["DBT_PROFILES_DIR"] = "/home/<my user>/TEST/PATH"

In [3]: os.makedirs("/home/<my user>/TEST/PATH")

In [4]: os.path.exists("/home/<my user>/TEST/PATH")
Out[4]: True

In [5]: from dbt import flags

In [6]: flags.set_from_args("", {})

In [7]: flags.PROFILES_DIR
Out[7]: '/home/<my user>/test/path'

In [8]: os.path.exists(flags.PROFILES_DIR)
Out[8]: False
```

This would explain my situation as my Jenkins variable contains uppercase characters.

**Comment by wrborigin** [comment]
Yeah, unsetting `DBT_PROFILES_DIR` and copying the `profiles.yml` to `~/.dbt` fixed the for me as well. My path(s) have no uppercase letter, so I'm not sure it is the same issue?

**Comment by tomasfarias** [comment]
You may try running something similar to my interactive session and try out your path as there is also some [path normalization](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/flags.py#L160) going on that could be affecting your final `PROFILES_DIR` value.

Regardless, I'm glad the workaround worked, and perhaps both issues may be solved by reading the user config from `flags.PROFILES_DIR` like dbt does.

**Comment by jpy-git** [comment]
@tomasfarias as far as I'm aware the dbt templater is using `flags.PROFILES_DIR`:
https://github.com/sqlfluff/sqlfluff/blob/6815d913ebe2723750ae11f0a0aed2d900a53c6a/plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py#L192-L215

It should get the profile from `flags.PROFILES_DIR` unless specifically overwritten in your sqlfluff config.

If you're interested in taking a look then that function is a good place to start 😄

**Comment by barrywhart** [comment]
@wrborigin, @tomasfarias: Can one of you provide details instructions (and accompanying files) to reproduce this issue? Without this amount of detail, it's unlikely we can fix the issue (maintainers want to fix bugs, and often don't have time to guess how to reproduce them).

**Comment by tomasfarias** [comment]
@barrywhart Of course, let me preface by saying that the effort of the maintainers and contributors is much appreciated, thank you!

I'll include here a step by step reproduction of the issue starting from a clean dbt sample project:

1. Start with a clean dbt sample project

```bash
pip install dbt-core==1
mkdir test-sqlfluff
cd test-sqlfluff
dbt init test-project  # Ignore settings, just create the project
❯ ls test-project
analyses  data	dbt_project.yml  macros  models  README.md  snapshots  tests
```

2. Create a profiles directory that contains UPPERCASE letters in the path:
```bash
mkdir DBT_PROFILES
```

3. Create a profiles.yml in the UPPERCASE dir:

```bash
cat DBT_PROFILES/profiles.yml
test:
  target: dev
  outputs:
    dev:
      type: redshift
      host: <host>
      threads: 1
      port: <port>
      user: <user>
      dbname: <dbname>
      schema: test
      password: <password>
```
I've removed the connection parameters. I've only tested this with a Redshift connector.

4. Create the following .sqlfluff file in test-project

```bash
cat test-project/.sqlfluff
[sqlfluff]
templater = dbt
```

5. Change the profile in db_project.yml (and the name too), the result should look like:

```sh
cat test-project/dbt_project.yml
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'testproject'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'test'
```
The rest of the lines were omitted as they did not change from the default dbt_project.yml.

6. Install and run sqlfluff with the DBT_PROFILES_DIR environment variable:

```bash
cd test-project
pip install sqlfluff==0.9.1 sqlfluff-templater-dbt==0.9.1
DBT_PROFILES_DIR="/home/tomasfarias/test-sqlfluff/DBT_PROFILES/" sqlfluff lint models/example/my_first_dbt_model.sql
```

Raises an exception:

```
=== [dbt templater] Sorting Nodes...
Traceback (most recent call last):
  File "/home/tomasfarias/.pyenv/versions/3.9.9/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 497, in lint
    result = lnt.lint_paths(
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 974, in lint_paths
    self.lint_path(
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 926, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 40, in iter_rendered
    for fname in self.linter.templater.sequence_files(
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 271, in sequence_files
    for key, node in self.dbt_manifest.nodes.items():
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/functools.py", line 982, in __get__
    val = self.func(instance)
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 154, in dbt_manifest
    projects = self.dbt_config.load_dependencies()
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/functools.py", line 982, in __get__
    val = self.func(instance)
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 101, in dbt_config
    self.dbt_config = DbtRuntimeConfig.from_args(
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/dbt/config/runtime.py", line 242, in from_args
    project, profile = cls.collect_parts(args)
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/dbt/config/runtime.py", line 216, in collect_parts
    profile = cls._get_rendered_profile(
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/dbt/config/runtime.py", line 194, in _get_rendered_profile
    return Profile.render_from_args(
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/dbt/config/profile.py", line 440, in render_from_args
    return cls.from_raw_profiles(
  File "/home/tomasfarias/.pyenv/versions/3.9.9/lib/python3.9/site-packages/dbt/config/profile.py", line 387, in from_raw_profiles
    raise DbtProjectError(
dbt.exceptions.DbtProjectError: Runtime Error
  Could not find profile named 'test'
```

6. Downgrade to dbt-core==0.21, back-port dbt_project.yml, and try again:

```bash
pip install dbt-core==0.21 dbt-redshift==0.21
DBT_PROFILES_DIR="/home/tomasfarias/test-sqlfluff/DBT_PROFILES/" sqlfluff lint models/example/my_first_dbt_model.sql
=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
== [models/example/my_first_dbt_model.sql] FAIL                                                                               
L:   1 | P:   1 | L050 | Files must not begin with newlines or whitespace.
All Finished 📜 🎉!
```

It works!

7. Upgrade to dbt-core==1 again, restore dbt_project.yml, mv profiles.yml to a directory without UPPERCASE characters,  and try again:

```bash
cd ..
mkdir dbt_profiles
mv DBT_PROFILES/profiles.yml dbt_profiles/profiles.yml
cd test-project
pip install dbt-core==1 dbt-redshift==1
DBT_PROFILES_DIR="/home/tomasfarias/test-sqlfluff/DBT_PROFILES/" sqlfluff lint models/example/my_first_dbt_model.sql
=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
== [models/example/my_first_dbt_model.sql] FAIL                                                                               
L:   1 | P:   1 | L050 | Files must not begin with newlines or whitespace.
```

Works again! Notice I haven't changed the environment variable: it still points to `DBT_PROFILES` even though the file `DBT_PROFILES/profiles.yml` has been moved.

8. Just having fun: find your dbt installation, look for the `dbt/flags.py` file and change the `get_flag_value` function to `print` some things:

```python
def get_flag_value(flag, args, user_config):
    lc_flag = flag.lower()
    flag_value = getattr(args, lc_flag, None)
    if flag_value is None:
        # Environment variables use pattern 'DBT_{flag name}'
        env_flag = f"DBT_{flag}"
        env_value = os.getenv(env_flag)
        if env_value is not None and env_value != '':
            print(f"Hey, PROFILES_DIR is: {env_value}")
            env_value = env_value.lower()
            print(f"Look, now it's lowercased: {env_value}")
            # non Boolean values
            if flag in [
                'LOG_FORMAT',
                'PRINTER_WIDTH',
                'PROFILES_DIR',
                'INDIRECT_SELECTION',
                'EVENT_BUFFER_SIZE'
            ]:
                flag_value = env_value
            else:
                flag_value = env_set_bool(env_value)
        elif user_config is not None and getattr(user_config, lc_flag, None) is not None:
            flag_value = getattr(user_config, lc_flag)
        else:
            flag_value = flag_defaults[flag]
    if flag in ['PRINTER_WIDTH', 'EVENT_BUFFER_SIZE']:  # must be ints
        flag_value = int(flag_value)
    if flag == 'PROFILES_DIR':
        flag_value = os.path.abspath(flag_value)

    print(f"This is what the flag is now set to: {flag_value}")
    return flag_value
```

And run again:
```
❯ DBT_PROFILES_DIR="/home/tomasfarias/test-sqlfluff/DBT_PROFILES/" sqlfluff lint models/example/my_first_dbt_model.sql
=== [dbt templater] Sorting Nodes...
...
Hey, PROFILES_DIR is: /home/tomasfarias/test-sqlfluff/DBT_PROFILES/
Look, now it's lowercased: /home/tomasfarias/test-sqlfluff/dbt_profiles/
This is what the flag is now set to: /home/tomasfarias/test-sqlfluff/dbt_profiles
...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
== [models/example/my_first_dbt_model.sql] FAIL                                                                               
L:   1 | P:   1 | L050 | Files must not begin with newlines or whitespace.
All Finished 📜 🎉!
```

So yeah, that's it: when sqlfluff attempts to set the flags via `set_from_args`, it's re-setting the PROFILES_DIR flag to a lowercased value, causing it to point to a different directory. If this directory does not exist (like in the first run), then we fail.

Notice how before dbt sets the flags by calling `set_from_args` it actually reads the profile from the original (not `lower()` called) PROFILES_DIR: https://github.com/dbt-labs/dbt-core/blob/6855fe06a7d56f1c68363bea2472fe7128f95b3c/core/dbt/main.py#L170

sqlfluff is not doing this, and maybe it should, just for testing, I've modified `sqlfluff_templater_dbt/templapter.py` to:

```python
    @cached_property
    def dbt_config(self):
        """Loads the dbt config."""
        if self.dbt_version_tuple >= (1, 0):
            user_config = read_user_config(flags.PROFILES_DIR)
            flags.set_from_args(
                DbtConfigArgs(
                    project_dir=self.project_dir,
                    profiles_dir=self.profiles_dir,
                    profile=self._get_profile(),
                ),
                user_config,
            )
```

And now the first example that failed works:

```bash
mv dbt_profiles/profiles.yml DBT_PROFILES/profiles.yml
rm -rf dbt_profiles
DBT_PROFILES_DIR="/home/tomasfarias/test-sqlfluff/DBT_PROFILES/" sqlfluff lint models/example/my_first_dbt_model.sql
=== [dbt templater] Sorting Nodes...
...
This is what the flag is now set to: /home/tomasfarias/test-sqlfluff/DBT_PROFILES
...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
== [models/example/my_first_dbt_model.sql] FAIL                                                                               
L:   1 | P:   1 | L050 | Files must not begin with newlines or whitespace.
```

Not sure if that would be the exact solution, just mentioning that doing the same thing as dbt does, appears to work. Notice how this time, the flag doesn't change, as dbt finds it in the `user_config` and doesn't need to look at the environment (and do the `lower()` call).

Hopefully this step-by-step helps you identify the issue. I can provide more details or work on a fix too! Thanks again.

**Comment by tomasfarias** [comment]
Forgot to add that I'm not 100% sure if this is the same issue @wrborigin was experiencing as their DBT_PROFILES_DIR did not contain any UPPERCASE characters. But, since the workaround seemed to work for both of us, it may be.

**Comment by wrborigin** [comment]
I was not able to reproduce it on my local machine. It is if the env variables work differently between systems.

But with the "create `~/.dbt/profiles.yml` in your docker" workaround, it is annoying but not blocking anything, so I dunno if it's worth looking into.

**Comment by barrywhart** [comment]
I'll leave this issue open, and we'll look at @tomasfarias case. Thanks!
