### ISSUE TITLE
Linting throws "IndexError: list index out of range" on a valid syntax, snowflake 0.9.1

### ISSUE THREAD

**Issue by ahladkyi-spd** [sqlfluff/sqlfluff#2301]
In version 0.9.1, linting valid snowflake sql files started throwing exceptions. Smallest snippet to reproduce is 

```
SELECT MYCOLUMN1 FROM @public.mytable1 --noqa: L020,L027,L044
```
Adding `noqa` comments or `--ignore linting` doesn't help. Also this seems to happen on a complete different expressions too, but I assume it's the same bug.

## Expected Behaviour
No errors

## Observed Behaviour
```
CRITICAL   [L020] Applying rule L020 threw an Exception: list index out of range 
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\sqlfluff\core\rules\base.py", line 504, in crawl
    res = self._eval(
  File "C:\Python39\lib\site-packages\sqlfluff\rules\L020.py", line 99, in _eval
    select_info = get_select_statement_info(context.segment, context.dialect)
  File "C:\Python39\lib\site-packages\sqlfluff\core\rules\analysis\select.py", line 26, in get_select_statement_info
    table_aliases, standalone_aliases = get_aliases_from_select(segment, dialect)
  File "C:\Python39\lib\site-packages\sqlfluff\core\rules\analysis\select.py", line 106, in get_aliases_from_select
    aliases = fc.get_eventual_aliases()
  File "C:\Python39\lib\site-packages\sqlfluff\dialects\dialect_ansi.py", line 1426, in get_eventual_aliases
    ref: AliasInfo = clause.get_eventual_alias()
  File "C:\Python39\lib\site-packages\sqlfluff\dialects\dialect_ansi.py", line 1116, in get_eventual_alias
    penultimate_ref: ObjectReferenceSegment.ObjectReferencePart = list(
IndexError: list index out of range
CRITICAL   [L027] Applying rule L027 threw an Exception: list index out of range
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\sqlfluff\core\rules\base.py", line 504, in crawl
    res = self._eval(
  File "C:\Python39\lib\site-packages\sqlfluff\rules\L020.py", line 99, in _eval
    select_info = get_select_statement_info(context.segment, context.dialect)
  File "C:\Python39\lib\site-packages\sqlfluff\core\rules\analysis\select.py", line 26, in get_select_statement_info
    table_aliases, standalone_aliases = get_aliases_from_select(segment, dialect)
  File "C:\Python39\lib\site-packages\sqlfluff\core\rules\analysis\select.py", line 106, in get_aliases_from_select
    aliases = fc.get_eventual_aliases()
  File "C:\Python39\lib\site-packages\sqlfluff\dialects\dialect_ansi.py", line 1426, in get_eventual_aliases
    ref: AliasInfo = clause.get_eventual_alias()
  File "C:\Python39\lib\site-packages\sqlfluff\dialects\dialect_ansi.py", line 1116, in get_eventual_alias
    penultimate_ref: ObjectReferenceSegment.ObjectReferencePart = list(
IndexError: list index out of range
CRITICAL   [L044] Applying rule L044 threw an Exception: list index out of range
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\sqlfluff\core\rules\base.py", line 504, in crawl
    res = self._eval(
  File "C:\Python39\lib\site-packages\sqlfluff\rules\L044.py", line 136, in _eval
    return self._analyze_result_columns(crawler.query_tree)
  File "C:\Python39\lib\site-packages\sqlfluff\rules\L044.py", line 88, in _analyze_result_columns
    for wildcard in selectable.get_wildcard_info():
  File "C:\Python39\lib\site-packages\sqlfluff\core\rules\analysis\select_crawler.py", line 44, in get_wildcard_info
    for seg in self.select_info.select_targets:
  File "C:\Python39\lib\functools.py", line 969, in __get__
    val = self.func(instance)
  File "C:\Python39\lib\site-packages\sqlfluff\core\rules\analysis\select_crawler.py", line 37, in select_info
    return get_select_statement_info(
  File "C:\Python39\lib\site-packages\sqlfluff\core\rules\analysis\select.py", line 26, in get_select_statement_info
    table_aliases, standalone_aliases = get_aliases_from_select(segment, dialect)
  File "C:\Python39\lib\site-packages\sqlfluff\core\rules\analysis\select.py", line 106, in get_aliases_from_select
    aliases = fc.get_eventual_aliases()
  File "C:\Python39\lib\site-packages\sqlfluff\dialects\dialect_ansi.py", line 1426, in get_eventual_aliases
    ref: AliasInfo = clause.get_eventual_alias()
  File "C:\Python39\lib\site-packages\sqlfluff\dialects\dialect_ansi.py", line 1116, in get_eventual_alias
    penultimate_ref: ObjectReferenceSegment.ObjectReferencePart = list(
IndexError: list index out of range
All Finished 📜 🎉!
```

## Steps to Reproduce
`sqlfluff lint test.sql   --dialect snowflake`

## Dialect
snowflake

## Version
sqlfluff, version 0.9.1
Python 3.9.2

## Configuration
default

## Parse output
```
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        select_statement:
[L:  1, P:  1]      |            select_clause:
[L:  1, P:  1]      |                keyword:                                      'SELECT'
[L:  1, P:  7]      |                [META] indent:
[L:  1, P:  7]      |                whitespace:                                   ' '
[L:  1, P:  8]      |                select_clause_element:
[L:  1, P:  8]      |                    column_reference:
[L:  1, P:  8]      |                        identifier:                           'MYCOLUMN1'
[L:  1, P: 17]      |            whitespace:                                       ' '
[L:  1, P: 18]      |            [META] dedent:
[L:  1, P: 18]      |            from_clause:
[L:  1, P: 18]      |                keyword:                                      'FROM'
[L:  1, P: 22]      |                whitespace:                                   ' '
[L:  1, P: 23]      |                from_expression:
[L:  1, P: 23]      |                    [META] indent:
[L:  1, P: 23]      |                    from_expression_element:
[L:  1, P: 23]      |                        table_expression:
[L:  1, P: 23]      |                            table_reference:
[L:  1, P: 23]      |                                stage_path:                   '@public.mytable1'
[L:  1, P: 39]      |                    [META] dedent:
[L:  1, P: 39]      |    whitespace:                                               ' '
[L:  1, P: 40]      |    comment:                                                  '--noqa: L020,L027,L044'
[L:  1, P: 62]      |    newline:                                                  '\n'
```

**Comment by jpy-git** [comment]
@chwiese could you look at re-splitting stage_path out as before please?

**Comment by ahladkyi-spd** [comment]
I'm also having this exception on a syntax without stage_path, snippet:
```
DELETE FROM MYTABLE1
    USING (
        WITH MYCTE AS (SELECT COLUMN2 FROM MYTABLE3)
        SELECT COLUMN3 FROM MYTABLE3
    ) X
WHERE COLUMN1 = X.COLUMN3
```
output
```
CRITICAL   [L044] Applying rule L044 threw an Exception:  
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\sqlfluff\core\rules\base.py", line 504, in crawl
    res = self._eval(
  File "C:\Python39\lib\site-packages\sqlfluff\rules\L044.py", line 136, in _eval
    return self._analyze_result_columns(crawler.query_tree)
  File "C:\Python39\lib\site-packages\sqlfluff\rules\L044.py", line 85, in _analyze_result_columns
    assert query.selectables
AssertionError
All Finished 📜 🎉!
```
parse output
```
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        delete_statement:
[L:  1, P:  1]      |            keyword:                                          'DELETE'  
[L:  1, P:  7]      |            whitespace:                                       ' '       
[L:  1, P:  8]      |            from_clause:
[L:  1, P:  8]      |                keyword:                                      'FROM'    
[L:  1, P: 12]      |                whitespace:                                   ' '       
[L:  1, P: 13]      |                from_expression:
[L:  1, P: 13]      |                    [META] indent:
[L:  1, P: 13]      |                    from_expression_element:
[L:  1, P: 13]      |                        table_expression:
[L:  1, P: 13]      |                            table_reference:
[L:  1, P: 13]      |                                identifier:                   'MYTABLE1'
[L:  1, P: 21]      |                    [META] dedent:
[L:  1, P: 21]      |            newline:                                          '\n'      
[L:  2, P:  1]      |            whitespace:                                       '    '    
[L:  2, P:  5]      |            using_clause:
[L:  2, P:  5]      |                keyword:                                      'USING'   
[L:  2, P: 10]      |                whitespace:                                   ' '       
[L:  2, P: 11]      |                from_expression_element:
[L:  2, P: 11]      |                    table_expression:
[L:  2, P: 11]      |                        bracketed:
[L:  2, P: 11]      |                            start_bracket:                    '('       
[L:  2, P: 12]      |                            [META] indent:
[L:  2, P: 12]      |                            newline:                          '\n'
[L:  3, P:  1]      |                            whitespace:                       '        '
[L:  3, P:  9]      |                            with_compound_statement:
[L:  3, P:  9]      |                                keyword:                      'WITH'
[L:  3, P: 13]      |                                whitespace:                   ' '
[L:  3, P: 14]      |                                common_table_expression:
[L:  3, P: 14]      |                                    identifier:               'MYCTE'
[L:  3, P: 19]      |                                    whitespace:               ' '
[L:  3, P: 20]      |                                    keyword:                  'AS'
[L:  3, P: 22]      |                                    whitespace:               ' '
[L:  3, P: 23]      |                                    bracketed:
[L:  3, P: 23]      |                                        start_bracket:        '('
[L:  3, P: 24]      |                                        [META] indent:
[L:  3, P: 24]      |                                        select_statement:
[L:  3, P: 24]      |                                            select_clause:
[L:  3, P: 24]      |                                                keyword:      'SELECT'
[L:  3, P: 30]      |                                                [META] indent:
[L:  3, P: 30]      |                                                whitespace:   ' '
[L:  3, P: 31]      |                                                select_clause_element:
[L:  3, P: 31]      |                                                    column_reference:
[L:  3, P: 31]      |                                                        identifier:  'COLUMN2'
[L:  3, P: 38]      |                                            whitespace:       ' '
[L:  3, P: 39]      |                                            [META] dedent:
[L:  3, P: 39]      |                                            from_clause:
[L:  3, P: 39]      |                                                keyword:      'FROM'
[L:  3, P: 43]      |                                                whitespace:   ' '
[L:  3, P: 44]      |                                                from_expression:
[L:  3, P: 44]      |                                                    [META] indent:
[L:  3, P: 44]      |                                                    from_expression_element:
[L:  3, P: 44]      |                                                        table_expression:
[L:  3, P: 44]      |                                                            table_reference:
[L:  3, P: 44]      |                                                                identifier:  'MYTABLE3'
[L:  3, P: 52]      |                                                    [META] dedent:
[L:  3, P: 52]      |                                        [META] dedent:
[L:  3, P: 52]      |                                        end_bracket:          ')'
[L:  3, P: 53]      |                                newline:                      '\n'
[L:  4, P:  1]      |                                whitespace:                   '        '
[L:  4, P:  9]      |                                select_statement:
[L:  4, P:  9]      |                                    select_clause:
[L:  4, P:  9]      |                                        keyword:              'SELECT'
[L:  4, P: 15]      |                                        [META] indent:
[L:  4, P: 16]      |                                        select_clause_element:
[L:  4, P: 16]      |                                            column_reference:
[L:  4, P: 16]      |                                                identifier:   'COLUMN3'
[L:  4, P: 23]      |                                    whitespace:               ' '
[L:  4, P: 24]      |                                    [META] dedent:
[L:  4, P: 24]      |                                    from_clause:
[L:  4, P: 24]      |                                        keyword:              'FROM'
[L:  4, P: 28]      |                                        whitespace:           ' '
[L:  4, P: 29]      |                                        from_expression:
[L:  4, P: 29]      |                                            [META] indent:
[L:  4, P: 29]      |                                            from_expression_element:
[L:  4, P: 29]      |                                                table_expression:
[L:  4, P: 29]      |                                                    table_reference:
[L:  4, P: 29]      |                                                        identifier:  'MYTABLE3'
[L:  4, P: 37]      |                                            [META] dedent:
[L:  4, P: 37]      |                            newline:                          '\n'
[L:  5, P:  1]      |                            whitespace:                       '    '
[L:  5, P:  5]      |                            [META] dedent:
[L:  5, P:  5]      |                            end_bracket:                      ')'
[L:  5, P:  6]      |                    whitespace:                               ' '
[L:  5, P:  7]      |                    alias_expression:
[L:  5, P:  7]      |                        identifier:                           'X'
[L:  5, P:  8]      |            newline:                                          '\n'
[L:  6, P:  1]      |            where_clause:
[L:  6, P:  1]      |                keyword:                                      'WHERE'
[L:  6, P:  6]      |                [META] indent:
[L:  6, P:  6]      |                whitespace:                                   ' '
[L:  6, P:  7]      |                expression:
[L:  6, P:  7]      |                    column_reference:
[L:  6, P:  7]      |                        identifier:                           'COLUMN1'
[L:  6, P: 14]      |                    whitespace:                               ' '
[L:  6, P: 15]      |                    comparison_operator:
[L:  6, P: 15]      |                        raw_comparison_operator:              '='
[L:  6, P: 16]      |                    whitespace:                               ' '
[L:  6, P: 17]      |                    column_reference:
[L:  6, P: 17]      |                        identifier:                           'X'
[L:  6, P: 18]      |                        dot:                                  '.'
[L:  6, P: 19]      |                        identifier:                           'COLUMN3'
[L:  6, P: 26]      |                [META] dedent:
```

**Comment by barrywhart** [comment]
This line in `dialect_ansi.py` is failing:
```
            penultimate_ref: ObjectReferenceSegment.ObjectReferencePart = list(
                ref.iter_raw_references()
            )[-1]
```

It fails because in Snowflake, `iter_raw_references()` no longer returns anything. It's looking for descendant segments of type `identifier` and not finding any:
```
        for elem in self.recursive_crawl("identifier"):
            yield from self._iter_reference_parts(elem)
```

And that's because the `TableReferenceSegment` has only a single descendant, a `CodeSegment`:
```
(Pdb) self
<TableReferenceSegment: ([L:  1, P: 23])>
(Pdb) self.segments
(<CodeSegment: ([L:  1, P: 23]) '@public.mytable1'>,)
(Pdb) self.segments[0].segments
[]
```

**Comment by barrywhart** [comment]
@chwiese: Would you be wiling to look into this? It seems like it's related to your recently merged PR, #2250.

**Comment by barrywhart** [comment]
0.9.0:
```
[L:  1, P: 18]      |            from_clause:
[L:  1, P: 18]      |                keyword:                                      'FROM'
[L:  1, P: 22]      |                whitespace:                                   ' '
[L:  1, P: 23]      |                from_expression:
[L:  1, P: 23]      |                    [META] indent:
[L:  1, P: 23]      |                    from_expression_element:
[L:  1, P: 23]      |                        table_expression:
[L:  1, P: 23]      |                            internal_external_stage:
[L:  1, P: 23]      |                                literal:                      '@'
[L:  1, P: 24]      |                                identifier:                   'public'
[L:  1, P: 30]      |                                dot:                          '.'
[L:  1, P: 31]      |                                identifier:                   'mytable1'
[L:  1, P: 39]      |                    [META] dedent:
```

0.9.1:
```
[L:  1, P: 23]      |                from_expression:
[L:  1, P: 23]      |                    [META] indent:
[L:  1, P: 23]      |                    from_expression_element:
[L:  1, P: 23]      |                        table_expression:
[L:  1, P: 23]      |                            table_reference:
[L:  1, P: 23]      |                                stage_path:                   '@public.mytable1'
[L:  1, P: 39]      |                    [META] dedent:
```

**Comment by chwiese** [comment]
@jpy-git, @barrywhart: I will have a look over  the weekend.

**Comment by barrywhart** [comment]
Thanks!

**Comment by chwiese** [comment]
@ahladkyi-spd [this](https://github.com/sqlfluff/sqlfluff/issues/2301#issuecomment-1012292979) is a separate issue, for which I have created #2319 .
