### ISSUE TITLE
L044 throws assertion exception

### ISSUE THREAD

**Issue by chwiese** [sqlfluff/sqlfluff#2319]
I'm also having this exception on a syntax without stage_path, snippet:
```
DELETE FROM MYTABLE1
    USING (
        WITH MYCTE AS (SELECT COLUMN2 FROM MYTABLE3)
        SELECT COLUMN3 FROM MYTABLE3
    ) X
WHERE COLUMN1 = X.COLUMN3
```
output
```
CRITICAL   [L044] Applying rule L044 threw an Exception:  
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\sqlfluff\core\rules\base.py", line 504, in crawl
    res = self._eval(
  File "C:\Python39\lib\site-packages\sqlfluff\rules\L044.py", line 136, in _eval
    return self._analyze_result_columns(crawler.query_tree)
  File "C:\Python39\lib\site-packages\sqlfluff\rules\L044.py", line 85, in _analyze_result_columns
    assert query.selectables
AssertionError
All Finished 📜 🎉!
```
parse output
```
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        delete_statement:
[L:  1, P:  1]      |            keyword:                                          'DELETE'  
[L:  1, P:  7]      |            whitespace:                                       ' '       
[L:  1, P:  8]      |            from_clause:
[L:  1, P:  8]      |                keyword:                                      'FROM'    
[L:  1, P: 12]      |                whitespace:                                   ' '       
[L:  1, P: 13]      |                from_expression:
[L:  1, P: 13]      |                    [META] indent:
[L:  1, P: 13]      |                    from_expression_element:
[L:  1, P: 13]      |                        table_expression:
[L:  1, P: 13]      |                            table_reference:
[L:  1, P: 13]      |                                identifier:                   'MYTABLE1'
[L:  1, P: 21]      |                    [META] dedent:
[L:  1, P: 21]      |            newline:                                          '\n'      
[L:  2, P:  1]      |            whitespace:                                       '    '    
[L:  2, P:  5]      |            using_clause:
[L:  2, P:  5]      |                keyword:                                      'USING'   
[L:  2, P: 10]      |                whitespace:                                   ' '       
[L:  2, P: 11]      |                from_expression_element:
[L:  2, P: 11]      |                    table_expression:
[L:  2, P: 11]      |                        bracketed:
[L:  2, P: 11]      |                            start_bracket:                    '('       
[L:  2, P: 12]      |                            [META] indent:
[L:  2, P: 12]      |                            newline:                          '\n'
[L:  3, P:  1]      |                            whitespace:                       '        '
[L:  3, P:  9]      |                            with_compound_statement:
[L:  3, P:  9]      |                                keyword:                      'WITH'
[L:  3, P: 13]      |                                whitespace:                   ' '
[L:  3, P: 14]      |                                common_table_expression:
[L:  3, P: 14]      |                                    identifier:               'MYCTE'
[L:  3, P: 19]      |                                    whitespace:               ' '
[L:  3, P: 20]      |                                    keyword:                  'AS'
[L:  3, P: 22]      |                                    whitespace:               ' '
[L:  3, P: 23]      |                                    bracketed:
[L:  3, P: 23]      |                                        start_bracket:        '('
[L:  3, P: 24]      |                                        [META] indent:
[L:  3, P: 24]      |                                        select_statement:
[L:  3, P: 24]      |                                            select_clause:
[L:  3, P: 24]      |                                                keyword:      'SELECT'
[L:  3, P: 30]      |                                                [META] indent:
[L:  3, P: 30]      |                                                whitespace:   ' '
[L:  3, P: 31]      |                                                select_clause_element:
[L:  3, P: 31]      |                                                    column_reference:
[L:  3, P: 31]      |                                                        identifier:  'COLUMN2'
[L:  3, P: 38]      |                                            whitespace:       ' '
[L:  3, P: 39]      |                                            [META] dedent:
[L:  3, P: 39]      |                                            from_clause:
[L:  3, P: 39]      |                                                keyword:      'FROM'
[L:  3, P: 43]      |                                                whitespace:   ' '
[L:  3, P: 44]      |                                                from_expression:
[L:  3, P: 44]      |                                                    [META] indent:
[L:  3, P: 44]      |                                                    from_expression_element:
[L:  3, P: 44]      |                                                        table_expression:
[L:  3, P: 44]      |                                                            table_reference:
[L:  3, P: 44]      |                                                                identifier:  'MYTABLE3'
[L:  3, P: 52]      |                                                    [META] dedent:
[L:  3, P: 52]      |                                        [META] dedent:
[L:  3, P: 52]      |                                        end_bracket:          ')'
[L:  3, P: 53]      |                                newline:                      '\n'
[L:  4, P:  1]      |                                whitespace:                   '        '
[L:  4, P:  9]      |                                select_statement:
[L:  4, P:  9]      |                                    select_clause:
[L:  4, P:  9]      |                                        keyword:              'SELECT'
[L:  4, P: 15]      |                                        [META] indent:
[L:  4, P: 16]      |                                        select_clause_element:
[L:  4, P: 16]      |                                            column_reference:
[L:  4, P: 16]      |                                                identifier:   'COLUMN3'
[L:  4, P: 23]      |                                    whitespace:               ' '
[L:  4, P: 24]      |                                    [META] dedent:
[L:  4, P: 24]      |                                    from_clause:
[L:  4, P: 24]      |                                        keyword:              'FROM'
[L:  4, P: 28]      |                                        whitespace:           ' '
[L:  4, P: 29]      |                                        from_expression:
[L:  4, P: 29]      |                                            [META] indent:
[L:  4, P: 29]      |                                            from_expression_element:
[L:  4, P: 29]      |                                                table_expression:
[L:  4, P: 29]      |                                                    table_reference:
[L:  4, P: 29]      |                                                        identifier:  'MYTABLE3'
[L:  4, P: 37]      |                                            [META] dedent:
[L:  4, P: 37]      |                            newline:                          '\n'
[L:  5, P:  1]      |                            whitespace:                       '    '
[L:  5, P:  5]      |                            [META] dedent:
[L:  5, P:  5]      |                            end_bracket:                      ')'
[L:  5, P:  6]      |                    whitespace:                               ' '
[L:  5, P:  7]      |                    alias_expression:
[L:  5, P:  7]      |                        identifier:                           'X'
[L:  5, P:  8]      |            newline:                                          '\n'
[L:  6, P:  1]      |            where_clause:
[L:  6, P:  1]      |                keyword:                                      'WHERE'
[L:  6, P:  6]      |                [META] indent:
[L:  6, P:  6]      |                whitespace:                                   ' '
[L:  6, P:  7]      |                expression:
[L:  6, P:  7]      |                    column_reference:
[L:  6, P:  7]      |                        identifier:                           'COLUMN1'
[L:  6, P: 14]      |                    whitespace:                               ' '
[L:  6, P: 15]      |                    comparison_operator:
[L:  6, P: 15]      |                        raw_comparison_operator:              '='
[L:  6, P: 16]      |                    whitespace:                               ' '
[L:  6, P: 17]      |                    column_reference:
[L:  6, P: 17]      |                        identifier:                           'X'
[L:  6, P: 18]      |                        dot:                                  '.'
[L:  6, P: 19]      |                        identifier:                           'COLUMN3'
[L:  6, P: 26]      |                [META] dedent:
```

_Originally posted by @ahladkyi-spd in https://github.com/sqlfluff/sqlfluff/issues/2301#issuecomment-1012292979_

@barrywhart This issue started with #1991 , if you checkout to d5f14735784dc099ef6ce6529a9e6c58c4287c68, the query lints without throwing an exception. When you checkout to 54effa079fc2db108fe0e4673c63e64d5583253c you get the assertion exception.

**Comment by barrywhart** [comment]
Good detective work! I'll take a look.

**Comment by barrywhart** [comment]
@chwiese: I have a PR for this now: #2321.
