### ISSUE TITLE
Can't find dbt_packages file in dbt-core==1.0.0 upgrade

### ISSUE THREAD

**Issue by calliewhitee** [sqlfluff/sqlfluff#2408]
## Expected Behaviour
Provide results of linting compiled sql files

## Observed Behaviour
```
=== [dbt templater] Sorting Nodes...                                                                                           
=== [dbt templater] Compiling dbt project...                                                                                   
=== [dbt templater] Project Compiled.                                                                                          
file dates.sql:   0%|                                                                                  | 0/228 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/callie-mtla/.virtualenvs/test_sqlfluff/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/Users/callie-mtla/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/callie-mtla/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/callie-mtla/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/callie-mtla/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/callie-mtla/Library/Python/3.8/lib/python/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/callie-mtla/.virtualenvs/test_sqlfluff/lib/python3.8/site-packages/sqlfluff/cli/commands.py", line 480, in lint
    result = lnt.lint_paths(
  File "/Users/callie-mtla/.virtualenvs/test_sqlfluff/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 964, in lint_paths
    self.lint_path(
  File "/Users/callie-mtla/.virtualenvs/test_sqlfluff/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 916, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/Users/callie-mtla/.virtualenvs/test_sqlfluff/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/Users/callie-mtla/.virtualenvs/test_sqlfluff/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/Users/callie-mtla/.virtualenvs/test_sqlfluff/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 43, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/Users/callie-mtla/.virtualenvs/test_sqlfluff/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 642, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "/Users/callie-mtla/.virtualenvs/test_sqlfluff/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 619, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/Users/callie-mtla/.virtualenvs/test_sqlfluff/lib/python3.8/site-packages/sqlfluff_templater_dbt/templater.py", line 330, in process
    processed_result = self._unsafe_process(fname_absolute_path, in_str, config)
  File "/Users/callie-mtla/.virtualenvs/test_sqlfluff/lib/python3.8/site-packages/sqlfluff_templater_dbt/templater.py", line 447, in _unsafe_process
    node = self._find_node(fname, config)
  File "/Users/callie-mtla/.virtualenvs/test_sqlfluff/lib/python3.8/site-packages/sqlfluff_templater_dbt/templater.py", line 402, in _find_node
    raise RuntimeError(
RuntimeError: File /Users/callie-mtla/dev/analytics-engineering/dbt_packages/dbt_date/integration_tests/models/dates.sql was not found in dbt project
```

## Steps to Reproduce
pyenv local 3.8.9
mkvirtualenv -p /usr/bin/python3 test_sqlfluff
pip install dbt-core==1.0.0
pip install dbt-snowflake==1.0.0
pip install sqlfluff==0.9.0 (I tried 0.9.1 as well -- same output)
pip install sqlfluff-templater-dbt==0.9.0 (I tried 0.9.1 as well -- same output)
dbt deps (
  - package: calogica/dbt_expectations
    version: 0.5.1

  - package: dbt-labs/dbt_utils
    version: 0.8.0
)
sqlfluff lint

## Dialect
Snowflake/dbt

Just to note, I'm on a M1 Silicon Mac, but using virtual environments. This project was previously working and successfully running sqlfluff prior to upgrade to dbt 1.0.0. Other teammates on the same project don't seem to be hitting the same error, but I can't vouch for their set up. 

I also confirmed that the noted `/Users/callie-mtla/dev/analytics-engineering/dbt_packages/dbt_date/integration_tests/models/dates.sql` file does indeed exist at that location. 

## Version

python 3.8.9
dbt-core 1.0.0
dbt-snowflake 1.0.0
sqlfluff 0.9.0
sqlfluff-templater-dbt 0.9.0
dbt_utils 0.8.0
dbt_expectations 0.5.1

## Configuration
```
Include your SQLFluff configuration here
```
[sqlfluff]
verbose = 0
nocolor = False
dialect = snowflake
templater = dbt
rules = None
exclude_rules = L034, L044
recurse = 0
output_line_length = 120
runaway_limit = 10
ignore_templated_areas = True
encoding = autodetect
# Comma separated list of file extensions to lint.

# NB: This config will only apply in the root folder.
sql_file_exts = .sql,.sql.j2,.dml,.ddl

[sqlfluff:indentation]
indented_joins = False
template_blocks_indent = False

[sqlfluff:templater]
unwrap_wrapped_queries = True

[sqlfluff:templater:jinja]
apply_dbt_builtins = True

[sqlfluff:templater:jinja:macros]
# Macros provided as builtins for dbt projects
dbt_ref = {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
dbt_source = {% macro source(source_name, table) %}{{source_name}}_{{table}}{% endmacro %}
dbt_config = {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}
dbt_var = {% macro var(variable) %}item{% endmacro %}
dbt_is_incremental = {% macro is_incremental() %}True{% endmacro %}

# Some rules can be configured directly from the config common to other rules.
[sqlfluff:rules]
tab_space_size = 2
max_line_length = 120
indent_unit = space
comma_style = leading
allow_scalar = True
single_table_references = consistent
unquoted_identifiers_policy = all

# Some rules have their own specific config.
[sqlfluff:rules:L003]
lint_templated_tokens = False

[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = consistent

[sqlfluff:rules:L014]  # Unquoted identifiers
extended_capitalisation_policy = consistent

[sqlfluff:rules:L016]
ignore_comment_lines = False

[sqlfluff:rules:L029]  # Keyword identifiers
unquoted_identifiers_policy = aliases

[sqlfluff:rules:L030]  # Function names
capitalisation_policy = consistent

[sqlfluff:rules:L038]
select_clause_trailing_comma = forbid

[sqlfluff:rules:L040]  # Null & Boolean Literals
capitalisation_policy = consistent

[sqlfluff:rules:L042]
# By default, allow subqueries in from clauses, but not join clauses.
forbid_subquery_in = join

[sqlfluff:rules:L047]  # Consistent syntax to count all rows
prefer_count_1 = False

**Comment by calliewhitee** [comment]
I found a work-around by putting dbt_packages/ in .sqlfluffignore. Probably good practice anyway, but it should probably be automatically excluded.

**Comment by NiallRees** [comment]
I'm going to close this as I don't think this is an issue with SQLFluff - the dbt templater relies on selected sql files being model files. I'd recommend using `sqlfluff lint models`, assuming that your models directory is called `models`.
