### ISSUE TITLE
L044 throws exception when final statement has no SELECT

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#2467]
With this SQL:

```sql
WITH mycte AS (
    SELECT
        foo,
        bar
    FROM mytable1
)

UPDATE sometable
SET
    sometable.baz = mycte.bar
FROM
    mycte;
```

## Expected Behaviour

SQL Lints

## Observed Behaviour

```
% sqlfluff lint test.sql
CRITICAL   [L044] Applying rule L044 threw an Exception:                                                                                                         
Traceback (most recent call last):
  File "/Users/barry/sqlfluff/src/sqlfluff/core/rules/base.py", line 519, in crawl
    res = self._eval(
  File "/Users/barry/sqlfluff/src/sqlfluff/rules/L044.py", line 145, in _eval
    return self._analyze_result_columns(crawler.query_tree)
  File "/Users/barry/sqlfluff/src/sqlfluff/rules/L044.py", line 86, in _analyze_result_columns
    assert query.selectables
AssertionError
```

## Steps to Reproduce

As per above

## Dialect

All

## Version

0.9.2

## Configuration
Default

**Comment by tunetheweb** [comment]
Fixed in #2468
