### ISSUE TITLE
If statements in Jinja/dbt can trigger "list index out of range" error when used with whitespace controls

### ISSUE THREAD

**Issue by kdw2126** [sqlfluff/sqlfluff#2541]
## Expected Behaviour
Whenever valid Jinja or SQL code is run through ```sqlfluff lint```, it does not cause SQLFluff to crash.

## Observed Behaviour
When a Jinja/dbt SQL file is run with certain whitespace controls and if statements that have no text, SQLFluff exits with a "List index out of range error."

## Steps to Reproduce
(1). Save the following (nonsense but valid) jinja/dbt SQL file (EDIT:  @barrywhart's [example](https://github.com/sqlfluff/sqlfluff/issues/2541#issuecomment-1029494670) is better):
```sql
{% set metrics = ['A', 'B', 'C'] %}

{% for x in metrics %}
    {% if x == 'A' %}
    {% else %}
    SELECT 'E'
    {% endif %}
    {% if not loop.last and x != 'A' %}
    UNION ALL
    {% endif %}
{%- endfor %}

```
(2). Set BigQuery as the dialect and jinja as the templater and run sqlfluff lint on this file.

<details>
<summary><b>Stack Trace:</b></summary>

```
Traceback (most recent call last):
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/lib/python3.8/site-packages/sqlfluff/cli/commands.py", line 508, in lint
    result = lnt.lint_paths(
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 1032, in lint_paths
    self.lint_path(
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 984, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 43, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 710, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 681, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/lib/python3.8/site-packages/sqlfluff/core/templaters/jinja.py", line 365, in process
    raw_sliced, sliced_file, out_str = self.slice_file(
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/lib/python3.8/site-packages/sqlfluff/core/templaters/jinja.py", line 417, in slice_file
    trace = tracer.trace()
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/lib/python3.8/site-packages/sqlfluff/core/templaters/slicers/tracer.py", line 103, in trace
    self.move_to_slice(target_slice_idx, slice_length)
  File "/Users/kdw2126/.local/share/virtualenvs/real-markets-management-4VVaVdIV/lib/python3.8/site-packages/sqlfluff/core/templaters/slicers/tracer.py", line 161, in move_to_slice
    self.program_counter = candidates[0]
IndexError: list index out of range
```

</details>

Note that this SQL -- which only has one character changed in the last line -- is valid:
```sql
{% set metrics = ['A', 'B', 'C'] %}



{% for x in metrics %}
    {% if x == 'A' %}
    {% else %}
    SELECT 'E'
    {% endif %}
    {% if not loop.last and x != 'A' %}
    UNION ALL
    {% endif %}
{% endfor %}
```

## Dialect
BigQuery

## Version
SQLFluff version is 0.9.4.  Python version is 3.8.10.
I'm using dbt 1.0.1 but the same issue occurs when using jinja as a Templater.

## Configuration
```
[sqlfluff]
dialect = bigquery
templater = jinja
exclude_rules = L003,L008,L011,L014,L016,L029,L031,L034

[sqlfluff:rules]
max_line_length = 120
comma_style = leading

[sqlfluff:rules:L010]
capitalisation_policy = upper

[sqlfluff:rules:L030]
capitalisation_policy = upper
```

**Comment by tunetheweb** [comment]
Looks like it's the dash in the last line causing the issue.

Replacing:

```
{%- endfor %}
```

with:

```
{% endfor %}
```

Fixes the issues. These whitespace control characters have caused us issues in the past as they are complicated to get right. Looks like we need to have another look at this test case (FYI @barrywhart )

**Comment by barrywhart** [comment]
This simpler example produces the same exception.
```
{% for x in ['A', 'B'] %}
    {% if x != 'A' %}
    SELECT 'E'
    {% endif %}
{%- endfor %}
```
