### ISSUE TITLE
Existing reference to heuristic slicer breaks new installs

### ISSUE THREAD

**Issue by msnidal** [sqlfluff/sqlfluff#2575]
## Expected Behaviour
The sqlfluff command will run as expected

## Observed Behaviour
ModuleNotFoundError as below:
```
Traceback (most recent call last):
  File "/Users/marksnidal/.pyenv/versions/3.8.12/bin/sqlfluff", line 5, in <module>
    from sqlfluff.cli.commands import cli
  File "/Users/marksnidal/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sqlfluff/__init__.py", line 6, in <module>
    from sqlfluff.api import lint, fix, parse, list_rules, list_dialects
  File "/Users/marksnidal/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sqlfluff/api/__init__.py", line 4, in <module>
    from sqlfluff.api.simple import lint, fix, parse, APIParsingError
  File "/Users/marksnidal/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sqlfluff/api/simple.py", line 4, in <module>
    from sqlfluff.core import (
  File "/Users/marksnidal/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sqlfluff/core/__init__.py", line 9, in <module>
    from sqlfluff.core.linter import Linter
  File "/Users/marksnidal/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sqlfluff/core/linter/__init__.py", line 6, in <module>
    from sqlfluff.core.linter.linter import Linter
  File "/Users/marksnidal/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 32, in <module>
    from sqlfluff.core.rules import get_ruleset
  File "/Users/marksnidal/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sqlfluff/core/rules/__init__.py", line 12, in <module>
    for plugin_rules in get_plugin_manager().hook.get_rules():
  File "/Users/marksnidal/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sqlfluff/core/plugin/host.py", line 12, in get_plugin_manager
    pm.load_setuptools_entrypoints(project_name)
  File "/Users/marksnidal/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/Users/marksnidal/.pyenv/versions/3.8.12/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/marksnidal/.pyenv/versions/3.8.12/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/marksnidal/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sqlfluff_templater_dbt/__init__.py", line 3, in <module>
    from sqlfluff_templater_dbt.templater import DbtTemplater
  File "/Users/marksnidal/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sqlfluff_templater_dbt/templater.py", line 27, in <module>
    from sqlfluff.core.templaters.slicers.heuristic import slice_template
ModuleNotFoundError: No module named 'sqlfluff.core.templaters.slicers.heuristic'
```

## Steps to Reproduce
Install latest sqlfluff module from pypi, `0.9.4` in my case

## Dialect
I am using the Redshift dialect

## Version
Sqlfluff version `0.9.4` from pypi, I am using Python `3.8.12` in this environment.

## Configuration
Below are the contents of my `pyproject.toml` file, in case it's relevant:
```
[tool.sqlfluff.core]
templater = "jinja"

[tool.sqlfluff.templater.jinja]
apply_dbt_builtins = true
load_macros_from_path = "macros"

[tool.sqlfluff.indentation]
indented_joins = false
template_blocks_indent = true

[tool.sqlfluff.rules]
tab_space_size = 2
max_line_length = 120
indent_unit = "space"
comma_style = "trailing"
allow_scalar = true
single_table_references = "consistent"
unquoted_identifiers_policy = "all"
```

I am going to put up a pull request to try to fix this, there is also a reference to the heuristic slicer in a comment that I can remove.

**Comment by msnidal** [comment]
My apologies, the issue was from the dbt templater plugin getting out of sync with my install somehow. I was using the `sqlfluff[dbt]==0.9.4` syntax in my `requirements.txt` file which was somehow not getting updated properly - if anybody had the same problem, you can manually run `pip install sqlfluff_templater_dbt==0.9.4` to get the plugin in sync with the package (or replace the 0.9.4 with whatever version you're using)
