### ISSUE TITLE
Allow macros macros for templater Jinja

### ISSUE THREAD

**Issue by fbb-oc** [sqlfluff/sqlfluff#2636]
SQLFluf does not parse macro if the macro is present in macro.

For example: 
/models/my_model.sql
```
SELECT
    * -- for example
FROM my_table
```

/macros/get_list.sql
```
{% macro get_list() %}
    {% set query %}
        SELECT
            * -- for the example
        FROM {{ ref('my_model') }}
    {% endset %}
    {% set results = run_query(query) %}
    {% if execute %}
        {% set results_list = results.rows %}
    {% else %}
        {% set results_list = [] %}
    {% endif %}
    {{ return(results_list) }}
{% endmacro %}
```
In this condition, we have the following error message
```
sqlfluff lint models/my_model.sql
```
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/sqlfluff", line 33, in <module>
    sys.exit(load_entry_point('sqlfluff==0.10.0', 'console_scripts', 'sqlfluff')())
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/cli/commands.py", line 518, in lint
    result = lnt.lint_paths(
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/linter/linter.py", line 1035, in lint_paths
    self.lint_path(
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/linter/linter.py", line 987, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/linter/runner.py", line 43, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/linter/linter.py", line 710, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/linter/linter.py", line 681, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 319, in process
    env, live_context, make_template = self.template_builder(
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 276, in template_builder
    live_context = self.get_context(fname=fname, config=config, env=env)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 255, in get_context
    self._extract_macros_from_path(
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 90, in _extract_macros_from_path
    cls._extract_macros_from_path(
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 82, in _extract_macros_from_path
    cls._extract_macros_from_template(template, env=env, ctx=ctx)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 59, in _extract_macros_from_template
    for k in macro_template.module.__dict__:
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/jinja2/environment.py", line 1472, in module
    return self._get_default_module()
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/jinja2/environment.py", line 1440, in _get_default_module
    self._module = self.make_module()
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/jinja2/environment.py", line 1399, in make_module
    return TemplateModule(self, ctx)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/jinja2/environment.py", line 1529, in __init__
    body_stream = list(template.root_render_func(context))  # type: ignore
  File "<template>", line 14, in root
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'ref' is undefined
```
This error is generated because we check first our own macros here [sqlfluff/core/templaters/jinja.py](https://github.com/sqlfluff/sqlfluff/blob/4d526107c32946d87858cd766a99adfdbb056175/src/sqlfluff/core/templaters/jinja.py#L230)

If we update the code
```
            # Get macros from config - useful if we have macros in our macros
            # models -> macros -> macros
            macros_from_config = self._extract_macros_from_config(
                config=config, env=env, ctx=live_context
            )
            live_context.update(macros_from_config)

            # Get macros from libraries - useful if we have macros in our macros
            # models -> macros -> macros
            libraries_from_config = self._extract_libraries_from_config(config=config)
            live_context.update(libraries_from_config)

            macros_path = self._get_macros_path(config)
            if macros_path:
                live_context.update(
                    self._extract_macros_from_path(
                        macros_path, env=env, ctx=live_context
                    )
                )

            # Load config macros, these will take precedence over macros from the path
            live_context.update(macros_from_config)
            live_context.update(libraries_from_config)
```

**Comment by barrywhart** [comment]
@fbb-oc: Thanks for reporting the issue! I'm having trouble understanding parts of the information you've provided. Can you explain in more detail:
* What kind of SQL file and macro file cause the error to occur?
* What you think is wrong with the code?
* What you are proposing to change?

I don't understand what you mean by "does not parse macro if the macro is present in macro.". I also don't know what you changed in the proposed code you provided. Feel free to add more info here, or if you prefer,  you can create a PR with the proposed changes directly (plus appropriate automated tests). (PRs can help with communicating about code changes, because they automatically provide a "before and after" view of the affected code.)

**Comment by fbb-oc** [comment]
Hello @barrywhart 

Thanks for your time and your response.

To complete my issue, in case where we have a macro inside a macro as [ref](https://docs.getdbt.com/reference/dbt-jinja-functions/ref) : 
```
{% macro example() %}
    {% set query %}
        SELECT
            * -- for the example
        FROM {{ **ref**('my_model') }}
    {% endset %}
    -- ....
{% endmacro %}
```
**Ref** is a macro defined by **DBT** but when **SQLFluff** parse file and search macro, it begin to search macro who are available in macros directory (defined in SQLFluff configuration)

In this case an exception is generated (see the first post) because macro **ref** is not defined in this directory.

If we change macros loading order from:
1. macros defined in directory macros
2. macros defined in config
3. macros defined in builtin
By
1. macros defined in config
2. macros defined in builtin
3. macros defined in directory macros
4. macros defined in config
5. macros defined in builtin

We load in a first time macros defined by **DBT** or in the config and avoid the configuration if the macro **ref** is used inside an another macro.

I make a PR tomorrow with the change and a link with this issue ;)

**Comment by barrywhart** [comment]
@alanmcruickshank, @tunetheweb: Any concerns about the change proposed above? I don't use macros much, so I don't have a sense of whether changing the current order is likely to break things for other users.

**Comment by tunetheweb** [comment]
Fraid I don't know enough about this area to comment one way or another to be honest.

**Comment by fbb-oc** [comment]
Hello,

I would like to create a PR from a branch, but I dont have the permission to push my branch on this repo.
Any idea ?

**Comment by tunetheweb** [comment]
You should fork the repo first and then open a PR to this repo.
https://github.com/sqlfluff/sqlfluff/wiki/Git-Guide#recommended-way-to-use-git-for-sqlfluff
