### ISSUE TITLE
Critical Bug - Python Exception During SQLFluff fix

### ISSUE THREAD

**Issue by WittierDinosaur** [sqlfluff/sqlfluff#2812]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Attempting to `sqlfluff fix` a file causes a python exception, and a warning that shouldn't fire. Verified this does not fire in 0.10.1

### Expected Behaviour

File is successfully fixed

### Observed Behaviour

```
 sqlfluff fix test.sql
==== finding fixable violations ====
WARNING    After fixes were applied, segment <SelectStatementSegment: ([L:  4, P:  3])> failed the match() parser check. Result: MatchResult(matched_segments=(), unmatched_segments=(<SelectClauseSegment: ([L:  4, P:  3])>, <NewlineSegment: ([L:  5, P:  8]) '\n'>, <FromClauseSegment: ([L:  6, P:  3])>)) Fixes: [<LintFix: delete @[L:  6, P:  1] delete:'  '>] 
CRITICAL   [L036] Applying rule L036 threw an Exception: tuple index out of range                                                                                                                                       
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/rules/base.py", line 535, in crawl
    res = self._eval(context=context)
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/rules/L036.py", line 75, in _eval
    return self._eval_single_select_target_element(
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/rules/L036.py", line 326, in _eval_single_select_target_element
    to_delete[-1],
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/rules/functional/segments.py", line 140, in __getitem__
    result = super().__getitem__(item)
IndexError: tuple index out of range
WARNING    After fixes were applied, segment <SelectStatementSegment: ([L:  4, P:  3])> failed the match() parser check. Result: MatchResult(matched_segments=(), unmatched_segments=(<SelectClauseSegment: ([L:  4, P:  3])>, <NewlineSegment: ([L:  5, P:  8]) '\n'>, <FromClauseSegment: ([L:  6, P:  3])>)) Fixes: [<LintFix: create_after @[L:  4, P:  3] create:'\n'>, <LintFix: delete @[L:  5, P:  8] delete:'\n'>] 
== [test.sql] FAIL                                                                                                                                                                                                      
L:   2 | P:   5 | L003 | Line over-indented compared to line #1
L:   4 | P:   3 | L003 | Indentation not consistent with line #3
L:   5 | P:   5 | L003 | Line over-indented compared to line #3
L:   6 | P:   3 | L003 | Indentation not consistent with line #3
==== fixing violations ====
4 fixable linting violations found

```

### How to reproduce

sqlfluff fix this with the below config:
```
INSERT INTO foo (
    bar
)
  SELECT
    foo
  FROM bar
;

```

### Dialect

Snowflake

### Version

0.11.0

### Configuration
```
[sqlfluff]
# https://docs.sqlfluff.com/en/stable/configuration.html#default-configuration
verbose = 0
nocolor = False
dialect = snowflake
templater = jinja
rules = None
exclude_rules = L011,L016,L031,L034,L035
recurse = 0
output_line_length = 120
runaway_limit = 10
ignore = None
ignore_templated_areas = True
encoding = autodetect
disable_noqa = False
sql_file_exts = .sql,.sql.j2,.dml
fix_even_unparsable = False

[sqlfluff:indentation]
indented_joins = False
indented_ctes = False
indented_using_on = True
template_blocks_indent = True

[sqlfluff:templater]
unwrap_wrapped_queries = True

[sqlfluff:templater:jinja]
apply_dbt_builtins = True

[sqlfluff:templater:jinja:macros]
# Macros provided as builtins for dbt projects
dbt_ref = {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
dbt_source = {% macro source(source_name, table) %}{{source_name}}_{{table}}{% endmacro %}
dbt_config = {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}
dbt_var = {% macro var(variable, default='') %}item{% endmacro %}
dbt_is_incremental = {% macro is_incremental() %}True{% endmacro %}

# Some rules can be configured directly from the config common to other rules.
[sqlfluff:rules]
tab_space_size = 2
max_line_length = 120
indent_unit = space
comma_style = leading
allow_scalar = True
single_table_references = consistent
unquoted_identifiers_policy = all

# Some rules have their own specific config.
# https://docs.sqlfluff.com/en/stable/rules.html
[sqlfluff:rules:L003]
lint_templated_tokens = True

[sqlfluff:rules:L007]  # Keywords
operator_new_lines = after

[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = upper

[sqlfluff:rules:L011]  # Table aliasing
aliasing = implicit

[sqlfluff:rules:L012]  # Column aliasing
aliasing = explicit

[sqlfluff:rules:L013]  # Column expressions
allow_scalar = False

[sqlfluff:rules:L014]  # Unquoted identifiers
extended_capitalisation_policy = lower

[sqlfluff:rules:L016]
ignore_comment_lines = False

[sqlfluff:rules:L029]  # Keyword identifiers
unquoted_identifiers_policy = aliases

[sqlfluff:rules:L030]  # Function names
extended_capitalisation_policy = lower

[sqlfluff:rules:L038]
select_clause_trailing_comma = forbid

[sqlfluff:rules:L040]  # Null & Boolean Literals
capitalisation_policy = consistent

[sqlfluff:rules:L042]
# By default, allow subqueries in FROM clauses, but not JOIN clauses.
forbid_subquery_in = join

[sqlfluff:rules:L047]  # Consistent syntax to count all rows
prefer_count_1 = False
prefer_count_0 = False

[sqlfluff:rules:L052]  # Statements must end with a semi-colon
multiline_newline = True
require_final_semicolon = True
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by WittierDinosaur** [comment]
This config is all that is necessary to cause the python exception:

```
[sqlfluff:rules]
tab_space_size = 2
```

**Comment by tunetheweb** [comment]
Looks like this was fixed in #2813 

You happy to close this now @WittierDinosaur ?

**Comment by WittierDinosaur** [comment]
@tunetheweb can we bind this to your open PR - it fails on main, but not your branch

**Comment by tunetheweb** [comment]
Excellent. I'l be merging this as soon as Coverage stops being so mean issuing it's reports!

**Comment by tunetheweb** [comment]
Oh and like that it just came back! Merged.
