### ISSUE TITLE
Multiple Newlines at the end of a model cause assertion errors

### ISSUE THREAD

**Issue by dannyshaw** [sqlfluff/sqlfluff#2880]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I was receiving the following error in running `sqlfluff lint` in a project configured with the dbt templating.

```shell
Traceback (most recent call last):
  File "/home/danny/.virtualenvs/dbt/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/home/danny/.virtualenvs/dbt/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/danny/.virtualenvs/dbt/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/danny/.virtualenvs/dbt/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/danny/.virtualenvs/dbt/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/danny/.virtualenvs/dbt/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/danny/.virtualenvs/dbt/lib/python3.8/site-packages/sqlfluff/cli/commands.py", line 533, in lint
    result = lnt.lint_paths(
  File "/home/danny/.virtualenvs/dbt/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 1087, in lint_paths
    self.lint_path(
  File "/home/danny/.virtualenvs/dbt/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 1039, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/home/danny/.virtualenvs/dbt/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/home/danny/.virtualenvs/dbt/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/home/danny/.virtualenvs/dbt/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 43, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/home/danny/.virtualenvs/dbt/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 760, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "/home/danny/.virtualenvs/dbt/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 731, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/home/danny/.virtualenvs/dbt/lib/python3.8/site-packages/sqlfluff_templater_dbt/templater.py", line 323, in process
    processed_result = self._unsafe_process(fname_absolute_path, in_str, config)
  File "/home/danny/.virtualenvs/dbt/lib/python3.8/site-packages/sqlfluff_templater_dbt/templater.py", line 541, in _unsafe_process
    TemplatedFile(
  File "/home/danny/.virtualenvs/dbt/lib/python3.8/site-packages/sqlfluff/core/templaters/base.py", line 127, in __init__
    assert (tfs.templated_slice.start ==
AssertionError
```

I discovered this was due to extra newlines in the model at the end.

### Expected Behaviour

Either a successful output, or the newlines themselves are reported as a linting error.

### Observed Behaviour

I did some debugging and noticed there was a single character difference between the values being asserted in `core/templaters/base.py:L127`, and it was always the last slice being assessed. 

```python
assert (tfs.templated_slice.start == previous_slice.templated_slice.stop)
```

This led me to believe it was related to newlines, and I've discovered that if there's more than a single newline at the end, then this error occurs. 

I removed all the newlines in affected files and the issue dissapeared.

### How to reproduce

after the final select statement in a model insert two newlines

### Dialect

postgres, with dbt templater

### Version

0.11.1

### Configuration

.sqlfluff:
```
[sqlfluff]
dialect = postgres
templater = dbt

[sqlfluff:rules]
tab_space_size = 2

[sqlfluff:templater:dbt]
target = prod
```

.sqlfluffignore:
```
target/
dbt_modules/
dbt_packages/
macros/
scripts/
```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by marianore-waisdata** [comment]
Getting similar error in version 0.11.1 (DBT Bigquery). Same models and command in ~0.10.1 works fine.

**Comment by barrywhart** [comment]
Reproduced with this SQL file:
```
{{ config(materialized='view') }}

with cte_example as (
     select 1 as col_name
),

final as
(
    select
        col_name,
        {{ testmacro('col_blahblahblahblahblahname') }} as col_name2
    from
        cte_example
)

select * from final



```

**Comment by troyschuetrumpf-elation** [comment]
Hi @barrywhart, 
I noticed in our project as of 0.11.2 we are still blowing up with a AssertionError if there is a single or multiple newline at the end of a model file. 

`➜  dbt git:(update-sqlfluff-to-11.2) ✗ sqlfluff lint models/stage/test.sql
=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
Traceback (most recent call last):
  File "/usr/local/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 533, in lint
    result = lnt.lint_paths(
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 1087, in lint_paths
    self.lint_path(
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 1039, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 43, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 760, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 731, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/usr/local/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 323, in process
    processed_result = self._unsafe_process(fname_absolute_path, in_str, config)
  File "/usr/local/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 537, in _unsafe_process
    TemplatedFile(
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/templaters/base.py", line 129, in __init__
    assert (
AssertionError
➜  dbt git:(update-sqlfluff-to-11.2) ✗ sqlfluff --version
sqlfluff, version 0.11.2
➜  dbt git:(update-sqlfluff-to-11.2) ✗`


`{{ "" }}

select 1
`

We are excluding the following rules (in case that is partially the cause
`exclude_rules = L002, L004, L008, L009, L010, L014, L016, L019, L022, L027, L029, L031, L033`

**Comment by troyschuetrumpf-elation** [comment]
Tested with a minimal .sqlfluff config
```
[sqlfluff]
templater = dbt
dialect = redshift
```
and 
```
[sqlfluff]
templater = dbt
```

Same result

**Comment by barrywhart** [comment]
@troyschuetrumpf-elation: I'm not seeing this error in my local installation of SQLFluff. Please:
* Open a new issue
* Attach your test sql file, in case there is something specific 
* Confirm you are running SQLFluff 0.11.2 (upgrading the dbt templater alone will not help, because the bug fix is in **core** SQLFluff)
* If possible, try and reproduce this issue using the jinja templater (it's easier for the SQLFluff maintainers to work with than dbt, and it uses the same code for the failure you're seeing)
