### ISSUE TITLE
RuntimeError: File X was not found in dbt project

### ISSUE THREAD

**Issue by RoyalTS** [sqlfluff/sqlfluff#2906]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

As a follow-up to #597, I have a repo with the following directory structure:

```
.
├── db
│   ├── dbt
│       └── models
└── issues
    └── experiment
        └── sql
```

where `dbt` is a dbt project and `models` contains a bunch of jinja'ed SQL statements. `issues/experiment/sql` also contains SQL statements, without any jinja templating.

My pyproject.toml looks like this:

```
[tool.sqlfluff.core]
dialect = "snowflake"
templater = "dbt"
sql_file_exts = ".sql"

[tool.sqlfluff.templater.dbt]
project_dir = "./db/dbt"
```

When I now run sqlfluff as part of my pre-commit hooks I get

```
- hook id: sqlfluff-lint
- exit code: 1

=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
Traceback (most recent call last):
  File "/Users/rooyalts/.cache/pre-commit/repo92f6m640/py_env-python3.9/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/Users/rooyalts/.cache/pre-commit/repo92f6m640/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rooyalts/.cache/pre-commit/repo92f6m640/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/rooyalts/.cache/pre-commit/repo92f6m640/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rooyalts/.cache/pre-commit/repo92f6m640/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rooyalts/.cache/pre-commit/repo92f6m640/py_env-python3.9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/rooyalts/.cache/pre-commit/repo92f6m640/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 533, in lint
    result = lnt.lint_paths(
  File "/Users/rooyalts/.cache/pre-commit/repo92f6m640/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 1087, in lint_paths
    self.lint_path(
  File "/Users/rooyalts/.cache/pre-commit/repo92f6m640/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 1039, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/Users/rooyalts/.cache/pre-commit/repo92f6m640/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/Users/rooyalts/.cache/pre-commit/repo92f6m640/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/Users/rooyalts/.cache/pre-commit/repo92f6m640/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 43, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/Users/rooyalts/.cache/pre-commit/repo92f6m640/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 760, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "/Users/rooyalts/.cache/pre-commit/repo92f6m640/py_env-python3.9/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 731, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/Users/rooyalts/.cache/pre-commit/repo92f6m640/py_env-python3.9/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 323, in process
    processed_result = self._unsafe_process(fname_absolute_path, in_str, config)
  File "/Users/rooyalts/.cache/pre-commit/repo92f6m640/py_env-python3.9/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 443, in _unsafe_process
    node = self._find_node(fname, config)
  File "/Users/rooyalts/.cache/pre-commit/repo92f6m640/py_env-python3.9/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 398, in _find_node
    raise RuntimeError(
RuntimeError: File /Users/rooyalts/repos/myrepo/issues/experiment/sql/analysis_dataset.sql was not found in dbt project
```

Which: fair enough. I thought I would be able to solve this by putting an `.sqlfluff` file with the following contents in the `issues` directory:

```
[sqlfluff]
templater = "jinja"
```

Alas, same error message.

### Expected Behaviour

The SQL files in the `dbt` directory should use the `dbt` template, the files in the `issues` directory should use the jinja templater

### Observed Behaviour

RuntimeError

### How to reproduce

See above

### Dialect

Snowflake

### Version

0.11.1

### Configuration

See above

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
SQLFluff doesn't support overriding the templater for a subdirectory. Could you set up independent SQLFluff configurations for the two directories? If I understand correctly, they are adjacent; it's not that one is a subdirectory of the other.

**Comment by barrywhart** [comment]
(In other words, move the dbt SQLFluff configuration to the `db/` or `db/dbt/` subdirectories.)

**Comment by RoyalTS** [comment]
That gets me some but not all of the way there: `Attempt to set templater to dbt failed. Using jinja templater. Templater cannot be set in a .sqlfluff file in a subdirectory of the current working directory. It can be set in a .sqlfluff in the current working directory. See Nesting section of the docs for more details.`

**Comment by tunetheweb** [comment]
Sounds like you have a top level .sqlfluff files and are overriding it further down the three.

You need one `.sqlfluff` file (with dbt templater) in dbt directory.
And another `.sqlfluff` file (with jinja  templater) in issues directory.
And no `.sqlfluff` in the top level directory containing both of these directories.

**Comment by RoyalTS** [comment]
That's what I've got!

```sh
> find . -type f -name '.sqlfluff' | sed -r 's|/[^/]+$||' |sort |uniq
./db/dbt
./issues
```

**Comment by RoyalTS** [comment]
Hmm... when I call `sqlfluff fix . from `./db` I get the above errors. When I call it from `./db/dbt` everything runs through smoothly.

And no, `pyproject.toml` is clean and I don't use any other config files.

**Comment by tunetheweb** [comment]
Guessing it loads the default config (including Jinja templator) when it can't find one when rub from `./db`.

Any reason it needs to be in `./db/dbt` and couldn't be in `./db`?

**Comment by RoyalTS** [comment]
The `.sqlfluff` file? Yeah, there's another subdirectory of `db` that isn't dbt.

**Comment by RoyalTS** [comment]
Now it's getting tricky! :D

I'm actually using `sqlfluff` as a pre-commit hook. So I need to have a hook that has `./db/dbt` as its working directory (how do I do that???) and a hook for `./issues`?

**Comment by tunetheweb** [comment]
Don't know precommit too well to be honest, but yeah I'd say two hooks with `exclude` params for each to ignore the directories it shouldn't look at. Can't see how to override start path, but could just use `args` to see the `--templater` argument appropriately in each hook?

BTW if you figure this out we'd LOVE a PR to the [config](https://github.com/sqlfluff/sqlfluff/blob/main/docs/source/configuration.rst) and/or [precommit docs](https://github.com/sqlfluff/sqlfluff/blob/main/docs/source/production.rst) to explain how to do this!

**Comment by RoyalTS** [comment]
This seems to do the job:

```
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 0.11.2
  hooks:
    - id: sqlfluff-lint
      name: sqlfluff-lint-dbt
      files: ^db/dbt
      args: [--config=db/dbt/.sqlfluff]
      additional_dependencies: ['dbt-snowflake', 'sqlfluff-templater-dbt']
    - id: sqlfluff-fix
      name: sqlfluff-fix-dbt
      files: ^db/dbt
      args: [--config=db/dbt/.sqlfluff]
      additional_dependencies: ['dbt-snowflake', 'sqlfluff-templater-dbt']
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 0.11.2
  hooks:
    - id: sqlfluff-lint
      name: sqlfluff-lint-other
      exclude: ^db/dbt/
    - id: sqlfluff-fix
      name: sqlfluff-fix-other
      exclude: ^db/dbt/
```
