### ISSUE TITLE
Newlines at the end of a model cause assertion errors with dbt templater

### ISSUE THREAD

**Issue by troyschuetrumpf-elation** [sqlfluff/sqlfluff#2941]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

This issue is similar to https://github.com/sqlfluff/sqlfluff/issues/2880. When running `sqlfluff lint` with sqlfluff 0.11.2 and the dbt templater 

```
sqlfluff lint models/stage/test.sql
=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
Traceback (most recent call last):
  File "/usr/local/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 533, in lint
    result = lnt.lint_paths(
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 1087, in lint_paths
    self.lint_path(
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 1039, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 43, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 760, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 731, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/usr/local/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 323, in process
    processed_result = self._unsafe_process(fname_absolute_path, in_str, config)
  File "/usr/local/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 537, in _unsafe_process
    TemplatedFile(
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/templaters/base.py", line 129, in __init__
    assert (
AssertionError

sqlfluff --version
sqlfluff, version 0.11.2
```

In this case I used a bare minimum model and .sqlfluff
test.sql (one or multiple new line at the end of the file)
```
{{ "" }}

SELECT 1

```
.sqlfluff
```
[sqlfluff]
templater = dbt
dialect = redshift
```

Notes for testing:

1. I used a minimal dbt project with a connection to a redshift database. The only model was the above test.sql, no macros, no tests etc. 
2. If you use the jinja templater this issue does not occur. 

### Expected Behaviour

No AssertionError on linting

### Observed Behaviour

AssertionError when running `sqlfluff lint`

### How to reproduce

1. Create a dbt project that has a connection to a redshift database (possibly others)
2. Create a test model such as the one above
3. Set up .sqlfluff as per above
4. Run `sqlfluff lint`

### Dialect

Redshift

### Version

0.11.2

### Configuration

[sqlfluff]
templater = dbt
dialect = redshift

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by troyschuetrumpf-elation** [comment]
Hi @barrywhart, this is the bug log based on https://github.com/sqlfluff/sqlfluff/issues/2880

**Comment by troyschuetrumpf-elation** [comment]
I have a solution, I upgraded `sqlfluff` to 0.11.2 but `sqlfluff-templater-dbt` was still at 0.11.0. Updating to 0.11.2 for `sqlfluff-templater-dbt` as well resolves this issue.
