### ISSUE TITLE
AssertionError in dbt templater when file ends with `-%}`

### ISSUE THREAD

**Issue by brunocostalopes** [sqlfluff/sqlfluff#2964]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When using SQLFluff with dbt templater, I've received an AssertionError when running `sqlfluff lint` against one of my models. Full stack is below

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/diff-quality", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/diff_cover/diff_quality_tool.py", line 348, in main
    percent_passing = generate_quality_report(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/diff_cover/diff_quality_tool.py", line 279, in generate_quality_report
    reporter.generate_report(output_file)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/diff_cover/report_generator.py", line 2[65](https://github.com/company/dbt/runs/5786623765?check_suite_focus=true#step:7:65), in generate_report
    report = template.render(self._context())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/diff_cover/report_generator.py", line 314, in _context
    context = super().report_dict()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/diff_cover/report_generator.py", line 187, in report_dict
    src_stats = {src: self._src_path_stats(src) for src in self.src_paths()}
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/diff_cover/report_generator.py", line 84, in src_paths
    for src, summary in self._diff_violations().items()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/diff_cover/report_generator.py", line 176, in _diff_violations
    self._diff_violations_dict = {
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/diff_cover/report_generator.py", line 178, in <dictcomp>
    self._violations.violations(src_path),
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sqlfluff/diff_quality_plugin.py", line 27, in violations
    linted_path = linter.lint_path(src_path, ignore_non_existent_files=True)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 1039, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 43, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 760, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line [73](https://github.com/company/dbt/runs/5786623765?check_suite_focus=true#step:7:73)1, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sqlfluff_templater_dbt/templater.py", line 320, in process
    processed_result = self._unsafe_process(fname_absolute_path, in_str, config)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sqlfluff_templater_dbt/templater.py", line 536, in _unsafe_process
    TemplatedFile(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sqlfluff/core/templaters/base.py", line 136, in __init__
    assert tfs.templated_slice.stop == len(templated_str)
AssertionError
```

### Expected Behaviour

The contents of the file shouldn't cause SQLFluff to crash

### Observed Behaviour

When using dbt, if a model ends with `-%}`, then all of the whitespace and newlines are removed in the compiled SQL and `sqlfluff lint` fails with an AssertionError error.

### How to reproduce

We realised that this is caused by some dbt models ending with `-%}`. This causes all of the whitespace and newlines to be  removed in the compiled SQL so it's possibly related to #2887 

Issue can be reproduced with the `minimial.sql` file below and running

```
sqlfluff lint minimal.sql
```

minimal.sql:
```
select 1
{% if target.database == 'test' -%}
  union all
  select 2
{%- endif -%}

```

**Fix**
Replacing the `-%}` at the end with `%}` will make SQLFluff work as expected:

```
select 1
{% if target.database == 'test' -%}
  union all
  select 2
{%- endif %}

```

### Dialect

snowflake

### Version

0.11.2

### Configuration

.sqlfluff:
```
[sqlfluff]
templater = dbt
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
Good catch! It's in the same area of the code as the earlier PR, but this is actually a separate bug. We recently added the assertions which are catching these bugs. In the past, the behavior was wrong, but wasn't necessarily breaking anything in an obvious way.

**Comment by brunocostalopes** [comment]
Thanks for sorting this out so quickly!

**Comment by barrywhart** [comment]
No problem! Hoping for zero bugs in this area of the code soon. 🤞

**Comment by kd2718** [comment]
We were having a similar issue, but the `-%}` was inside a macro. Will this fix also work in that case?

**Comment by barrywhart** [comment]
@kd2718: It might, if the failure happened when using the macro at the end of a file.

**Comment by kd2718** [comment]
@barrywhart Our macro is not at the end of the file, it's in the middle :( . Would you be OK if we setup a flag to disable this check? If so where in the code should that be placed?

**Comment by barrywhart** [comment]
This check should not be disabled. Please create a new GitHub issue with a test case so we can reproduce and fix it.
