### ISSUE TITLE
Jinja templater: Using an unknown Jinja tag fails with runtime error & stack trace

### ISSUE THREAD

**Issue by b-per** [sqlfluff/sqlfluff#3199]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I have seen this error on my dbt project when using SQLFluff with the Jinja template.

I have a dbt [custom generic test](https://docs.getdbt.com/docs/guides/writing-custom-generic-tests#generic-tests-with-standard-arguments) defined in my macros folder.

When using `load_macros_from_path = macros`, every call to `sqlfluff` returns the following error:
```
Traceback (most recent call last):
  File "<my_venv_path>bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "<my_venv_path>lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "<my_venv_path>lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "<my_venv_path>lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "<my_venv_path>lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "<my_venv_path>lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "<my_venv_path>lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 517, in lint
    result = lnt.lint_paths(
  File "<my_venv_path>lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 1143, in lint_paths
    self.lint_path(
  File "<my_venv_path>lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 1095, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "<my_venv_path>lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "<my_venv_path>lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "<my_venv_path>lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 43, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "<my_venv_path>lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 816, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "<my_venv_path>lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 787, in render_string
    templated_file, templater_violations = self.templater.process(
  File "<my_venv_path>lib/python3.9/site-packages/sqlfluff/core/templaters/jinja.py", line 327, in process
    env, live_context, make_template = self.template_builder(
  File "<my_venv_path>lib/python3.9/site-packages/sqlfluff/core/templaters/jinja.py", line 284, in template_builder
    live_context = self.get_context(fname=fname, config=config, env=env)
  File "<my_venv_path>lib/python3.9/site-packages/sqlfluff/core/templaters/jinja.py", line 263, in get_context
    self._extract_macros_from_path(
  File "<my_venv_path>lib/python3.9/site-packages/sqlfluff/core/templaters/jinja.py", line 92, in _extract_macros_from_path
    cls._extract_macros_from_path(
  File "<my_venv_path>lib/python3.9/site-packages/sqlfluff/core/templaters/jinja.py", line 84, in _extract_macros_from_path
    cls._extract_macros_from_template(template, env=env, ctx=ctx)
  File "<my_venv_path>lib/python3.9/site-packages/sqlfluff/core/templaters/jinja.py", line 58, in _extract_macros_from_template
    macro_template = env.from_string(template, globals=ctx)
  File "<my_venv_path>lib/python3.9/site-packages/jinja2/environment.py", line 942, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "<my_venv_path>lib/python3.9/site-packages/jinja2/environment.py", line 639, in compile
    self.handle_exception(source=source_hint)
  File "<my_venv_path>lib/python3.9/site-packages/jinja2/environment.py", line 833, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "<my_venv_path>lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 7, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'test'
```

Modifying the following lines
https://github.com/sqlfluff/sqlfluff/blob/656a958146e9d415a39e77da7a063cd304fd56d3/src/sqlfluff/core/templaters/jinja.py#L56-L57
to add 
```
context = {}
        if '{% test ' in template:
            return context
macro_template = env.from_string(template, globals=ctx) 
```
works but it looks very hacky and might not work if a file contains both `macro` and `test` elements.

### Expected Behaviour

sqlfluff should run without error or triggering any exception

### Observed Behaviour

the error message pasted above is raised

### How to reproduce

- create a dbt custom generic test and save it in the macros folder
- setup SQLFluff with the Jinja templater
- add the following to `.sqlfluff`
```
[sqlfluff:templater:jinja]
load_macros_from_path = macros
```

### Dialect

N/A

### Version

sqlfluff, version `0.13.0`
dbt version `1.0.3`

### Configuration

.sqlfluff
```
[sqlfluff]
verbose = 0
nocolor = False
dialect = snowflake
templater = jinja
rules = None

recurse = 0
output_line_length = 80
runaway_limit = 10
ignore_templated_areas = True

sql_file_exts = .sql,.sql.j2,.dml,.ddl

[sqlfluff:templater:jinja]
load_macros_from_path = macros
...
```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
I think `{% test ...` must be a dbt-specific feature, and you're using the jinja templater. This is not a bug, but possibly an enhancement request.

Have you tried using the dbt templater instead?

Also, please provide a complete example, rather than just saying "dbt custom generic test". The maintainers are unpaid volunteers, and issues with incomplete or vague instructions to reproduce are considered low priority.

**Comment by b-per** [comment]
Hi!

Yes, I have used the dbt templater, and it works fine 👍  . I was just trying to use the Jinja one as well as it is faster to run, so currently the feedback loop is better when using it in VS Code for example.

This is an example of custom generic test in dbt:
```
{% test is_even(model, column_name) %}

with validation as (

    select
        {{ column_name }} as even_field

    from {{ model }}

),

validation_errors as (

    select
        even_field

    from validation
    -- if this is true, then even_field is actually odd!
    where (even_field % 2) = 1

)

select *
from validation_errors

{% endtest %}
```
and this piece of Jinja code is saved in a SQL file, either under the `macros` folder (when I get this error), or under `tests/generic`.

To reproduce the error I got, a person would just need to use the config `load_macros_from_path = macros` and save the snippet of code from above in a SQL file under the folder `macros`.


An easy workaround today is for people to move those dbt tests from `macros` to `tests/generic` but I was just wondering if there was a way to exclude those files by default, and I am happy to contribute if there is a specific way forward to do it.

**Comment by barrywhart** [comment]
To make sure I understand, you're not trying to _lint_ files that depend on dbt tests, you simply want it to ignore those files. Is there a way to know which files contain tests based on the file or directory name, or does it require looking at the file _contents_?

If the former is true, have you tried `.sqlfluffignore`?

**Comment by b-per** [comment]
No, I am not trying to _lint_ those `test` macros, I just want to avoid `sqlfluff` raising an exception when some of those tests have been defined. It was most likely not clear in my original message but I got the error when running `sqlfluff` on a file that has nothing to do with the `test`.

The current implementation of dbt generic tests doesn't dictate any rule about the file name. So, the workaround is relatively easy in a sense that those tests could be moved to `tests/generic` or added in some way to `.sqlfluffignore` but a user who would be getting this exception might not know what to do to fix it.

**Comment by barrywhart** [comment]
I think the error message is clear enough. The jinja templater supports jinja, along with very small bits of dbt. But mostly, the jinja templater supports jinja. Expecting it to nicely detect and fail on use of dbt-specific extensions seems like too much.

**Comment by barrywhart** [comment]
I talked with another maintainer. We'll address this by catching the exception and reporting this as a templating error. So it won't be a dbt-specific fix, just better overall error handling in the jinja templater.

**Comment by barrywhart** [comment]
I have a PR (#3239) which fixes the stack trace and reports a hopefully helpful error message, without building any dbt-specific knowledge into the Jinja templater:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/1678585/166159498-db909131-61f3-4d51-beb0-45885ea2d4d8.png">
