### ISSUE TITLE
ignore_words_regex results in error

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#3226]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I'm trying to use the new `ignore_words_regex` in rule L014. The regex is similar to `^(SchemaA.*)$` (so I want it to ignore all tables in a certain schema.

### Expected Behaviour

Everything is follows the naming policy, but identifiers starting with `SchemaA` are not changed.

### Observed Behaviour

```
CRITICAL   [L014] Applying rule L014 threw an Exception: string index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/rules/base.py", line 634, in crawl
    res = self._eval(context=context)
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/rules/L014.py", line 87, in _eval
    return super()._eval(context=context)
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/rules/L010.py", line 120, in _eval
    if context.segment.raw[0] != context.segment.raw[0].upper():
IndexError: string index out of range
```

Additionally, identifiers starting with `SchemaA` are changed.

### How to reproduce

see above

### Dialect

T-SQL

### Version

Latest `main`

### Configuration

[sqlfluff]
dialect = tsql

[sqlfluff:rules:L014] # Unquoted identifiers
extended_capitalisation_policy = pascal
ignore_words_regex = "^(Landing.*)$"

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Those are sentences not words 😁

Each identifier is handled as a unique token (do a `sqlfluff parse` to see the parts) and the rule applies at each token - not the overall identifier.

**Comment by fdw** [comment]
Ah, I see. Thank you!

There's probably no way to leave the `data_type_identifier` if the `identifier` is something, right?

**Comment by tunetheweb** [comment]
> There's probably no way to leave the data_type_identifier if the identifier is something, right?

Sorry don't get what you mean?

**Comment by fdw** [comment]
Sorry!

My problem is that I have types in a certain schema which are named inconsistently with lower or upper or pascal case. I thought the best solution was to still enable L014, but ignore everything in this schema. However, that can only work if I can match only on the schema part.

For an example, let's say I have a schema `Weird`. In `Weird`, types and tables don't follow rules.
Is there a way I can ignore all of them in L014?

**Comment by tunetheweb** [comment]
Only way to do that at present would be to inline ignore.

```sql
SELECT *
FROM
  normal.table1
INNER JOIN
  Weird.Table2 -- noqa: L014
WHERE
....etc.
```

Or enhance the rule further to look at the schema.

**Comment by fdw** [comment]
So, I thought about extending the rule. Would it work if I also target `ObjectReferenceSegment` and check all of its components for `ignore_words` and `ignore_words_regex`?
If so, could you please also give me a hint how I can access the components of a segment?

**Comment by tunetheweb** [comment]
Because you want to ignore the word, if it's preceded by the ignore words.

So probably what you want is to check the parent with this:

```py
parent: Optional[BaseSegment] = (
            context.parent_stack[-1] if context.parent_stack else None
        )
```

Check if it's a `ObjectReferenceSegment`, then check it's first child identifier:

```py
get_child("identifier")
```

And if that matches `ignore` or `ignore_regex`, then you can skip this word.

Also might want to put this behind a flag (`check_schema_for_ignores = False`?)

**Comment by tunetheweb** [comment]
I'm also curious as to how you got the exception. Would like to solve that too but can't recreate it.

**Comment by fdw** [comment]
I'd like to help you with the exception, but I'm not sure exactly what you need. But I can try to reproduce the error. Which output would be helpful?

Also, while implementing the solution you proposed, I noticed that TSQL's `DatatypeSegment` would theoretically be supported, but as the `DatatypeSegment` is not a `ObjectReferenceSegment` (even though it could be), it isn't. Should I try to remodel the `DatatypeSegment` to be `oneOf(ObjectReferenceSegment, <support for primitives>)`?

**Comment by barrywhart** [comment]
@fdw: Please include the commit ID. Issues that say "latest `main`" are often not reproducible because it changes frequently.

**Comment by barrywhart** [comment]
@tunetheweb, @fdw: Should we update the title of this issue? It seems to have changed from a bug to an enhancement request. Or both?

**Comment by tunetheweb** [comment]
> @tunetheweb, @fdw: Should we update the title of this issue? It seems to have changed from a bug to an enhancement request. Or both?

Changed to what I understand the ask is. Feel free to change @fdw if it's incorrect.

**Comment by fdw** [comment]
It is kind of both - on the one hand, there's the feature I would like to see, and on the other, a crash happened.

Since most of the discussion is about the new feature, it makes sense to keep this ticket for the feature only.
If you can tell me which information would be helpful to debug the crash, I can open a new ticket with that :)

**Comment by tunetheweb** [comment]
I'd really like to solve the crash too.

Here's what I'm doing:

Setting my `.sqlfluff` file to this:

```
[sqlfluff]
dialect = tsql

[sqlfluff:rules:L014] # Unquoted identifiers
extended_capitalisation_policy = pascal
ignore_words_regex = "^(Landing.*)$"
```

Trying to lint this SQL:
```sql
SELECT *
FROM LandingA.table1
```

No crash:

```
% sqlfluff lint test.sql
== [test.sql] FAIL                                                                                                                                                   
L:   1 | P:   1 | L044 | Query produces an unknown number of result columns.                                                                                         
L:   2 | P:  15 | L014 | Unquoted identifiers must be pascal case.
All Finished 📜 🎉!
```

**Comment by fdw** [comment]
I tried, but I couldn't reproduce the crash, either. Sorry.

**Comment by peterbud** [comment]
I think this can be also closed. If not - pls let me know and we can re-open
