### ISSUE TITLE
Critical errors when fixing

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#3290]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When running `sqlfluff fix` on some files, I've been getting `CRITICAL` errors for the last several days.

### Expected Behaviour

There should be no critical errors.

### Observed Behaviour

Instead, I get
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/parser/segments/base.py", line 1279, in _validate_segment_after_fixes
    r_copy.parse(parse_context)
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/parser/segments/base.py", line 1078, in parse
    self.segments = self.expand(
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/parser/segments/base.py", line 439, in expand
    res = stmt.parse(parse_context=parse_context)
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/parser/segments/base.py", line 1006, in parse
    raise ValueError(
ValueError: Segment <StatementSegment: ([L:122, P:  7])> ends with non code segment: '\n'.
```

### How to reproduce

See above

### Dialect

T-SQL

### Version

Latest `main`, which should be `8d73a2d9374fa7e3`

### Configuration

n/a

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
No details on how to reproduce
