### ISSUE TITLE
Critical errors with parsing after fix

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#3303]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I run `sqlfluff fix` on the following TSQL
```sql
create procedure name as
begin
drop table if exists #something
  end
```

### Expected Behaviour

I expect the last two lines to be indented differently after fixing.

### Observed Behaviour

Instead, the following error is shown:
```
==== finding fixable violations ====
CRITICAL   After L003 fixes were applied, segment <BeginEndSegment: ([L:  2, P:  1])> failed the parse() check. Fixes: [<LintFix: create_before @[L:  3, P:  1] create:'  '>]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/parser/segments/base.py", line 1279, in _validate_segment_after_fixes
    r_copy.parse(parse_context)
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/parser/segments/base.py", line 1078, in parse
    self.segments = self.expand(
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/parser/segments/base.py", line 439, in expand
    res = stmt.parse(parse_context=parse_context)
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/parser/segments/base.py", line 1006, in parse
    raise ValueError(
ValueError: Segment <StatementSegment: ([L:  3, P:  1])> ends with non code segment: '\n'.
(<DropTableStatementSegment: ([L:  3, P:  1])>, <NewlineSegment: ([L:  3, P: 32]) '\n'>)
```

However, the file is re-formatted correctly.

### How to reproduce

See above.

I suspect the error is related to using a temporary table in `drop table if exists` (like `drop table if exists #something` or `drop table if exists ##something`) and requiring a fix for that line.

### Dialect

T-SQL

### Version

Commit `86bba7073b32552932daee8cd0ee8af47924a13d`

### Configuration

nothing interesting, I think

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
This SQL is unparsable by sqlfluff.

Are you using `--FIX-EVEN-UNPARSABLE` if so that is done at your own risk. However I cannot replicate this with the above SQL even when using that.

**Comment by fdw** [comment]
Interestingly, this seems to parse just fine using `sqlfluff parse`:
```
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    batch:
[L:  1, P:  1]      |        create_procedure_statement:
[L:  1, P:  1]      |            keyword:                                          'create'
[L:  1, P:  7]      |            whitespace:                                       ' '
[L:  1, P:  8]      |            keyword:                                          'procedure'
[L:  1, P: 17]      |            whitespace:                                       ' '
[L:  1, P: 18]      |            object_reference:
[L:  1, P: 18]      |                identifier:                                   'name'
[L:  1, P: 22]      |            [META] indent:
[L:  1, P: 22]      |            whitespace:                                       ' '
[L:  1, P: 23]      |            [META] dedent:
[L:  1, P: 23]      |            keyword:                                          'as'
[L:  1, P: 25]      |            newline:                                          '\n'
[L:  2, P:  1]      |            procedure_statement:
[L:  2, P:  1]      |                statement:
[L:  2, P:  1]      |                    begin_end_block:
[L:  2, P:  1]      |                        keyword:                              'begin'
[L:  2, P:  6]      |                        [META] indent:
[L:  2, P:  6]      |                        newline:                              '\n'
[L:  3, P:  1]      |                        statement:
[L:  3, P:  1]      |                            drop_table_statement:
[L:  3, P:  1]      |                                keyword:                      'drop'
[L:  3, P:  5]      |                                whitespace:                   ' '
[L:  3, P:  6]      |                                keyword:                      'table'
[L:  3, P: 11]      |                                whitespace:                   ' '
[L:  3, P: 12]      |                                keyword:                      'if'
[L:  3, P: 14]      |                                whitespace:                   ' '
[L:  3, P: 15]      |                                keyword:                      'exists'
[L:  3, P: 21]      |                                whitespace:                   ' '
[L:  3, P: 22]      |                                table_reference:
[L:  3, P: 22]      |                                    identifier:               '#something'
[L:  3, P: 32]      |                                newline:                      '\n'
[L:  4, P:  1]      |                                whitespace:                   '  '
[L:  4, P:  3]      |                        [META] dedent:
[L:  4, P:  3]      |                        keyword:                              'end'
```

**Comment by barrywhart** [comment]
This message means there was a parsing error **after** the fixes were applied. It's an internal check designed to detect bugs in the rules or the core linter. I'm taking a closer look now. There's existing code in place designed to handle this case, but it seems to have a bug.
