### ISSUE TITLE
Running `sqlfluff fix` and `sqlfluff lint` produces an attribute error

### ISSUE THREAD

**Issue by R7L208** [sqlfluff/sqlfluff#3438]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Running `sqlfluff fix` and `sqlfluff lint` produces an attribute error.

I tested this running the below commands and all produced a similar stack trace with same error.

```bash
sqlfluff lint --dialect sparksql -vvv test/fixtures/dialects/sparksql/delta_merge.sql
sqlfluff fix --dialect sparksql -vvv test/fixtures/dialects/sparksql/delta_merge.sql
sqlfluff fix --dialect snowflake -vvv test/fixtures/dialects/snowflake/multiple_shorthand_casts.sql
sqlfluff fix --dialect ansi -vvv test/fixtures/dialects/ansi/select_a.sql
```

```bash
> sqlfluff fix --dialect sparksql -vvv test/fixtures/dialects/sparksql/delta_merge.sql
==== sqlfluff ====
sqlfluff:               0.12.0 python:                 3.9.10
implementation:        cpython verbosity:                   3
dialect:              sparksql templater:               jinja
rules:                                all
== Raw Config:
core:
    dialect:            sparksql
    disable_noqa:       False
    encoding:           autodetect
    fix_even_unparsable:False
    ignore:             []
    ignore_templated_areas:True
    nocolor:            False
    output_line_length: 80
    recurse:            True
    rules:              all
    runaway_limit:      10
    sql_file_exts:      .sql,.sql.j2,.dml,.ddl
    templater:          jinja
    verbose:            3
indentation:
    indented_ctes:      False
    indented_joins:     False
    indented_using_on:  True
    template_blocks_indent:True
rules:
    allow_scalar:       True
    comma_style:        trailing
    indent_unit:        space
    max_line_length:    80
    single_table_references:consistent
    tab_space_size:     4
    unquoted_identifiers_policy:all
    Example_L001:
        forbidden_columns:  bar, baaz
    L003:
        hanging_indents:    True
    L007:
        operator_new_lines: after
    L010:
        capitalisation_policy:consistent
    L011:
        aliasing:           explicit
    L012:
        aliasing:           explicit
    L014:
        extended_capitalisation_policy:consistent
    L016:
        ignore_comment_clauses:False
        ignore_comment_lines:False
    L026:
        force_enable:       False
    L027:
    L028:
        force_enable:       False
    L029:
        unquoted_identifiers_policy:aliases
    L030:
        extended_capitalisation_policy:consistent
    L031:
        force_enable:       False
    L036:
        wildcard_policy:    single
    L038:
        select_clause_trailing_comma:forbid
    L040:
        capitalisation_policy:consistent
    L042:
        forbid_subquery_in: join
    L047:
        prefer_count_0:     False
        prefer_count_1:     False
    L051:
        fully_qualify_join_types:inner
    L052:
        multiline_newline:  False
        require_final_semicolon:False
    L054:
        group_by_and_order_by_style:consistent
    L057:
        additional_allowed_characters:""
        allow_space_in_identifier:False
        quoted_identifiers_policy:all
        unquoted_identifiers_policy:all
    L059:
        force_enable:       False
        prefer_quoted_identifiers:False
    L062:
    L063:
        extended_capitalisation_policy:consistent
    L064:
        force_enable:       False
        preferred_quoted_literal_style:consistent
templater:
    unwrap_wrapped_queries:True
    jinja:
        apply_dbt_builtins: True

==== finding fixable violations ====
=== [ path: test/fixtures/dialects/sparksql/delta_merge.sql ] ===

INFO       TEMPLATING RAW [jinja] (test/fixtures/dialects/sparksql/delta_merge.sql)
INFO       Slicing File Template
Traceback (most recent call last):
  File "/Users/lorin.dawson/repos/sqlfluff/src/sqlfluff/core/rules/base.py", line 1083, in register
    "all" in cls.groups
AttributeError: type object 'Rule_Example_L001' has no attribute 'groups'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/lorin.dawson/repos/sqlfluff/.venv/bin/sqlfluff", line 33, in <module>
    sys.exit(load_entry_point('sqlfluff', 'console_scripts', 'sqlfluff')())
  File "/Users/lorin.dawson/repos/sqlfluff/.venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lorin.dawson/repos/sqlfluff/.venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/lorin.dawson/repos/sqlfluff/.venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lorin.dawson/repos/sqlfluff/.venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lorin.dawson/repos/sqlfluff/.venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/lorin.dawson/repos/sqlfluff/src/sqlfluff/cli/commands.py", line 769, in fix
    result = lnt.lint_paths(
  File "/Users/lorin.dawson/repos/sqlfluff/src/sqlfluff/core/linter/linter.py", line 1143, in lint_paths
    self.lint_path(
  File "/Users/lorin.dawson/repos/sqlfluff/src/sqlfluff/core/linter/linter.py", line 1095, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/Users/lorin.dawson/repos/sqlfluff/src/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/Users/lorin.dawson/repos/sqlfluff/src/sqlfluff/core/linter/runner.py", line 56, in iter_partials
    rule_set = self.linter.get_ruleset(config=rendered.config)
  File "/Users/lorin.dawson/repos/sqlfluff/src/sqlfluff/core/linter/linter.py", line 95, in get_ruleset
    rs = get_ruleset()
  File "/Users/lorin.dawson/repos/sqlfluff/src/sqlfluff/core/rules/__init__.py", line 42, in get_ruleset
    std_rules = _load_standard_rules()
  File "/Users/lorin.dawson/repos/sqlfluff/src/sqlfluff/core/rules/__init__.py", line 35, in _load_standard_rules
    std_rule_set.register(rule)
  File "/Users/lorin.dawson/repos/sqlfluff/src/sqlfluff/core/rules/base.py", line 1088, in register
    raise AttributeError(
AttributeError: Rule 'Example_L001' doesn't belong to any rule groups. All rules must belong to at least one group
```

### Expected Behaviour

No attribute error is thrown.

### Observed Behaviour

Attribute error is thrown

### How to reproduce

On main branch, running any of the above commands will reproduce.

### Dialect

sparksql, snowflake and ansi

### Version

sqlfluff, version 0.12.0

### Configuration

Default configs. `.sqlfluff` and `.sqlfluffignore` empty.

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by R7L208** [comment]
Was able to resolve by deleting the `.tox` folder and doing a fresh install of SQLFluff
