### ISSUE TITLE
Crash on fixing reported errors about "Inconsistent Capitalisation of Unquoted Identifiers" L014

### ISSUE THREAD

**Issue by codigo-ergo-sum** [sqlfluff/sqlfluff#366]
I have a SQL file which doesn't have consistent capitalization of unquoted identifiers. sqlfluff reports 213 violations of this. But when I run this command `sqlfluff fix fact_daily_moving_forecast.sql --rules L014` I get this error message:

==== fixing violations ====
213 fixable linting violations found
Are you sure you wish to attempt to fix these? [Y/n] ...
Attempting fixes...
Persisting Changes...
UMMMMMM!
111
('replace', 109, 113, 109, 113)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlfluff/cli/commands.py", line 253, in fix
    success = do_fixes(lnt, result, verbosity=verbose, types=SQLLintError)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlfluff/cli/commands.py", line 183, in do_fixes
    res = result.persist_changes(output_func=lnt.output_func, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlfluff/linter.py", line 505, in persist_changes
    for path in self.paths
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlfluff/linter.py", line 505, in <listcomp>
    for path in self.paths
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlfluff/linter.py", line 388, in persist_changes
    buffer[file.path] = file.persist_tree(verbosity=verbosity)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlfluff/linter.py", line 318, in persist_tree
    write_buff, success = self.fix_string(verbosity=verbosity)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlfluff/linter.py", line 252, in fix_string
    raise NotImplementedError("ABC")
NotImplementedError: ABC

**Comment by codigo-ergo-sum** [comment]
I'm a bit hesitant to post the actual full SQL file here but if needed I can send it privately. Let me know if this doesn't give enough information to reproduce the issue.

**Comment by alanmcruickshank** [comment]
If you're happy to send the full sql directly that would be really helpful to debug this.

In particular with that `NotImplementedError`, there are a couple of codepaths that aren't implemented because I didn't know under what circumstances they would actually happen - so it's really useful that you've found one!

Could you send it to alan<at>designingoverload.com? If it's a sensitive query I won't publish it as a test case in it's entirety. It might be useful to have *part* of the query as a test case but in that case I'll remove all the business specific logic and as much of the query as I can to still replicate the bug. In particular I'll randomise all the identifiers so it's not clear what they referenced in the past.

**Comment by codigo-ergo-sum** [comment]
Sending SQL now. I think you meant alan@designingoverload.com so sending there. Please don't publish query directly.

**Comment by alanmcruickshank** [comment]
@barrywhart brought this up in the discussion around the 0.4.0 release. Given I've got the queries, I'll pick up narrowing down exactly where this issue is coming from so that we've got the clarity we need to fix this.

**Comment by alanmcruickshank** [comment]
Ok this was an excellent test case. Thanks @codigo-ergo-sum , and sorry it's taken this long to get to them.

This has flushed out:
- Another parsing issue with the bigquery `EXCEPT` clause, which is now fixed ✔️ 
- Fixing the above required a parsing improvement which I expect will also lead to a speed increase ✔️ 
- It's also led to an extra feature on the `OneOf` grammar where we can exclude certain patterns ✔️ 
- The issue with L014 appears to be fixed by other changes since the original post. 🤔 
- It's identified another issue with rule L016 however which I'm now working on fixing. ❗ 

All will arrive as one PR in due course.

**Comment by alanmcruickshank** [comment]
The issue with L022 is that if a query is parsed with leading commas before CTEs, but the config is set to expect trailing commas on CTEs there is an infinite loop. I think the solution is that L022 needs to detect the comma style from the query in front of it and act accordingly rather than blindly assuming the config is correct.

I'm actually going to put together a PR for my changes so far and then address that fix seperately.
