### ISSUE TITLE
SQL fluff linting breaks when using DBT variables

### ISSUE THREAD

**Issue by paulorijnberg** [sqlfluff/sqlfluff#3728]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Within Quantile, we are using for a project Snowflake, Meltano and DBT to build a data warehouse. We added to our Github actions some linting testing/automation using SQL Fluff. Which works in general super smooth!

Yesterday I tried adding some a SQL CASE like this to one of our DBT files:
```
-- Add the time of the day segment as a dictionary
day_segment_start_and_end_time AS (
    SELECT
        *,
        CASE
            WHEN 
                favorite_day_segment_for_an_appointment = 'morning' 
                THEN {{ var("day_segments")["morning"] }}
            WHEN 
                favorite_day_segment_for_an_appointment = 'afternoon' 
                THEN {{ var("day_segments")["afternoon"] }}
            WHEN 
                favorite_day_segment_for_an_appointment = 'evening' 
                THEN {{ var("day_segments")["evening"] }}
        END AS favorite_day_segment_start_and_end_time
    FROM
        favorite_time_for_an_appointment
)
```

Since the command **does work**, I wanted to check the SQL fluff linting since this is integrated within our Github actions. When running the SQL fluff linting command, I receive the following problem:
```
❯ meltano invoke sqlfluff:lint
2022-08-05T11:47:40.981271Z [info     ] Environment 'dev' is active
=== [dbt templater] Sorting Nodes...                                                                                                                                                         
file rpt_customer_information.sql:   0%|                                                                                                                              | 0/36 [00:00<?, ?it/s]11:47:49  Unable to do partial parsing because config vars, config profile, or config target have changed
=== [dbt templater] Compiling dbt project...                                                                                                                                                 
=== [dbt templater] Project Compiled.                                                                                                                                                        
file rpt_customer_information.sql:   0%|                                                                                                                              | 0/36 [00:02<?, ?it/s]11:47:51  Unable to do partial parsing because config vars, config profile, or config target have changed
11:47:51  Unable to do partial parsing because env vars used in profiles.yml have changed
11:47:51  Unable to do partial parsing because config vars, config profile, or config target have changed
11:47:51  Unable to do partial parsing because env vars used in profiles.yml have changed
11:47:51  Unable to do partial parsing because config vars, config profile, or config target have changed
11:47:51  Unable to do partial parsing because env vars used in profiles.yml have changed
11:47:51  Unable to do partial parsing because config vars, config profile, or config target have changed
11:47:51  Unable to do partial parsing because env vars used in profiles.yml have changed
== [/COMPANY-NAME-ANONYMIZED/meltano/transform/models/reporting/customer_contact/rpt_customers_favorite_day_time.sql] FAIL                                                                               
L:  79 | P:  13 |  PRS | Line 79, Position 13: Found unparsable section: 'WHEN \n                                                                                                            
                       | favorite_day_segme...'
WARNING: Parsing errors found and dialect is set to 'snowflake'. Have you configured your dialect correctly?                                                                                 
All Finished :scroll: :tada:! 
```

I tried adding the dbt variables to my `.sqlfluff` config file, but that didn't seem to solve the problem.
```
[sqlfluff]
dialect = snowflake
templater = dbt
output_line_length = 80
ignore_templated_areas = True
runaway_limit = 100
exclude_rules = L001, L009, L014, L016, L034

[sqlfluff:templater:dbt]
project_dir = transform
profiles_dir = transform/profiles/snowflake
profile = meltano
target = default

[sqlfluff:templater:jinja:context]
day_segments = {morning: {start: 0, end: 12}, afternoon: {start: 12,end: 17}, evening: {start: 17,end: 23}}

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 120
indent_unit = space
comma_style = trailing

[sqlfluff:rules:L014]
extended_capitalisation_policy = lower

[sqlfluff:rules:L036]
wildcard_policy = multiple
```

### Expected Behaviour

Since DBT build works, the code actually works. But SQL linting says it isn't able to parse it.

### Observed Behaviour

It says that the code can't be parsed. So I tried replacing the DBT variables with just arbitrary values. This **does** work! So I observed that the problem is that it breaks due to the CASE SQL statement in combination with the DBT variables.

### How to reproduce

Use DBT variables in the THEN part of a CASE statement. 

### Dialect

snowflake

### Version

Installed via Meltano utility functions -> `pip_url: sqlfluff[dbt]`

### Configuration

.sqlfluff

```
[sqlfluff]
dialect = snowflake
templater = dbt
output_line_length = 80
ignore_templated_areas = True
runaway_limit = 100
exclude_rules = L001, L009, L014, L016, L034

[sqlfluff:templater:dbt]
project_dir = transform
profiles_dir = transform/profiles/snowflake
profile = meltano
target = default

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 120
indent_unit = space
comma_style = trailing

[sqlfluff:rules:L014]
extended_capitalisation_policy = lower

[sqlfluff:rules:L036]
wildcard_policy = multiple
```

```
.meltano/
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by masteinhauser** [comment]
@paulorijnberg Could you try re-using the same `.sqlfluff` config file but with the following change?

From:
```
[sqlfluff:templater:jinja:context]
```

To:
```
[sqlfluff:templater:dbt:context]
```

I believe that you might have a typo, but I am currently working through enabling DBT variables in my own project and have yet to be successful.

**Comment by paulorijnberg** [comment]
Hi @masteinhauser,

Thanks for your tip, but unfortunately it doesn't work. It gives me the following error:

```
Traceback (most recent call last):
  File "/change-data/meltano/.meltano/utilities/sqlfluff/venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 494, in catch_jinja
    yield
  File "/change-data/meltano/.meltano/utilities/sqlfluff/venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 526, in render_template
    return template.render(ctx)
  File "/change-data/meltano/.meltano/utilities/sqlfluff/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/change-data/meltano/.meltano/utilities/sqlfluff/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/change-data/meltano/.meltano/utilities/sqlfluff/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 44, in top-level template code
  File "/change-data/meltano/.meltano/utilities/sqlfluff/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 384, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'morning'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/change-data/meltano/.meltano/utilities/sqlfluff/venv/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 464, in _unsafe_process
    node = self.dbt_compiler.compile_node(
  File "/change-data/meltano/.meltano/utilities/sqlfluff/venv/lib/python3.9/site-packages/dbt/compilation.py", line 513, in compile_node
    node = self._compile_node(node, manifest, extra_context)
  File "/change-data/meltano/.meltano/utilities/sqlfluff/venv/lib/python3.9/site-packages/dbt/compilation.py", line 374, in _compile_node
    compiled_node.compiled_sql = jinja.get_rendered(
  File "/change-data/meltano/.meltano/utilities/sqlfluff/venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 571, in get_rendered
    return render_template(template, ctx, node)
  File "/change-data/meltano/.meltano/utilities/sqlfluff/venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 526, in render_template
    return template.render(ctx)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/change-data/meltano/.meltano/utilities/sqlfluff/venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 499, in catch_jinja
    raise UndefinedMacroException(str(e), node) from e
dbt.exceptions.UndefinedMacroException: Compilation Error in model rpt_customers_favorite_day_time (models/reporting/customer_contact/rpt_customers_favorite_day_time.sql)
  'str object' has no attribute 'morning'. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
WARNING    Skipped file /change-data/meltano/transform/models/reporting/customer_contact/rpt_customers_favorite_day_time.sql because dbt raised a fatal exception during compilation: Compilation Error in model rpt_customers_favorite_day_time (models/reporting/customer_contact/rpt_customers_favorite_day_time.sql)
  'str object' has no attribute 'morning'. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
```

Might be due to the fact that the variable is nested. 

```
[sqlfluff:templater:dbt:context]
day_segments = {"morning": {"start": 0, "end": 12}, "afternoon": {"start": 12, "end": 17}, "evening": {"start": 17, "end": 23}}
```

**Comment by DiogoReisPinto** [comment]
We are facing the same issue in our project. For now, as a workaround, we have disabled templating checks for SQL Fluff using in our `.sqlfluff` configuration:

`[sqlfluff]
ignore = templating`

but it is not ideal as we are skipping all template checks at project level.

**Comment by masteinhauser** [comment]
I'm still AFK, but I have a fully working nested variable configuration I
can share tomorrow.

It was difficult to get working since there were no documented examples or
tests, so I'll be adding something similar.

**Comment by paulorijnberg** [comment]
@masteinhauser i would love to get that!

@DiogoReisPinto i also tried adding the ignore clause, but for some reason it just complete skips it

**Comment by barrywhart** [comment]
Changed label from `bug` to `documentation` since it sounds like it's working for some people.

**Comment by barrywhart** [comment]
@masteinhauser: Are you still planning to provide that example?

**Comment by krazavet-tinyclues** [comment]
Hello 👋 
I'm facing the same issue, nested structures are a nightmare to translate them as `.ini` object structure. Even though it is possible, it's still annoying without using json structure.

I was wondering maybe using `[sqlfluff:templater:jinja:macros]` section, we could take advantage of `dbt_var` macros definition, but it seems also complicated.

But if there is a more elegant way to solve this, I'm quite curious by your solution @masteinhauser 🙂

**Comment by masteinhauser** [comment]
Firstly, sincere apologies for the delay! I actually had forgotten about this project as we got stuck needing to upgrade to DBT 1.2.0 before we could integrate sqlfluff into our usage.

Unfortunately, @krazavet-tinyclues is correct with the nightmare that is embedded nested data within the INI format.

The example and usage that I came up with is the following:
```
# Run the sqlfluff test with the following commands:
#   $ dbt deps
#   $ DATABASE=cicd-0000000000 HOST=localhost PORT=5432 DBT_USER=sqlfluff DBT_PASSWORD=nopass sqlfluff lint --config .sqlfluff.abcd-1234567890

################################
##   DBT Vars Configuration   ##
################################
[sqlfluff:templater:dbt:context]
client = "abcd-1234567890"
staging_schema = "staging"

[sqlfluff:templater:dbt:context:client_config]
products = [ "example" ]

[sqlfluff:templater:dbt:context:client_config:sources]
abcd = { }

[sqlfluff:templater:dbt:context:default_config:options]
enable_v2_metrics = false
metrics_version = "3"

[sqlfluff:templater:dbt:context:schemas]
analytics = "analytics"
customer_data_model = "customer_data_model"
staging = "staging"
trends = "trends"

[sqlfluff:templater:dbt:context:settings]
key = "value"
```

However, we **only** use this structure for `sqlfluff` where we cannot easily modify the pre-commit command which is used. In our normal pipeline we pass all dynamic configuration via a combination of `--vars` and custom `config` files which we overlay into our pipeline.

It's inherently complicated as we have a small number of pipelines supporting a large number of clients. All of which require minor and somewhat subtle configuration and codepath branching for inherent data model differences.

**Comment by krazavet-tinyclues** [comment]
> However, we **only** use this structure for `sqlfluff` where we cannot easily modify the pre-commit command which is used. In our normal pipeline we pass all dynamic configuration via a combination of `--vars` and custom `config` files which we overlay into our pipeline.
> 
> It's inherently complicated as we have a small number of pipelines supporting a large number of clients. All of which require minor and somewhat subtle configuration and codepath branching for inherent data model differences.

In my company, we are exactly in the same situation, and so we need to rely a lot on the DBT variables to make our pipeline working for any client.
[DBT variables are using YAML or JSON format](https://docs.getdbt.com/docs/build/project-variables#defining-variables-on-the-command-line), which makes me think it should be easier to write and parse variables if they were written like such 👇 
```ini
[sqlfluff:templater:jinja:context]
my_dict = {"field_1": val_1, "field_2": {"field_3": val_3, "field_4": null}, ...} # JSON format here 👈 
```
A [new issue](https://github.com/sqlfluff/sqlfluff/issues/4153) has been opened last month regarding Jinja nested variables, and we can see in the `Use case` section the example given uses a Python dictionary.
What do you think about JSON or YAML object structure to provide DBT variables ?

**Comment by paulorijnberg** [comment]
@krazavet-tinyclues adding something in general for nested variables would be nice! FYI, we've solved this problem by doing some additional transformation to our data warehouse to bypass this. Tbh it would be much nicer if we could have used the nested functionality.
