### ISSUE TITLE
Jinja templater: "{% include %}" files cause linting to fail and stop if they use undefined Jinja variables

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#3738]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

SQLFluff has the `load_macros_from_path` config setting to configure the location of **macro** files. But Jinja also supports a simpler `{% include %}` directive. These are not macro files, just literal SQL files to pull into the main file. If I try and specify this directory to `load_macros_from_path`, I often get errors when SQLFluff tries to load macros from those files, e.g.:
```
Traceback (most recent call last):
  File "/Users/barry.hart/.pyenv/versions/product-recs-v2-3.10.4/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/sqlfluff/cli/commands.py", line 1008, in parse
    parsed_strings = list(
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/sqlfluff/core/linter/linter.py", line 1171, in parse_path
    yield self.parse_string(
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/sqlfluff/core/linter/linter.py", line 835, in parse_string
    rendered = self.render_string(in_str, fname, config, encoding)
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/sqlfluff/core/linter/linter.py", line 784, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/sqlfluff/core/templaters/base.py", line 47, in _wrapped
    return func(self, in_str=in_str, fname=fname, config=config, **kwargs)
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 342, in process
    env, live_context, make_template = self.template_builder(
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 297, in template_builder
    live_context = self.get_context(fname=fname, config=config, env=env)
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 276, in get_context
    self._extract_macros_from_path(
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 99, in _extract_macros_from_path
    cls._extract_macros_from_path(
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 84, in _extract_macros_from_path
    cls._extract_macros_from_template(template, env=env, ctx=ctx)
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 60, in _extract_macros_from_template
    for k in macro_template.module.__dict__:
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/jinja2/environment.py", line 1478, in module
    return self._get_default_module()
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/jinja2/environment.py", line 1446, in _get_default_module
    self._module = self.make_module()
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/jinja2/environment.py", line 1405, in make_module
    return TemplateModule(self, ctx)
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/jinja2/environment.py", line 1535, in __init__
    body_stream = list(template.root_render_func(context))  # type: ignore
  File "<template>", line 27, in root
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/jinja2/loaders.py", line 195, in get_source
    pieces = split_template_path(template)
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/jinja2/loaders.py", line 30, in split_template_path
    for piece in template.split("/"):
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/Users/barry.hart/.pyenv/versions/3.10.4/envs/product-recs-v2-3.10.4/lib/python3.10/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'sql_file' is undefined
```

Can we add a separate config setting, e.g. `include_path`, that is available for `{% include %}` but is not processed as macros?

### Use case

I want to lint and fix SQL files that use Jinja `{% include %}`.

### Dialect

n/a

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
The specific errors I were encountering were not really related to macros vs `{% include %}` -- if we add some exception-handling logic to `extract_macros_from_template()`, I think that'll address the need. As an experiment, I wrapped an exception handler around the loop inside that function, e.g.:
```
        from jinja2.exceptions import UndefinedError
        try:
          for k in macro_template.module.__dict__:
            print(f"Module field: {k}")
            attr = getattr(macro_template.module, k)
            # Is it a macro? If so install it at the name of the macro
            if isinstance(attr, Macro):
                context[k] = attr
        except UndefinedError as e:
            pass
```

**Comment by barrywhart** [comment]
Note: The `UndefinedError` occurs when a file being included references an undefined Jinja variable. This happened when first setting up the project because `.sqlfluff` was missing some definitions in `[sqlfluff:templater:jinja:context]`.

**Comment by barrywhart** [comment]
In my initial experiments, rather than the above proposed fix, I had hacked in the following change:
```
    def _get_jinja_env(self, config=None):
        """Get a properly configured jinja environment."""
        # We explicitly want to preserve newlines.
        macros_path = self._get_macros_path(config)
        return SandboxedEnvironment(
            keep_trailing_newline=True,
            # The do extension allows the "do" directive
            autoescape=False,
            extensions=["jinja2.ext.do"],
            loader=FileSystemLoader("src"),
            #loader=FileSystemLoader(macros_path) if macros_path else None,
        )
```

This points to a potential alternate fix, allowing the user to configure a path for `include` files, separate from the path for macro files. But if we can make the existing `load_macros_from_path` config setting work for both, that seems better to me (keeps things simpler, more consistent, avoids adding more settings).

**Comment by barrywhart** [comment]
Test case:

`.sqlfluff`:
```
[sqlfluff]
dialect = ansi

[sqlfluff:templater:jinja]
load_macros_from_path = macros

```

`test.sql`:
```
SELECT id
FROM records
```

`macros/utils.sql`:
```
{% include sql_file %}
```
