### ISSUE TITLE
ERROR      dbt_profiles_dir: /Users/tekumara/.dbt could not be accessed. Check it exists.     

### ISSUE THREAD

**Issue by tekumara** [sqlfluff/sqlfluff#3744]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

```
export DBT_PROFILES_DIR=.
sqlfluff lint
=== [dbt templater] Sorting Nodes...                                                                                                                                       
ERROR      dbt_profiles_dir: /Users/tekumara/.dbt could not be accessed. Check it exists.                                                                            
file account.sql:   0%|                                                                                                                             | 0/40 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/tekumara/code/jaffles-shop/.venv/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 560, in lint
    result = lnt.lint_paths(
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 1140, in lint_paths
    self.lint_path(
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 1092, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 40, in iter_rendered
    for fname in self.linter.templater.sequence_files(
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 270, in sequence_files
    for key, node in self.dbt_manifest.nodes.items():
  File "/Users/tekumara/.pyenv/versions/3.9.13/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 143, in dbt_manifest
    projects = self.dbt_config.load_dependencies()
  File "/Users/tekumara/.pyenv/versions/3.9.13/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 108, in dbt_config
    self.dbt_config = DbtRuntimeConfig.from_args(
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/dbt/config/runtime.py", line 240, in from_args
    project, profile = cls.collect_parts(args)
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/dbt/config/runtime.py", line 214, in collect_parts
    profile = cls._get_rendered_profile(
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/dbt/config/runtime.py", line 192, in _get_rendered_profile
    return Profile.render_from_args(
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/dbt/config/profile.py", line 440, in render_from_args
    return cls.from_raw_profiles(
  File "/Users/tekumara/code/jaffles-shop/.venv/lib/python3.9/site-packages/dbt/config/profile.py", line 387, in from_raw_profiles
    raise DbtProjectError(
dbt.exceptions.DbtProjectError: Runtime Error
  Could not find profile named 'snowflake'
make: *** [lint] Error 1                                                                                                                                                   
```

### Expected Behaviour

No error when DBT_PROFILES_DIR is set and ~/.dbt does not exist.

### Observed Behaviour

See above

### How to reproduce

1. Make sure you don't have ~/.dbt
1. Add a profiles.yml to the current dir
1. 
```
export DBT_PROFILES_DIR=.
sqlfluff lint
```

### Dialect

snowflake

### Version

sqlfluff, version 1.2.1

### Configuration

```
[tool.sqlfluff.core]
templater = "dbt"
sql_file_exts = ".sql,.sql.j2,.dml,.ddl"
dialect = "snowflake"

[tool.sqlfluff.templater.dbt]
project_dir = "."
profile = "snowflake"
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
@tekumara - why are your configuration values prefixed by `tool`? Can you confirm that you still experience this issue if you change your `.sqlfluff` file to:

```ini
[sqlfluff]
templater = "dbt"
sql_file_exts = ".sql,.sql.j2,.dml,.ddl"
dialect = "snowflake"

[sqlfluff.templater.dbt]
project_dir = "."
profile = "snowflake"
```

**Comment by tekumara** [comment]
I'm using pyproject.toml hence the `tool` prefix.

**Comment by alanmcruickshank** [comment]
On checking this in more detail, I think you're missing the `profiles_dir` configuration setting as specified in [the docs](https://docs.sqlfluff.com/en/stable/configuration.html#installation-configuration).

Give this is a fairly old issue and I think it's covered in the docs, I'm going to close this. Do reopen it if this doesn't fix the issue.

**Comment by tekumara** [comment]
Oh right, I was using `DBT_PROFILES_DIR` env var instead - is that not supported?

**Comment by alanmcruickshank** [comment]
I've just done some testing. This is already supported 👍. In fact we use this feature in our dbt project at tails.com.

I'm going to raise a small PR to make the error clearer, but otherwise I think this is sorted. @tekumara - can you confirm whether you're still having issues with accessing the profiles file?

**Comment by tekumara** [comment]
Thank you! I can confirm I can't replicate this in sqlfluff 1.4.5
