### ISSUE TITLE
SQLFluff ignores specified encoding and autodetected even if it is enforced in CLI

### ISSUE THREAD

**Issue by jakubvedral** [sqlfluff/sqlfluff#3815]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

If i run:

`sqlfluff fix --dialect bigquery --encoding=utf-8 models/test.sql`

I will get an error where file is not correctly read. Specified  encoding is not used and is autodetected instead.

Error:
```
Traceback (most recent call last):
  File "C:\Users\jakub\.conda\envs\pm-dbt_base\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jakub\.conda\envs\pm-dbt_base\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jakub\.conda\envs\pm-dbt_base\Scripts\sqlfluff.exe\__main__.py", line 7, in <module>
  File "C:\Users\jakub\.conda\envs\pm-dbt_base\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\jakub\.conda\envs\pm-dbt_base\lib\site-packages\sqlfluff\core\linter\runner.py", line 102, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "C:\Users\jakub\.conda\envs\pm-dbt_base\lib\site-packages\sqlfluff\core\linter\runner.py", line 55, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "C:\Users\jakub\.conda\envs\pm-dbt_base\lib\site-packages\sqlfluff\core\linter\runner.py", line 44, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "C:\Users\jakub\.conda\envs\pm-dbt_base\lib\site-packages\sqlfluff\core\linter\linter.py", line 813, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "C:\Users\jakub\.conda\envs\pm-dbt_base\lib\site-packages\sqlfluff\core\linter\linter.py", line 784, in render_string
    templated_file, templater_violations = self.templater.process(
  File "C:\Users\jakub\.conda\envs\pm-dbt_base\lib\site-packages\sqlfluff\core\templaters\base.py", line 47, in _wrapped
    return func(self, in_str=in_str, fname=fname, config=config, **kwargs)
  File "C:\Users\jakub\.conda\envs\pm-dbt_base\lib\site-packages\sqlfluff_templater_dbt\templater.py", line 344, in process
    processed_result = self._unsafe_process(fname_absolute_path, in_str, config)
  File "C:\Users\jakub\.conda\envs\pm-dbt_base\lib\site-packages\sqlfluff_templater_dbt\templater.py", line 519, in _unsafe_process
    source_dbt_sql = source_dbt_model.read()
  File "C:\Users\jakub\.conda\envs\pm-dbt_base\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 13: character maps to <undefined>
```

contents of test.sql file to reproduce the error:
```
select 
'ŠČŘŽÝÁ' as text
```
Even when I try some tricks I found in simillar errors it does not help (like deleting target directory).

DBT run & compile works OK as expected:

```
dbt compile -m test 
17:25:37  Running with dbt=1.2.1
17:25:38  Found 230 models, 267 tests, 8 snapshots, 0 analyses, 700 macros, 0 operations, 2 seed files, 60 sources, 0 exposures, 0 metrics
17:25:38  
17:25:38  Concurrency: 4 threads (target='dev')
17:25:38  
17:25:38  Done.
```

### Expected Behaviour

Fluff should use correct encoding to read the file and not try to autodetect (or use Windows default). 

### Observed Behaviour

Sqlfluff fix will try to detect the encoding and ignore the file encoding specified in CLI command.

### How to reproduce

create test.sql file to reproduce the error:
```
select 
'ŠČŘŽÝÁ' as text
```

and run 
`sqlfluff fix --dialect bigquery --encoding=utf-8 models/test.sql`
using .sqlfluff settings and enviroment specified below .

### Dialect

bigquery

### Version

Python packages (pip freeze) under Anaconda 3.9 environment

```
agate==1.6.3
appdirs==1.4.4
atomicwrites==1.4.1
attrs==22.1.0
Babel==2.10.3
cachetools==5.2.0
certifi @ file:///C:/Windows/TEMP/abs_e9b7158a-aa56-4a5b-87b6-c00d295b01fanefpc8_o/croots/recipe/certifi_1655968940823/work/certifi
cffi==1.15.1
cfgv==3.3.1
chardet==5.0.0
charset-normalizer==2.1.1
click==8.1.3
colorama==0.4.5
dbt-bigquery==1.2.0
dbt-core==1.2.1
dbt-extractor==0.4.1
diff-cover==6.5.1
distlib==0.3.6
filelock==3.8.0
future==0.18.2
google-api-core==2.8.2
google-auth==2.11.0
google-cloud-bigquery==2.34.4
google-cloud-core==2.3.2
google-crc32c==1.3.0
google-resumable-media==2.3.3
googleapis-common-protos==1.56.4
grpcio==1.47.0
grpcio-status==1.47.0
hologram==0.0.15
identify==2.5.3
idna==3.3
iniconfig==1.1.1
isodate==0.6.1
Jinja2==2.11.3
jinja2-simple-tags==0.4.0
jsonschema==3.2.0
leather==0.3.4
Logbook==1.5.3
MarkupSafe==2.0.1
mashumaro==2.9
minimal-snowplow-tracker==0.0.2
msgpack==1.0.4
networkx==2.8.6
nodeenv==1.7.0
packaging==21.3
parsedatetime==2.4
pathspec==0.9.0
platformdirs==2.5.2
pluggy==1.0.0
pre-commit==2.20.0
proto-plus==1.22.0
protobuf==3.20.1
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
Pygments==2.13.0
pyparsing==3.0.9
pyrsistent==0.18.1
pytest==7.1.2
python-dateutil==2.8.2
python-slugify==6.1.2
pytimeparse==1.1.8
pytz==2022.2.1
PyYAML==6.0
regex==2022.8.17
requests==2.28.1
rsa==4.9
six==1.16.0
sqlfluff==1.3.0
sqlfluff-templater-dbt==1.3.0
sqlparse==0.4.2
tblib==1.7.0
text-unidecode==1.3
toml==0.10.2
tomli==2.0.1
tqdm==4.64.0
typing_extensions==4.3.0
urllib3==1.26.12
virtualenv==20.16.3
Werkzeug==2.1.2
wincertstore==0.2
```

anaconda version: conda 4.12.0

Windows info:
```
WindowsBuildLabEx                                       : 22000.1.amd64fre.co_release.210604-1628
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : Professional
WindowsInstallationType                                 : Client
WindowsInstallDateFromRegistry                          : 03.06.2022 10:16:26
WindowsProductName                                      : Windows 10 Pro
WindowsSystemRoot                                       : C:\Windows
WindowsVersion                                          : 2009
WindowsUBR                                              : 856
BiosCharacteristics                                     : {7, 10, 11, 12…}
BiosBIOSVersion                                         : {ALASKA - 1072009, 4204, American Megatrends - 50011}
BiosBuildNumber                                         :
BiosCaption                                             : 4204
BiosCodeSet                                             :
BiosCurrentLanguage                                     : en|US|iso8859-1
BiosDescription                                         : 4204
BiosEmbeddedControllerMajorVersion                      : 255
BiosEmbeddedControllerMinorVersion                      : 255
BiosFirmwareType                                        : Uefi
BiosIdentificationCode                                  :
BiosInstallableLanguages                                : 9
BiosInstallDate                                         :
BiosLanguageEdition                                     :
BiosListOfLanguages                                     : {en|US|iso8859-1, fr|FR|iso8859-1, zh|TW|unicode, zh|CN|unico
                                                          de…}
BiosManufacturer                                        : American Megatrends Inc.
BiosName                                                : 4204
BiosOtherTargetOS                                       :
BiosPrimaryBIOS                                         : True
BiosReleaseDate                                         : 25.02.2022 1:00:00
BiosSerialNumber                                        : System Serial Number
BiosSMBIOSBIOSVersion                                   : 4204
BiosSMBIOSMajorVersion                                  : 3
BiosSMBIOSMinorVersion                                  : 3
BiosSMBIOSPresent                                       : True
BiosSoftwareElementState                                : Running
BiosStatus                                              : OK
BiosSystemBiosMajorVersion                              : 5
BiosSystemBiosMinorVersion                              : 17
BiosTargetOperatingSystem                               : 0
BiosVersion                                             : ALASKA - 1072009
CsAdminPasswordStatus                                   : Unknown
CsAutomaticManagedPagefile                              : True
CsAutomaticResetBootOption                              : True
CsAutomaticResetCapability                              : True
CsBootOptionOnLimit                                     :
CsBootOptionOnWatchDog                                  :
CsBootROMSupported                                      : True
CsBootStatus                                            : {0, 0, 0, 0…}
CsBootupState                                           : Normal boot
CsChassisBootupState                                    : Safe
CsChassisSKUNumber                                      : Default string
CsCurrentTimeZone                                       : 120
CsDaylightInEffect                                      : True
CsDescription                                           : AT/AT COMPATIBLE
CsDomainRole                                            : StandaloneWorkstation
CsEnableDaylightSavingsTime                             : True
CsFrontPanelResetStatus                                 : Unknown
CsHypervisorPresent                                     : True
CsInfraredSupported                                     : False
CsInitialLoadInfo                                       :
CsInstallDate                                           :
CsKeyboardPasswordStatus                                : Unknown
CsLastLoadInfo                                          :
CsManufacturer                                          : ASUS
CsModel                                                 : System Product Name
CsNetworkServerModeEnabled                              : True
CsNumberOfLogicalProcessors                             : 24
CsNumberOfProcessors                                    : 1
CsProcessors                                            : {AMD Ryzen 9 5900X 12-Core Processor            }
CsOEMStringArray                                        : {Default string, Default string, Default string, Default stri
                                                          ng…}
CsPartOfDomain                                          : False
CsPauseAfterReset                                       : -1
CsPCSystemType                                          : Desktop
CsPCSystemTypeEx                                        : Desktop
CsPowerManagementCapabilities                           :
CsPowerManagementSupported                              :
CsPowerOnPasswordStatus                                 : Unknown
CsPowerState                                            : Unknown
CsPowerSupplyState                                      : Safe
CsPrimaryOwnerContact                                   :
CsResetCapability                                       : Other
CsResetCount                                            : -1
CsResetLimit                                            : -1
CsRoles                                                 : {LM_Workstation, LM_Server, NT, Potential_Browser…}
CsStatus                                                : OK
CsSupportContactDescription                             :
CsSystemFamily                                          : To be filled by O.E.M.
CsSystemSKUNumber                                       : SKU
CsSystemType                                            : x64-based PC
CsThermalState                                          : Safe
CsTotalPhysicalMemory                                   : 68629106688
CsPhysicallyInstalledMemory                             : 67108864
OsName                                                  : Microsoft Windows 11 Pro
OsType                                                  : WINNT
OsOperatingSystemSKU                                    : 48
OsVersion                                               : 10.0.22000
OsCSDVersion                                            :
OsBuildNumber                                           : 22000
OsCountryCode                                           : 420
OsCurrentTimeZone                                       : 120
OsLocaleID                                              : 0405
OsLocale                                                : cs-CZ
OsLocalDateTime                                         : 30.08.2022 19:31:34
OsLastBootUpTime                                        : 29.08.2022 9:28:10
OsUptime                                                : 1.10:03:24.3027580
OsBuildType                                             : Multiprocessor Free
OsCodeSet                                               : 1250
OsDataExecutionPreventionAvailable                      : True
OsDataExecutionPrevention32BitApplications              : True
OsDataExecutionPreventionDrivers                        : True
OsDataExecutionPreventionSupportPolicy                  : OptIn
OsDebug                                                 : False
OsDistributed                                           : False
OsEncryptionLevel                                       : 256
OsForegroundApplicationBoost                            : Maximum
OsTotalVisibleMemorySize                                : 67020612
OsFreePhysicalMemory                                    : 46490924
OsTotalVirtualMemorySize                                : 100922052
OsFreeVirtualMemory                                     : 31510128
OsInUseVirtualMemory                                    : 69411924
OsTotalSwapSpaceSize                                    :
OsSizeStoredInPagingFiles                               : 33901440
OsFreeSpaceInPagingFiles                                : 28463652
OsPagingFiles                                           : {C:\pagefile.sys}
OsHardwareAbstractionLayer                              : 10.0.22000.778
OsInstallDate                                           : 03.06.2022 12:16:26
OsManufacturer                                          : Microsoft Corporation
OsMaxNumberOfProcesses                                  : 4294967295
OsMaxProcessMemorySize                                  : 137438953344
OsMuiLanguages                                          : {cs-CZ, en-US}
OsNumberOfLicensedUsers                                 :
OsNumberOfProcesses                                     : 372
OsNumberOfUsers                                         : 2
OsOrganization                                          :
OsArchitecture                                          : 64bitový
OsLanguage                                              : cs-CZ
OsProductSuites                                         : {TerminalServicesSingleSession}
OsOtherTypeDescription                                  :
OsPAEEnabled                                            :
OsPortableOperatingSystem                               : False
OsPrimary                                               : True
OsProductType                                           : WorkStation
OsServicePackMajorVersion                               : 0
OsServicePackMinorVersion                               : 0
OsStatus                                                : OK
OsServerLevel                                           :
KeyboardLayout                                          : cs-CZ
TimeZone                                                : (UTC+01:00) Praha, Bratislava, Budapešť, Bělehrad, Lublaň
PowerPlatformRole                                       : Desktop
HyperVisorPresent                                       : True
HyperVRequirementDataExecutionPreventionAvailable       :
HyperVRequirementSecondLevelAddressTranslation          :
HyperVRequirementVirtualizationFirmwareEnabled          :
HyperVRequirementVMMonitorModeExtensions                :
DeviceGuardSmartStatus                                  : Off
DeviceGuardRequiredSecurityProperties                   :
DeviceGuardAvailableSecurityProperties                  :
DeviceGuardSecurityServicesConfigured                   :
DeviceGuardSecurityServicesRunning                      :
DeviceGuardCodeIntegrityPolicyEnforcementStatus         :
DeviceGuardUserModeCodeIntegrityPolicyEnforcementStatus :
```

### Configuration

.sqlfluff
```
[sqlfluff]
templater = dbt
encoding = utf-8

[sqlfluff:templater:jinja]
apply_dbt_builtins = True
load_macros_from_path = macros

[sqlfluff:rules]
tab_space_size = 2
max_line_length = 160
indent_unit = space
comma_style = trailing
allow_scalar = True
single_table_references = consistent
unquoted_identifiers_policy = all

[sqlfluff:rules:L010]
# Keywords
capitalisation_policy = lower

```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
We think this behavior is because of dbt, because when using dbt templater, dbt reads the file. It seems to work correctly with the Jinja templater. There's a related issue about this. Hopefully we can at least have SQLFluff warn about this.

Are you using Windows? Everyone else who has had this issue has been on Windows.

**Comment by jakubvedral** [comment]
Yep, I am using Windows.

**Comment by jakubvedral** [comment]
If I edit dbt_templater to read using utf-8 it works. 
I dont know how to read the SQLFluff encoding config value from the code there to propagate it correctly.

If I could, I can try to fix it and make a PR.


`site-packages\sqlfluff_templater_dbt\templater.py", line 518, in _unsafe_process`

```
with open(fname,encoding='utf8') as source_dbt_model:
    source_dbt_sql = source_dbt_model.read()
```

**Comment by barrywhart** [comment]
Interesting! If you'd like to go ahead and create a PR (including a test for the fix), I'll comment on it later with advice on how to access the config setting.

**Comment by barrywhart** [comment]
In the dbt templater, we may want to use `in_str` rather than reading the SQL file from disk, because SQLFluff knows and uses the encoding specified in `.sqlfluff`.

**Comment by barrywhart** [comment]
This was fixed a while back under a separate issue. Tested today against `main` branch.
