### ISSUE TITLE
SQLFluff does not support dbt_metrics package

### ISSUE THREAD

**Issue by joris-swapfiets** [sqlfluff/sqlfluff#3832]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

A .sql file that uses the [dbt_metrics](https://github.com/dbt-labs/dbt_metrics) syntax throws an error. 

### Expected Behaviour

I expect SQLFluff to just lint the file without throwing an error.

### Observed Behaviour

When running `sql lint` on a file that uses the [dbt_metrics](https://github.com/dbt-labs/dbt_metrics) syntax a CompilationExceptionError is thrown.

### How to reproduce

When running `sql lint` on the following file:
```
select *
from {{ metrics.calculate(
    metric('on_site_repairs'),
    grain='month',
    dimensions=['business_unit', 'asset_category_name'],
    secondary_calculations=[],
    start_date='2022-01-01',
    end_date='2022-12-31'
) }}
```
This error is thrown
```
=== [dbt templater] Sorting Nodes...
13:47:33  Unable to do partial parsing because config vars, config profile, or config target have changed

=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
ERROR      Fatal dbt compilation error on /Users/jorisvanraaij/Documents/Data/GIT/dbt_reporting/models/metrics/on_site_repairs/on_site_repairs_month.sql. This occurs most often during incorrect sorting of ephemeral models before linting. Please report this error on github at https://github.com/sqlfluff/sqlfluff/issues, including both the raw and compiled sql for the model affected. 
Traceback (most recent call last):
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 293, in exception_handler
    yield
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 248, in call_macro
    return macro(*args, **kwargs)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 33, in macro
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/jinja2/sandbox.py", line 407, in getattr
    value = getattr(obj, attribute)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/jinja2/runtime.py", line 753, in __getattr__
    return self._fail_with_undefined_error()
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/jinja2/runtime.py", line 747, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'nodes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/sqlfluff_templater_dbt/templater.py", line 480, in _unsafe_process
    node = self.dbt_compiler.compile_node(
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/dbt/compilation.py", line 515, in compile_node
    node = self._compile_node(node, manifest, extra_context)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/dbt/compilation.py", line 374, in _compile_node
    compiled_node.compiled_sql = jinja.get_rendered(
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 571, in get_rendered
    return render_template(template, ctx, node)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 526, in render_template
    return template.render(ctx)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 2, in top-level template code
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 321, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 248, in call_macro
    return macro(*args, **kwargs)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 2, in template
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 321, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 248, in call_macro
    return macro(*args, **kwargs)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 9, in template
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 321, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 248, in call_macro
    return macro(*args, **kwargs)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 128, in template
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 321, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 250, in call_macro
    return e.value
  File "/Users/jorisvanraaij/.pyenv/versions/3.8.10/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 295, in exception_handler
    raise_compiler_error(str(e), self.macro)
  File "/Users/jorisvanraaij/Library/Caches/pypoetry/virtualenvs/dbt-reporting-GtWEb2s_-py3.8/lib/python3.8/site-packages/dbt/exceptions.py", line 445, in raise_compiler_error
    raise CompilationException(msg, node)
dbt.exceptions.CompilationException: Compilation Error in model on_site_repairs_month (models/metrics/on_site_repairs/on_site_repairs_month.sql)
  'dict object' has no attribute 'nodes'
  
  > in macro get_metric_sql (macros/get_metric_sql.sql)
  > called by macro default__calculate (macros/calculate.sql)
  > called by macro calculate (macros/calculate.sql)
  > called by macro get_model_relation (macros/graph_parsing/get_model_relation.sql)
  > called by model on_site_repairs_month (models/metrics/on_site_repairs/on_site_repairs_month.sql)
WARNING    Skipped file /Users/jorisvanraaij/Documents/Data/GIT/dbt_reporting/models/metrics/on_site_repairs/on_site_repairs_month.sql because dbt raised a fatal exception during compilation: Compilation Error in model on_site_repairs_month (models/metrics/on_site_repairs/on_site_repairs_month.sql)
  'dict object' has no attribute 'nodes'
  
  > in macro get_metric_sql (macros/get_metric_sql.sql)
  > called by macro default__calculate (macros/calculate.sql)
  > called by macro calculate (macros/calculate.sql)
  > called by macro get_model_relation (macros/graph_parsing/get_model_relation.sql)
  > called by model on_site_repairs_month (models/metrics/on_site_repairs/on_site_repairs_month.sql) 
All Finished 📜 🎉!
```

### Dialect

Redshift

### Version

sqlfluff, version 1.3.0
Python 3.8.10
sqlfluff-templater-dbt   1.3.0

dbt packages
```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.6
  - package: calogica/dbt_date
    version: 0.5.0
  - package: dbt-labs/metrics
    version: 0.3.1
```

### Configuration

```
[sqlfluff]
templater = dbt
dialect = redshift
rules = L014, L058, L042, L043, L035, L010, L006, L001, L019, L005, L008, L011, L012, L018, L017, L023, L039, L041, L046, L048, L049, L036, L002, L003
#rules = L003

[sqlfluff:rules]
indent_unit = space
tab_space_sice = 4

[sqlfluff:rules:L014]
# Capitalisation of unquoted identifiers.
extended_capitalisation_policy = lower

[sqlfluff:rules:L010]
# Keywords
capitalisation_policy = upper

[sqlfluff:rules:L019]
# Comma style
comma_style = trailing

[sqlfluff:rules:L042]
# Join/From clauses should not contain subqueries. Use CTEs instead.
forbid_subquery_in = both
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
@joris-swapfiets - this is an interesting bug in that the tracelog is almost all non-sqlfluff libraries.

Could you confirm a few things:
1. What results do you get if you run `dbt compile` on the same file (i.e. try to apply the operation that is crashing no using sqlfluff), does it succeed, and importantly, what does the compiled version of the file look like?
2. Can you confirm that there isn't a version drift between the version of `dbt` that `sqlfluff` is finding and the version of `dbt` that you get on the command line. You should be able to get that by calling `dbt --version` and `sqlfluff version -v`.

**Comment by joris-swapfiets** [comment]
@alanmcruickshank Thanks for your answer!

1. When running `dbt compile -s <model_name>` it compiles successfully to the following .sql file:
```
select *
from -- Need this here, since the actual ref is nested within loops/conditions:
    -- depends on: "dev"."reporting"."dbt_metrics_default_calendar"
    (
with calendar as (
    select * 
    from "dev"."reporting"."dbt_metrics_default_calendar"
            where date_day >= cast('2022-01-01' as date)
            and date_day <= cast('2022-12-31' as date)
)
,on_site_repairs__aggregate as (
        select
            date_month,
                business_unit,
                asset_category_name,
    count(property_to_aggregate)
 as on_site_repairs,
            bool_or(metric_date_day is not null) as has_data
        from (
    select
        cast(completed_on as date) as metric_date_day, -- timestamp field
        "dev"."reporting"."dbt_metrics_default_calendar".date_month as date_month,
        -- ALL DIMENSIONS
            business_unit,
            asset_category_name,
        action_id as property_to_aggregate
    from "dev"."reporting"."actions"
    left join "dev"."reporting"."dbt_metrics_default_calendar"
        on cast(completed_on as date) = date_day
    where 1=1
    -- metric start/end dates also applied here to limit incoming data
        and (
            cast(completed_on as date) >= cast('2022-01-01' as date)
            and cast(completed_on as date) <= cast('2022-12-31' as date)
        )
    -- metric filter clauses...
    and (
            action_type_name = 'value'
             and 
            status_code = 'value'
    )
) as base_query
        group by 
        1,2,3
    )
,on_site_repairs__dims as (
    select distinct
            business_unit,
            asset_category_name
    from on_site_repairs__aggregate
)
,on_site_repairs__spine_time as (
    select
        calendar.date_month
            ,on_site_repairs__dims.business_unit
            ,on_site_repairs__dims.asset_category_name
    from calendar
        cross join on_site_repairs__dims
    group by
        1, 2, 3
)
,on_site_repairs__final as (
    select
        on_site_repairs__spine_time.date_month,
            on_site_repairs__spine_time.business_unit,
            on_site_repairs__spine_time.asset_category_name,
        coalesce(on_site_repairs, 0) as on_site_repairs
        
    from on_site_repairs__spine_time
    left outer join on_site_repairs__aggregate
        using (date_month
                    ,business_unit
                    ,asset_category_name)
)
,secondary_calculations as (
    select *
    from
            on_site_repairs__final
)
        -- single metric without secondary calculations
        select * from on_site_repairs__final
        -- metric where clauses...
) metric_subq
```

2. As for the version drift
`dbt --version` returns: 
```
Core:
  - installed: 1.2.1
  - latest:    1.2.1 - Up to date!

Plugins:
  - redshift: 1.2.1 - Up to date!
  - postgres: 1.2.1 - Up to date!
 ```
`sqlfluff version -v` returns: 
```
==== sqlfluff ====
sqlfluff:                1.3.0 python:                 3.8.10
implementation:        cpython verbosity:                   1
dialect:              redshift templater:                 dbt
dbt:                    =1.2.1
rules:      L014, L058, L042, L043, L035,
            L010, L006, L001, L019, L005,
            L008, L011, L012, L018, L017,
            L023, L039, L041, L046, L048,
                   L049, L036, L002, L003
```

**Comment by davajm** [comment]
I think I might be experiencing the same _underlying_ issue. It looks to me that this is due to the dbt context variable [graph](https://docs.getdbt.com/reference/dbt-jinja-functions/graph).

We have a model that traverses the graph using a for loop that's throwing the same error. Here's a (minimal) reproducible example:

File `models/model.sql`
```
{{ graph.nodes.values() }}
```

`sqlfluff lint /models/model.sql`
```
=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
ERROR      Fatal dbt compilation error on /models/model.sql. This occurs most often during incorrect sorting of ephemeral models before linting. Please report this error on github at https://github.com/sqlfluff/sqlfluff/issues, including both the raw and compiled sql for the model affected.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 494, in catch_jinja
    yield
  File "/usr/local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 526, in render_template
    return template.render(ctx)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.10/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line -1, in top-level template code
  File "/usr/local/lib/python3.10/site-packages/jinja2/sandbox.py", line 407, in getattr
    value = getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'nodes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlfluff_templater_dbt/templater.py", line 480, in _unsafe_process
    node = self.dbt_compiler.compile_node(
  File "/usr/local/lib/python3.10/site-packages/dbt/compilation.py", line 515, in compile_node
    node = self._compile_node(node, manifest, extra_context)
  File "/usr/local/lib/python3.10/site-packages/dbt/compilation.py", line 374, in _compile_node
    compiled_node.compiled_sql = jinja.get_rendered(
  File "/usr/local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 571, in get_rendered
    return render_template(template, ctx, node)
  File "/usr/local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 525, in render_template
    with catch_jinja(node):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 499, in catch_jinja
    raise UndefinedMacroException(str(e), node) from e
dbt.exceptions.UndefinedMacroException: Compilation Error in model orphan_table (models/monitor/orphan_table.sql)
  'dict object' has no attribute 'nodes'. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
WARNING    Skipped file /models/model.sql because dbt raised a fatal exception during compilation: Compilation Error in model orphan_table (models/monitor/orphan_table.sql)
  'dict object' has no attribute 'nodes'. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
All Finished 📜 🎉!
```

Running `dbt compile --select model` works just fine.
