### ISSUE TITLE
ImportError after installing 1.3.1

### ISSUE THREAD

**Issue by clausherther** [sqlfluff/sqlfluff#3876]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Hi, I just upgraded to `1.3.1` via `pip install -U sqlfluff` and now I’m getting this error when I run _any_ `sqlfluff` command:
```
ImportError: cannot import name 'SQLTemplaterSkipFile' from 'sqlfluff.core.errors'
```

I don’t get the error when I downgrade to 1.3.0 (`pip install -U sqlfluff==1.3.0`).

### Expected Behaviour

I expect to see the regular usage help screen when typing `sqlfluff`.
```
Usage: sqlfluff [OPTIONS] COMMAND [ARGS]...

  SQLFluff is a modular SQL linter for humans.
...
```

### Observed Behaviour

I get this error:
```
sqlfluff
```
```
Traceback (most recent call last):
  File "/Users/claus/.pyenv/versions/dbt/bin/sqlfluff", line 5, in <module>
    from sqlfluff.cli.commands import cli
  File "/Users/claus/.pyenv/versions/3.9.9/envs/dbt/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 516, in <module>
    def lint(
  File "/Users/claus/.pyenv/versions/3.9.9/envs/dbt/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 230, in core_options
    get_plugin_manager().hook.get_templaters()
  File "/Users/claus/.pyenv/versions/3.9.9/envs/dbt/lib/python3.9/site-packages/sqlfluff/core/plugin/host.py", line 12, in get_plugin_manager
    pm.load_setuptools_entrypoints(project_name)
  File "/Users/claus/.pyenv/versions/3.9.9/envs/dbt/lib/python3.9/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/Users/claus/.pyenv/versions/3.9.9/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/claus/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/claus/.pyenv/versions/3.9.9/envs/dbt/lib/python3.9/site-packages/sqlfluff_templater_dbt/__init__.py", line 3, in <module>
    from sqlfluff_templater_dbt.templater import DbtTemplater
  File "/Users/claus/.pyenv/versions/3.9.9/envs/dbt/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 26, in <module>
    from sqlfluff.core.errors import SQLTemplaterError, SQLTemplaterSkipFile
ImportError: cannot import name 'SQLTemplaterSkipFile' from 'sqlfluff.core.errors' (/Users/claus/.pyenv/versions/3.9.9/envs/dbt/lib/python3.9/site-packages/sqlfluff/core/errors.py)
```

### How to reproduce

Run any `sqlfluff` command after installing 1.3.1.

### Dialect

bigquery

### Version

`1.3.1`

Python 3.9.9

### Configuration

I think this is irrelevant in this case, but

```
[sqlfluff]
verbose = 1
nocolor = False
dialect = bigquery
templater = dbt
rules = None
exclude_rules = L022, L003
recurse = 0
output_line_length = 100

[sqlfluff:templater:dbt]

[sqlfluff:indentation]
indented_joins = True

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 100
indent_unit = space

[sqlfluff:rules:L010]
capitalisation_policy = lower

[sqlfluff:rules:L011]
aliasing = explicit

[sqlfluff:rules:L019]
comma_style = trailing
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
Please try updating your version of `sqlfluff-templater-dbt`. I think you have an older, incompatible version installed.

**Comment by clausherther** [comment]
@barrywhart that worked, thanks! (Is that not a dependency of `sqlfluff`?)

**Comment by barrywhart** [comment]
No, it's the opposite -- the templater depends on SQLFluff. More recent versions pin the dependent version so they must be upgraded together, but I'm guessing you had an older version before this was added.
