### ISSUE TITLE
DBT Sorting node failure - dbt.exceptions.InvalidConnectionException

### ISSUE THREAD

**Issue by reidwil** [sqlfluff/sqlfluff#3920]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When running sqlfluff via github actions, we consistently get a failure prior to actual linting.

Note: SQLFluff has successfully linted out code within our CI system in the past.

### Expected Behaviour

To lint our files without raising this exception.

### Observed Behaviour

```
2022-10-05T17:33:48.9431434Z ERROR      Fatal dbt compilation error on /github/workspace/models/my_sick_model1.sql. This occurs most often during incorrect sorting of ephemeral models before linting. Please report this error on github at https://github.com/sqlfluff/sqlfluff/issues, including both the raw and compiled sql for the model affected. 
2022-10-05T17:33:48.9434472Z Traceback (most recent call last):
2022-10-05T17:33:48.9436605Z   File "/usr/local/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 464, in _unsafe_process
2022-10-05T17:33:48.9438094Z     node = self.dbt_compiler.compile_node(
2022-10-05T17:33:48.9439765Z   File "/usr/local/lib/python3.9/site-packages/dbt/compilation.py", line 515, in compile_node
2022-10-05T17:33:48.9441399Z     node = self._compile_node(node, manifest, extra_context)
2022-10-05T17:33:48.9443131Z   File "/usr/local/lib/python3.9/site-packages/dbt/compilation.py", line 374, in _compile_node
2022-10-05T17:33:48.9444535Z     compiled_node.compiled_sql = jinja.get_rendered(
2022-10-05T17:33:48.9446244Z   File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 571, in get_rendered
2022-10-05T17:33:48.9447558Z     return render_template(template, ctx, node)
2022-10-05T17:33:48.9449175Z   File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 526, in render_template
2022-10-05T17:33:48.9450686Z     return template.render(ctx)
2022-10-05T17:33:48.9452276Z   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
2022-10-05T17:33:48.9453694Z     self.environment.handle_exception()
2022-10-05T17:33:48.9455598Z   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
2022-10-05T17:33:48.9457031Z     reraise(*rewrite_traceback_stack(source=source))
2022-10-05T17:33:48.9458609Z   File "/usr/local/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
2022-10-05T17:33:48.9459773Z     raise value.with_traceback(tb)
2022-10-05T17:33:48.9461016Z   File "<template>", line 15, in top-level template code
2022-10-05T17:33:48.9462536Z   File "/usr/local/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
2022-10-05T17:33:48.9463759Z     return __context.call(__obj, *args, **kwargs)
2022-10-05T17:33:48.9465289Z   File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 321, in __call__
2022-10-05T17:33:48.9466679Z     return self.call_macro(*args, **kwargs)
2022-10-05T17:33:48.9468175Z   File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 248, in call_macro
2022-10-05T17:33:48.9469364Z     return macro(*args, **kwargs)
2022-10-05T17:33:48.9470802Z   File "/usr/local/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
2022-10-05T17:33:48.9471950Z     rv = self._func(*arguments)
2022-10-05T17:33:48.9472767Z   File "<template>", line 15, in template
2022-10-05T17:33:48.9474224Z   File "/usr/local/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
2022-10-05T17:33:48.9475439Z     return __context.call(__obj, *args, **kwargs)
2022-10-05T17:33:48.9476962Z   File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 321, in __call__
2022-10-05T17:33:48.9478163Z     return self.call_macro(*args, **kwargs)
2022-10-05T17:33:48.9479683Z   File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 248, in call_macro
2022-10-05T17:33:48.9480832Z     return macro(*args, **kwargs)
2022-10-05T17:33:48.9482267Z   File "/usr/local/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
2022-10-05T17:33:48.9483421Z     rv = self._func(*arguments)
2022-10-05T17:33:48.9484247Z   File "<template>", line 2, in template
2022-10-05T17:33:48.9485710Z   File "/usr/local/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
2022-10-05T17:33:48.9486929Z     return __context.call(__obj, *args, **kwargs)
2022-10-05T17:33:48.9488479Z   File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 321, in __call__
2022-10-05T17:33:48.9489813Z     return self.call_macro(*args, **kwargs)
2022-10-05T17:33:48.9491349Z   File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 248, in call_macro
2022-10-05T17:33:48.9492482Z     return macro(*args, **kwargs)
2022-10-05T17:33:48.9493883Z   File "/usr/local/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
2022-10-05T17:33:48.9495102Z     rv = self._func(*arguments)
2022-10-05T17:33:48.9495933Z   File "<template>", line 10, in template
2022-10-05T17:33:48.9497398Z   File "/usr/local/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
2022-10-05T17:33:48.9498640Z     return __context.call(__obj, *args, **kwargs)
2022-10-05T17:33:48.9500363Z   File "/usr/local/lib/python3.9/site-packages/dbt/adapters/base/impl.py", line 242, in execute
2022-10-05T17:33:48.9502001Z     return self.connections.execute(sql=sql, auto_begin=auto_begin, fetch=fetch)
2022-10-05T17:33:48.9504150Z   File "/usr/local/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 441, in execute
2022-10-05T17:33:48.9505551Z     _, cursor = self.add_query(sql, auto_begin)
2022-10-05T17:33:48.9507246Z   File "/usr/local/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 492, in add_query
2022-10-05T17:33:48.9508651Z     connection, cursor = super().add_query(
2022-10-05T17:33:48.9510284Z   File "/usr/local/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 55, in add_query
2022-10-05T17:33:48.9511671Z     connection = self.get_thread_connection()
2022-10-05T17:33:48.9513494Z   File "/usr/local/lib/python3.9/site-packages/dbt/adapters/base/connections.py", line 91, in get_thread_connection
2022-10-05T17:33:48.9515851Z     raise dbt.exceptions.InvalidConnectionException(key, list(self.thread_connections))
2022-10-05T17:33:48.9517967Z dbt.exceptions.InvalidConnectionException: Runtime Error
2022-10-05T17:33:48.9518885Z   connection never acquired for thread (123, 140482846660352), have [(123, 140482836170496), (123, 140482192320256)]
2022-10-05T17:33:48.9519856Z WARNING    Skipped file /github/workspace/models/espnplus/snapchat/espnplus_snapchat_agg.sql because dbt raised a fatal exception during compilation: Runtime Error
2022-10-05T17:33:48.9520812Z   connection never acquired for thread (123, 140482846660352), have [(123, 140482836170496), (123, 140482192320256)] 
```

### How to reproduce

Because this is in a CI context and not reproducible locally, here is the github action needed to run:
```yaml
    steps:
      - name: Clean workspace
        run: rm -rf * .* || true
      - uses: actions/checkout@v2
      - name: Sqlfluff lint
        uses: yu-iskw/action-sqlfluff@v3
        id: lint-sql
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          sqlfluff_version: "1.2.1"
          sqlfluff_command: "fix" # Or "lint"
          config: "${{ github.workspace }}/.sqlfluff"
          paths: '${{ github.workspace }}/models'
          extra_requirements_txt: './requirements/requirements_gha.txt'
```

### Dialect

dialect=snowflake
templater=dbt

### Version

```
dbt-core                   1.2.2
dbt-snowflake              1.2.0
sqlfluff                   1.2.1
sqlfluff-templater-dbt     1.2.1
python                     3.9
```

### Configuration

`.sqlfluff` 
```
[sqlfluff:core]
templater = dbt
dialect = snowflake
ignore = parsing
# L031 - weird table aliasing rule
# L032 - allow 'using', rather than "sqlfluff fix" changing to 'on' clause
# L034 - the order of elements in the select clause
# The reason is that it will change the order and effect the insert statement
# https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.core.rules.Rule_L034
exclude_rules = L009, L031, L032, L034

[sqlfluff:rules]
comma_style = trailing

[sqlfluff:rules:L016]
max_line_length = 300

[sqlfluff:rules:L010]
# Keywords
capitalisation_policy = upper

[sqlfluff:rules:L014]
# Keywords
extended_capitalisation_policy = lower

[sqlfluff:rules:L030]
# functions
extended_capitalisation_policy = upper

[sqlfluff:rules:L040]
# booleans and null
capitalisation_policy = upper

[sqlfluff:rules:L063]
# datatypes
extended_capitalisation_policy = upper

[sqlfluff:templater:dbt]
project_dir = ./
profiles_dir = ./
target = dev

[sqlfluff:templater:jinja]
apply_dbt_builtins = true
```
`.sqlfluffignore`
```
target/
dbt_modules/
dbt_packages/
macros/
models/dimensions/
models/facts/
```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
This looks very likely to be a `dbt` issue rather than a sqlfluff one - but I'm not sure the best way to confirm that within the context of a github action. Are you able to run `dbt compile` directly in the same context?

**Comment by alanmcruickshank** [comment]
I'm going to close this as as dbt issue not a sqlfluff issue - and without a good way to recreate the issue.
