### ISSUE TITLE
[L011] throws exception

### ISSUE THREAD

**Issue by lucianmoldovanu** [sqlfluff/sqlfluff#4089]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

sqlfluff fix models/core/test.sql --dialect snowflake

==== finding fixable violations ====
**CRITICAL   [L011] Applying rule L011 threw an Exception: 'NoneType' object has no attribute 'working_line_pos'**                                                             
Traceback (most recent call last):
  File "/home/lucian/.local/lib/python3.8/site-packages/sqlfluff/core/rules/base.py", line 512, in crawl
    res = self._eval(context=context)
  File "/home/lucian/.local/lib/python3.8/site-packages/sqlfluff/rules/L011.py", line 92, in _eval
    fixes=ReflowSequence.from_around_target(
  File "/home/lucian/.local/lib/python3.8/site-packages/sqlfluff/utils/reflow/sequence.py", line 504, in respace
    new_fixes, new_point = point.respace_point(
  File "/home/lucian/.local/lib/python3.8/site-packages/sqlfluff/utils/reflow/elements.py", line 347, in respace_point
    segment_buffer, delta_fixes = handle_respace__inline_with_space(
  File "/home/lucian/.local/lib/python3.8/site-packages/sqlfluff/utils/reflow/respace.py", line 270, in handle_respace__inline_with_space
    next_block.segments[0].pos_marker.working_line_pos,
AttributeError: 'NoneType' object has no attribute 'working_line_pos'
== [models/core/test.sql] FAIL                                                                                                                                             
L:   2 | P:   5 | L036 | Select targets should be on a new line unless there is
                       | only one select target.
L:   4 | P:  12 | L031 | Avoid aliases in from clauses and join conditions.
L:   5 | P:   5 | L003 | Expected 2 indentations, found 1 [compared to line 04]
L:   5 | P:  17 | L031 | Avoid aliases in from clauses and join conditions.
L:   6 | P:   5 | L003 | Expected 2 indentations, found 1 [compared to line 04]
L:   6 | P:  17 | L031 | Avoid aliases in from clauses and join conditions.
L:   6 | P:  81 | L016 | Line is too long.
==== fixing violations ====
7 fixable linting violations found

### Expected Behaviour

identification of linting deviations, proposal to fix

no code exceptions

### Observed Behaviour

Confirming the fix seems to work correctly. When you run again afterwards, there are no more lint suggestions (as expected) and no exceptions thrown either.

### How to reproduce

test.sql:
```
with compute_sessions as (
    select *
    from a
        left join b on a.project_id = b.id
        left join
            c on a.project_id = c.project_id and a.branch_id = c.id
)

select * from compute_sessions
```

### Dialect

snowflake

### Version

1.4.2

### Configuration

[sqlfluff:layout:type:alias_expression]
# We want non-default spacing _before_ the alias expressions.
spacing_before = align

# We want to align them within the next outer select clause.
# This means for example that alias expressions within the FROM
# or JOIN clause would _not_ be aligned with them.
align_within = select_clause

# The point at which to stop searching outward for siblings, which
# in this example would likely be the boundary of a CTE. Stopping
# when we hit brackets is usually a good rule of thumb for this
# configuration.
align_scope = bracketed

[sqlfluff:indentation]
indented_joins = True
tab_space_size = 2

# indented_on_contents = False

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by philip-ct** [comment]
Is there an update on this issue? I'm also receiving this

**Comment by philip-ct** [comment]
Update, unfortunately the above no longer works for me, also I'm getting these errors for both of L011 and L012

**Comment by schuppo** [comment]
I am having the same issue.

It only occurs when following configuration is set:

```ini
[sqlfluff:layout:type:alias_expression]
spacing_before = align
```

After removing this setting it does not appear any more.

I am adding a rather small query that could help to reproduce the error:

```sql
SELECT
RANK() OVER (PARTITION BY Id ORDER BY Id DESC) nr_rank
FROM (values ('Amsterdam', 1), ('London', 2)) Cities(Name, Id)
```

This query is valid and can be run using for example duckdb. But when trying to lint the file containing the query an exception is raised saying `AttributeError: 'NoneType' object has no attribute 'working_line_pos'`.

I was using sqlfluff version 1.4.5 when linting the statement.
