### ISSUE TITLE
Unable to lint two files from the command line

### ISSUE THREAD

**Issue by gnilrets** [sqlfluff/sqlfluff#4093]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I'm trying to lint multiple files from the command line:
```bash
sqlfluff lint models/staging/lgen/base/base_lgen_field_events__events_normalized.sql models/staging/lgen/base/base_lgen_lab_events__events_normalized.sql
```

The first one runs through just fine, but on the second one I get an error that "Skipped file /opt/eta-wh/dbt/models/staging/lgen/base/base_lgen_lab_events__events_normalized.sql because dbt raised a fatal exception during compilation: Runtime Error  connection never acquired for thread":
```
root@268b29d50346:/opt/eta-wh/dbt# sqlfluff lint models/staging/lgen/base/base_lgen_field_events__events_normalized.sql models/staging/lgen/base/base_lgen_lab_events__events_normalized.sql
==== sqlfluff ====
sqlfluff:                1.4.2 python:                 3.9.15
implementation:        cpython verbosity:                   1
dialect:             snowflake templater:                 dbt
dbt:                    =1.3.0
rules:                                all
==== readout ====

=== [ path: models/staging/lgen/base/base_lgen_field_events__events_normalized.sql ] ===

effective configured processes:  4
=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
path models/staging/lgen/base/base_lgen_field_events__events_normalized.sql:   0%|                                                                                                                                            | 0/2 [00:00<?, ?it/s]
rule L036:  43%|████████████████████████████████████████████████���███████████████████████████████████                                                                                                               | 28/65 [00:00<00:00, 277.20it/rule L039:  43%|████████████████████████████████████████████████���███████████████████████████████████                                                                                                               | 28/65 [00:00<00:00, 277.20it/rule L050:  43%|████████████████████████████████████████████████���███████████████████████████████████                                                                                                               | 28/65 [00:00<00:00, 277.20it/rule L055:  43%|██████████████████���█████████████████████████████████████████████████████████████████                                                                                                               | 28/65 [00:00<00:00, 277.20it/rule L063:  94%|███████████████████████████████��███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████            | 61/65 [00:00<00:00, 307.44it/s== [models/staging/lgen/base/base_lgen_field_events__events_normalized.sql] PASS                                                                                                                                                                    === [ path: models/staging/lgen/base/base_lgen_lab_events__events_normalized.sql ] ===

effective configured processes:  4
=== [dbt templater] Sorting Nodes...
ERROR      Fatal dbt compilation error on /opt/eta-wh/dbt/models/staging/lgen/base/base_lgen_lab_events__events_normalized.sql. This occurs most often during incorrect sorting of ephemeral models before linting. Please report this error on github at https://github.com/sqlfluff/sqlfluff/issues, including both the raw and compiled sql for the model affected.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 481, in _unsafe_process
    node = self.dbt_compiler.compile_node(
  File "/usr/local/lib/python3.9/site-packages/dbt/compilation.py", line 535, in compile_node
    node = self._compile_node(node, manifest, extra_context)
  File "/usr/local/lib/python3.9/site-packages/dbt/compilation.py", line 394, in _compile_node
    compiled_node.compiled_code = jinja.get_rendered(
  File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 587, in get_rendered
    return render_template(template, ctx, node)
  File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 542, in render_template
    return template.render(ctx)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.9/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 326, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 253, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 3, in template
  File "/usr/local/lib/python3.9/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 326, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 253, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 17, in template
  File "/usr/local/lib/python3.9/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dbt/adapters/snowflake/impl.py", line 103, in get_columns_in_relation
    return super().get_columns_in_relation(relation)
  File "/usr/local/lib/python3.9/site-packages/dbt/adapters/sql/impl.py", line 152, in get_columns_in_relation
    return self.execute_macro(
  File "/usr/local/lib/python3.9/site-packages/dbt/adapters/base/impl.py", line 1026, in execute_macro
    result = macro_function(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 326, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 253, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 2, in template
  File "/usr/local/lib/python3.9/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 326, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 253, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 5, in template
  File "/usr/local/lib/python3.9/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 326, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 253, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 2, in template
  File "/usr/local/lib/python3.9/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 326, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dbt/clients/jinja.py", line 253, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 11, in template
  File "/usr/local/lib/python3.9/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dbt/adapters/base/impl.py", line 278, in execute
    return self.connections.execute(sql=sql, auto_begin=auto_begin, fetch=fetch)
  File "/usr/local/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 407, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 458, in add_query
    connection, cursor = super().add_query(
  File "/usr/local/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 55, in add_query
    connection = self.get_thread_connection()
  File "/usr/local/lib/python3.9/site-packages/dbt/adapters/base/connections.py", line 91, in get_thread_connection
    raise dbt.exceptions.InvalidConnectionException(key, list(self.thread_connections))
dbt.exceptions.InvalidConnectionException: Runtime Error
  connection never acquired for thread (2517, 281473253634528), have [(2517, 281473262027232), (2517, 281472823980512), (2517, 281472815587808), (2517, 281472807195104), (2517, 281472798802400)]
path models/staging/lgen/base/base_lgen_lab_events__events_normalized.sql:  50%|███████████████████���███████████████████████████████████████████████                                                                   | 1/2 [00:03<00:03,  3.84s/iWARNING    Skipped file /opt/eta-wh/dbt/models/staging/lgen/base/base_lgen_lab_events__events_normalized.sql because dbt raised a fatal exception during compilation: Runtime Error
  connection never acquired for thread (2517, 281473253634528), have [(2517, 281473262027232), (2517, 281472823980512), (2517, 281472815587808), (2517, 281472807195104), (2517, 281472798802400)]
== [models/staging/lgen/base/base_lgen_lab_events__events_normalized.sql] PASS
==== summary ====
violations:        0 status:         PASS
All Finished 📜 🎉!
root@268b29d50346:/opt/eta-wh/dbt# sqlfluff lint models/staging/lgen/base/base_lgen_field_events__events_normalized.sql,models/staging/lgen/base/base_lgen_lab_events__events_normalized.sql
==== sqlfluff ====
sqlfluff:                1.4.2 python:                 3.9.15
implementation:        cpython verbosity:                   1
dialect:             snowflake templater:                 dbt
dbt:                    =1.3.0
rules:                                all
==== readout ====

=== [ path: models/staging/lgen/base/base_lgen_field_events__events_normalized.sql,models/staging/lgen/base/base_lgen_lab_events__events_normalized.sql ] ===


User Error: Specified path does not exist. Check it/they exist(s): models/staging/lgen/base/base_lgen_field_events__events_normalized.sql,models/staging/lgen/base/base_lgen_lab_events__events_normalized.sql.
```

### Expected Behaviour

I would expect no error.

### Observed Behaviour

There is an error.

### How to reproduce

Not clear, but it's easily reproducible on my system.

### Dialect

snowflake dialect and the dbt templater

### Version

sqlfluff, version 1.4.2

### Configuration
```
[sqlfluff]
verbose = 1
dialect = snowflake
templater = dbt
# templater = jinja
processes = 4

# L034 - Select wildcards then simple targets before calculations and aggregates.
exclude_rules = L034

# Some rules can be configured directly from the config common to other rules
[sqlfluff:rules]
max_line_length = 110

[sqlfluff:rules:L010]
capitalisation_policy = lower
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
I tested using SQLFluff's sample dbt project, and didn't get the error. From the `plugins/sqlfluff-templater-dbt/test/fixtures/dbt/` directory, I ran:
```
sqlfluff lint ./dbt_project/models/my_new_project/use_var.sql ./dbt_project/models/my_new_project/L034_test.sql
```

Please provide more information how to reproduce so we can investigate the issue.

**Comment by gnilrets** [comment]
I am unable to run those commands in this project because it's not clear how I can set things to match your environment (I tried, but dbt was not configured for this project, templater wasn't installed, etc).  Can you provide some guidance around how to set up a sqlfluff development environment so I can try to reproduce your result?

**Comment by barrywhart** [comment]
Does it still fail for you with the latest release (1.4.5)?

Would it actually be useful for you to reproduce my successful outcome? Do you know how to use Docker? (I ask because you'll need Docker in order to run the command I mentioned.)

**Comment by gnilrets** [comment]
This was on 1.4.2.  Yes, I can use Docker.

**Comment by barrywhart** [comment]
This is what I did. I retested it today on the latest code in `main`.

```
plugins/sqlfluff-templater-dbt/docker/startup
plugins/sqlfluff-templater-dbt/docker/shell
cd plugins/sqlfluff-templater-dbt/test/fixtures/dbt/
<<In the file plugins/sqlfluff-templater-dbt/test/fixtures/dbt.sqlfluff, change the profiles_dir setting to: profiles_dir = profiles_yml
pushd dbt_project
dbt deps
popd
sqlfluff lint ./dbt_project/models/my_new_project/use_var.sql ./dbt_project/models/my_new_project/L034_test.sql
```

**Comment by alanmcruickshank** [comment]
I'm going to close this issue as stale. I believe it's resolved, and I know that several setups ([like this one](https://github.com/sqlfluff/sqlfluff-github-actions/tree/main/menu_of_workflows/tails.com)) use the same functionality, so I'm fairly confident that it's working for most users.

If there's a more specific bug here I suggest we start a new issue.
