### ISSUE TITLE
TSQL L019 throws exception.  Spacing issue?

### ISSUE THREAD

**Issue by jpers36** [sqlfluff/sqlfluff#4255]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Running sqlfluff lint for rule L019 on the following TSQL code causes an exception to be thrown.
```
select B
	  ,C
from A

```

### Expected Behaviour

Expected the linter to complete without an exception

### Observed Behaviour

The exception:

```
CRITICAL   [L019] Applying rule L019 threw an Exception:
Traceback (most recent call last):
  File "C:\Users\JPersons\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlfluff\core\rules\base.py", line 512, in crawl
    res = self._eval(context=context)
  File "C:\Users\JPersons\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlfluff\rules\L019.py", line 79, in _eval
    .rebreak()
  File "C:\Users\JPersons\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlfluff\utils\reflow\sequence.py", line 540, in rebreak
    elem_buff, lint_results = rebreak_sequence(self.elements, self.root_segment)
  File "C:\Users\JPersons\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlfluff\utils\reflow\rebreak.py", line 381, in rebreak_sequence
    new_results, next_point = next_point.indent_to(
  File "C:\Users\JPersons\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlfluff\utils\reflow\elements.py", line 303, in indent_to
    f"{_indent_description(desired_indent)} "
  File "C:\Users\JPersons\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlfluff\utils\reflow\elements.py", line 143, in _indent_description
    assert all(c == "\t" for c in indent)
AssertionError
== [C:\Users\JPersons\OneDrive - Quisitive\Documents\SQLFluffTest.sql] FAIL
L:   2 | P:   4 | L019 | Unexpected exception: ;
Could you open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ?
You can
                       | ignore this exception for now, by adding '-- noqa: L019'
                       | at the end
of line 2

All Finished 📜 🎉!

```

### How to reproduce

```
sqlfluff lint --rules=L019 --dialect=tsql <PATH>
```

### Dialect

TSQL

### Version

1.4.5

### Configuration

none

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by pdebelak** [comment]
It seems like it might be having an issue with the mixed tabs and spaces for some reason, but I don't get the same error locally. Do you have a customized config at all?

**Comment by jpers36** [comment]
@pdebelak I'm getting the error without any custom config.

File encoding is UTF-8, if that makes a difference.

**Comment by alanmcruickshank** [comment]
I'm able to recreate the issue. It's still present on `main` as of now. It's definitely linked to the mixed indent, but we should be able to handle that without an error. Working on a fix now.
