### ISSUE TITLE
CompilationException error in command line after dbt-core 1.4.0 update

### ISSUE THREAD

**Issue by jussapaavo** [sqlfluff/sqlfluff#4315]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I tried to setup sqlfluff from a fresh installation, but I couldn't get it to work. I researched it further, and it seems like bad luck, since `dbt-core` just released a new version, where they [had renamed a part of their file](https://github.com/dbt-labs/dbt-core/commit/eb200b46877c31469f410b7d47dfd245473ed7cb) that sqlfluff is importing and it's resulting in an error.

Here's my error message:
```
Traceback (most recent call last):
  File "/Users/user/.local/bin/sqlfluff", line 5, in <module>
    from sqlfluff.cli.commands import cli
  File "/Users/user/.local/pipx/venvs/sqlfluff/lib/python3.10/site-packages/sqlfluff/cli/commands.py", line 518, in <module>
    def lint(
  File "/Users/user/.local/pipx/venvs/sqlfluff/lib/python3.10/site-packages/sqlfluff/cli/commands.py", line 218, in core_options
    get_plugin_manager().hook.get_templaters()
  File "/Users/user/.local/pipx/venvs/sqlfluff/lib/python3.10/site-packages/sqlfluff/core/plugin/host.py", line 12, in get_plugin_manager
    pm.load_setuptools_entrypoints(project_name)
  File "/Users/user/.local/pipx/venvs/sqlfluff/lib/python3.10/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/user/.local/pipx/venvs/sqlfluff/lib/python3.10/site-packages/sqlfluff_templater_dbt/__init__.py", line 3, in <module>
    from sqlfluff_templater_dbt.templater import DbtTemplater
  File "/Users/user/.local/pipx/venvs/sqlfluff/lib/python3.10/site-packages/sqlfluff_templater_dbt/templater.py", line 17, in <module>
    from dbt.exceptions import (
ImportError: cannot import name 'CompilationException' from 'dbt.exceptions' (/Users/user/.local/pipx/venvs/sqlfluff/lib/python3.10/site-packages/dbt/exceptions.py)
```

I tried to Google the `cannot import name 'CompilationException' from 'dbt.exceptions'` part, but couldn't find anything relevant. Then I looked further into the error message and found my way into `dbt-core` repository and couldn't find the `CompilationException` from anywhere. It's been renamed in a very recent commit which was released freshly in `1.4.0`.

### Expected Behaviour

Run `sqlfluff lint ./` in shell without Python errors.

### Observed Behaviour

Recieved Python errors and couldn't access intended functionalities.

### How to reproduce

Update dbt-core, run sqlfluff.

### Dialect

athena

### Version

`sqlfluff --version` is not working either.

### Configuration

[sqlfluff]
dialect = athena
templater = jinja
exclude_rules = L026, L031

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 120

[sqlfluff:layout:type:alias_expression]  # Align column aliases in SELECT clauses
spacing_before = align
align_within = select_clause
align_scope = bracketed

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by Caspar0-0** [comment]
I had a similar error message with a ticket : https://github.com/sqlfluff/sqlfluff/issues/4318 thanks above and pls help us!
