### ISSUE TITLE
sqlfluff not starting on dbt-core version 1.4.1

### ISSUE THREAD

**Issue by adrian-damaschin** [sqlfluff/sqlfluff#4332]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

We upgraded our dbt-core from vs 1.3.2 to vs 1.4.1 while using the same version for sqlfluff - latest 1.4.5.

We are using python 3.9.12 on poetry 1.2.1

### Expected Behaviour

Sql fluff running as usual

### Observed Behaviour

After the upgrade we are unable to start sql fluff run with the following error.

`Linting using SQLFluff dbt project at /home/runner/work/path_to_project
Traceback (most recent call last):
  File "/home/runner/work/path_to_project", line 5, in <module>
    from sqlfluff.cli.commands import cli
  File "/home/runner/work/data-platform/data-platform/.venv/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 518, in <module>
    def lint(
  File "/home/runner/work/path_to_project/.venv/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 218, in core_options
    get_plugin_manager().hook.get_templaters()
  File "/home/runner/work/path_to_project/.venv/lib/python3.9/site-packages/sqlfluff/core/plugin/host.py", line 12, in get_plugin_manager
    pm.load_setuptools_entrypoints(project_name)
  File "/home/runner/work/path_to_project/.venv/lib/python3.9/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/runner/work/path_to_project/.venv/lib/python3.9/site-packages/sqlfluff_templater_dbt/__init__.py", line 3, in <module>
    from sqlfluff_templater_dbt.templater import DbtTemplater
  File "/home/runner/work/path_to_project/.venv/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 17, in <module>
    from dbt.exceptions import (
ImportError: cannot import name 'CompilationException' from 'dbt.exceptions' (/home/runner/work/path_to_project/.venv/lib/python3.9/site-packages/dbt/exceptions.py)
Error: Process completed with exit code 1.`

### How to reproduce

Github repo cannot be provided as it is private.

The code is ran by a github action on ubuntu and the only thing changed is the dbt-core version.

### Dialect

command ran:
`poetry run sqlfluff lint $dir --logger linter -v`

### Version

1.4.5

### Configuration

[sqlfluff]
verbose = 5
dialect = snowflake
templater = dbt
exclude_rules = L016,L031

[sqlfluff:rules]
tab_space_size = 4

[sqlfluff:rules:L019]
comma_style = leading

[sqlfluff:templater:dbt]
project_dir = ${DEPLOYABLE_TARGET_DBT_PROJECT_DIR}
profiles_dir = .
profile = generic

[tool.sqlfluff.templater.jinja]
apply_dbt_builtins = True

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by pdebelak** [comment]
@adrian-damaschin this is fixed in #4317 which has been released in 2.0.0a4 (hopefully a full 2.0.0 will be released soon-ish).

**Comment by greg-finley** [comment]
Duplicate
