### ISSUE TITLE
ImportError: cannot import name 'CompilationException' from 'dbt.exceptions' for dbt 1.4.1

### ISSUE THREAD

**Issue by geoHeil** [sqlfluff/sqlfluff#4425]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

ImportError: cannot import name 'CompilationException' from 'dbt.exceptions'

### Expected Behaviour

no exception should be thrown. DBT compatibility for 1.4.1 should be there

### Observed Behaviour

Exception

### How to reproduce

sqlfluff fix

for a dBT project with sqlfluff and dbt 1.4.1

### Dialect

postgres with DBT

### Version

1.4.5

### Configuration

[sqlfluff]
templater = dbt
dialect = postgres
exclude_rules = L059

[sqlfluff:rules]
max_line_length = 130
[sqlfluff:rules:L010]
# Keywordys
capitalisation_policy = upper

[sqlfluff:templater:dbt]

target = my_target

[sqlfluff:templater:jinja]
apply_dbt_builtins = True

[sqlfluff:indentation]
indented_joins = false
indented_using_on = true
template_blocks_indent = false

[sqlfluff:templater]
unwrap_wrapped_queries = true

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by WittierDinosaur** [comment]
This issue has been raised about 15 times - super annoying that dbt change their interface in a minor release. It is fixed on main, we will be releasing a compatible release this week. It'll be 2.0.0a5 (an alpha release, so stable, so i'd encourage upgrading to it).

**Comment by geoHeil** [comment]
Thanks

**Comment by WittierDinosaur** [comment]
Just as an FYI - 2.0.0a5 is out now, and should fix it

**Comment by geoHeil** [comment]
thanks!

**Comment by jakebiesinger-storyhealth** [comment]
@WittierDinosaur seems to not be fixed? Or perhaps not for the even-more-recent `dbt==1.4.4`?

```bash
$ pipenv install dbt-core==1.4.4 dbt-bigquery==1.4.1 sqlfluff==2.0.0a5 sqlfluff-templater-dbt==1.2.0

$ pipenv run sqlfluff

Traceback (most recent call last):
  File "/Users/jakebiesinger/.local/share/virtualenvs/data-warehouse2-oiysC9eq/bin/sqlfluff", line 5, in <module>
    from sqlfluff.cli.commands import cli
  File "/Users/jakebiesinger/.local/share/virtualenvs/data-warehouse2-oiysC9eq/lib/python3.10/site-packages/sqlfluff/cli/commands.py", line 531, in <module>
    def lint(
  File "/Users/jakebiesinger/.local/share/virtualenvs/data-warehouse2-oiysC9eq/lib/python3.10/site-packages/sqlfluff/cli/commands.py", line 218, in core_options
    get_plugin_manager().hook.get_templaters()
  File "/Users/jakebiesinger/.local/share/virtualenvs/data-warehouse2-oiysC9eq/lib/python3.10/site-packages/sqlfluff/core/plugin/host.py", line 12, in get_plugin_manager
    pm.load_setuptools_entrypoints(project_name)
  File "/Users/jakebiesinger/.local/share/virtualenvs/data-warehouse2-oiysC9eq/lib/python3.10/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/jakebiesinger/.local/share/virtualenvs/data-warehouse2-oiysC9eq/lib/python3.10/site-packages/sqlfluff_templater_dbt/__init__.py", line 3, in <module>
    from sqlfluff_templater_dbt.templater import DbtTemplater
  File "/Users/jakebiesinger/.local/share/virtualenvs/data-warehouse2-oiysC9eq/lib/python3.10/site-packages/sqlfluff_templater_dbt/templater.py", line 17, in <module>
    from dbt.exceptions import (
ImportError: cannot import name 'CompilationException' from 'dbt.exceptions' (/Users/jakebiesinger/.local/share/virtualenvs/data-warehouse2-oiysC9eq/lib/python3.10/site-packages/dbt/exceptions.py)
```

The stacktrace sure looks like it belongs to dbt-core :(
