### ISSUE TITLE
ImportError Issue with sqlfluff-templater-dbt

### ISSUE THREAD

**Issue by mzemp** [sqlfluff/sqlfluff#4481]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Installed `sqlfluff 1.4.5` & `sqlfluff-templater-dbt 1.4.5` without issues. Though when running
```
sqlfluff lint models/my_file.sql
```
I get:
```
Traceback (most recent call last):
  File "/Users/mzemp/.venv/wif-dbt/bin/sqlfluff", line 5, in <module>
    from sqlfluff.cli.commands import cli
  File "/Users/mzemp/.venv/wif-dbt/lib/python3.11/site-packages/sqlfluff/cli/commands.py", line 449, in <module>
    @core_options
     ^^^^^^^^^^^^
  File "/Users/mzemp/.venv/wif-dbt/lib/python3.11/site-packages/sqlfluff/cli/commands.py", line 218, in core_options
    get_plugin_manager().hook.get_templaters()
    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mzemp/.venv/wif-dbt/lib/python3.11/site-packages/sqlfluff/core/plugin/host.py", line 12, in get_plugin_manager
    pm.load_setuptools_entrypoints(project_name)
  File "/Users/mzemp/.venv/wif-dbt/lib/python3.11/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
             ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mzemp/.venv/wif-dbt/lib/python3.11/site-packages/sqlfluff_templater_dbt/__init__.py", line 3, in <module>
    from sqlfluff_templater_dbt.templater import DbtTemplater
  File "/Users/mzemp/.venv/wif-dbt/lib/python3.11/site-packages/sqlfluff_templater_dbt/templater.py", line 17, in <module>
    from dbt.exceptions import (
ImportError: cannot import name 'CompilationException' from 'dbt.exceptions' (/Users/mzemp/.venv/wif-dbt/lib/python3.11/site-packages/dbt/exceptions.py)
```

### Expected Behaviour

No import issues.

### Observed Behaviour

Cannot use sqlfluff. I need to uninstall `sqlfluff-templater-dbt` and switch back to `templater = jinja` so that I can use `sqlfluff`.

### How to reproduce

```
pip install sqlfluff sqlfluff-templater-dbt
sqlfluff lint path/to/my_file.sql
```

### Dialect

bigquery

### Version

```
sqlfluff 1.4.5
sqlfluff-templater-dbt 1.4.5
python 3.11.2
```

### Configuration

```
[sqlfluff]
templater = dbt
dialect = bigquery
exclude_rules = L034

[sqlfluff:layout:type:comma]
line_position = leading

[sqlfluff:rules]
indent_unit = tab
tab_space_size = 4

[sqlfluff:rules:L010] # Keywords
capitalisation_policy = upper

[sqlfluff:rules:L014] # Unquoted Identifiers
extended_capitalisation_policy = lower

[sqlfluff:rules:L030] # Function Names
extended_capitalisation_policy = upper

[sqlfluff:rules:L064] # Quotes
preferred_quoted_literal_style = single_quotes

[sqlfluff:templater:dbt]
project_dir = .
profile = <profile>
target = dev
```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by greg-finley** [comment]
https://github.com/sqlfluff/sqlfluff/issues/4457#issuecomment-1453920237
