### ISSUE TITLE
[LT02] Unexpected exception: list index out of range

### ISSUE THREAD

**Issue by simpl1g** [sqlfluff/sqlfluff#4680]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

After upgrading from 2.0.2 to 2.0.3 I'm having this exception

It is only reproduces inside `is_incremental()` branch. If I rename schema or file name for example, it works fine.

### Expected Behaviour

sqlfluff lint -d ansi -t dbt sql # 2.0.2

```
=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
All Finished 📜 🎉!      
```

### Observed Behaviour

sqlfluff lint -d ansi -t dbt sql # 2.0.3

```
=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
CRITICAL   [LT02] Applying rule LT02 to 'models/google_play/staging/stg.sql' threw an Exception: list index out of range                    
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlfluff/core/rules/base.py", line 796, in crawl
    res = self._eval(context=context)
  File "/usr/local/lib/python3.10/site-packages/sqlfluff/rules/layout/LT02.py", line 63, in _eval
    .reindent()
  File "/usr/local/lib/python3.10/site-packages/sqlfluff/utils/reflow/sequence.py", line 578, in reindent
    elements, indent_results = lint_indent_points(
  File "/usr/local/lib/python3.10/site-packages/sqlfluff/utils/reflow/reindent.py", line 1379, in lint_indent_points
    _revise_templated_lines(lines, elements)
  File "/usr/local/lib/python3.10/site-packages/sqlfluff/utils/reflow/reindent.py", line 366, in _revise_templated_lines
    if first_point_idx + 3 == lines[idx + 1].indent_points[0].idx + 1:
IndexError: list index out of range
== [models/google_play/staging/stg.sql] FAIL                                                                                                
L:   1 | P:   1 | LT02 | Unexpected exception: list index out of range;
Could you
                       | open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ?
You can
                       | ignore this exception for now, by adding '-- noqa: LT02'
                       | at the end
of line 1
 [layout.indent]
All Finished 📜 🎉!
```

### How to reproduce

```jinja
{{
  config(
    materialized='incremental',
    schema='dbt',
  )
}}

SELECT col1
FROM table
WHERE
  {% if is_incremental() %}
    col1 > 1
  {% else %}
    col1 > 0
  {% endif %}
```

### Dialect

ansi

### Version

2.0.3

### Configuration

[sqlfluff]
dialect = ansi
templater = dbt

[sqlfluff:indentation]
tab_space_size = 2

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
Confirmed. I also get this issue on this simpler query, using the jinja templater:

```jinja
SELECT col1
FROM table
WHERE
  {% if true %}
    col1 > 1
  {% else %}
    col1 > 0
  {% endif %}
```

**Comment by simpl1g** [comment]
@alanmcruickshank Thank you! Do you know when 2.0.4 is going to be released?

**Comment by simpl1g** [comment]
@alanmcruickshank after upgrading I found new issue https://github.com/sqlfluff/sqlfluff/issues/4791 😃
