### ISSUE TITLE
2.0.3 [LT02] - ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by rapidsiege** [sqlfluff/sqlfluff#4745]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Linting a model that had no errors previous to the 2.0.0 upgrade (before rules were grouped and all had L0XX names) now throws an unexpected ValueError exception. 

```python
CRITICAL   [LT02] Applying rule LT02 to 'path/code_snippet.sql' threw an Exception: max() arg is an empty sequence 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/rules/base.py", line 796, in crawl
    res = self._eval(context=context)
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/rules/layout/LT02.py", line 62, in _eval
    ReflowSequence.from_root(context.segment, context.config)
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/utils/reflow/sequence.py", line 578, in reindent
    elements, indent_results = lint_indent_points(
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/utils/reflow/reindent.py", line 1379, in lint_indent_points
    _revise_templated_lines(lines, elements)
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/utils/reflow/reindent.py", line 498, in _revise_templated_lines
    best_indent = max(overlap)
ValueError: max() arg is an empty sequence
```

### Expected Behaviour

There shouldn't be any critical error.

### Observed Behaviour

Linting the .sql file with jinja code throws the exception. However, compiling the model and linting the compiled version throws no critical issue at all.

### How to reproduce

This snipped of abstract code should replicate the error:

```sql
with data as (
    select
        'A' as company_name,
        'B' as company_location,
),

{% for variable_array in [{"time_aggregation": "X", "cte_order": 1},{"time_aggregation": "Y", "cte_order": 2},{"time_aggregation": "Z", "cte_order": 3}] %}{% for evaluation_metric in ['C', 'D', 'E'] %}

{{ evaluation_metric }}_fill_{{ variable_array.cte_order }} as (
    select
        company_name,
        company_location,
        '{{ evaluation_metric }}' as evaluation_metric,
        '{{ variable_array.time_aggregation }}' as time_aggregation,
        {{ variable_array.cte_order }} as cte_order,
        null as evaluation_value,
    from data
),
{% endfor %}{% endfor %}

union_all_data as (
    {% for variable_array in [{"time_aggregation": "X", "cte_order": 1},{"time_aggregation": "Y", "cte_order": 2},{"time_aggregation": "Z", "cte_order": 3}] %}{% for evaluation_metric in ['C', 'D', 'E'] %}
    select *, from {{ evaluation_metric }}_fill_{{ variable_array.cte_order }}
    {% if not loop.last %}union all{% endif %}{% endfor %}{% if not loop.last %}union all{% endif %}{% endfor %}
)

select *, from union_all_data
```

If you `dbt compile -m code_snippet` it will throw out no exceptions (although it will fail due to a minor LT01 violation)

### Dialect
`
dbt-bigquery
`
### Version
```
sqlfluff = "==2.0.3"
sqlfluff-templater-dbt = "==2.0.3"
```

### Configuration
```
[sqlfluff]
dialect = bigquery
exclude_rules = LT05,RF01,AL07,ST07,ST06,AM06
ignore_templated_areas = True
templater = dbt
large_file_skip_byte_limit = 0

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = lower

[sqlfluff:rules:capitalisation.identifiers]
unquoted_identifiers_policy = column_aliases
extended_capitalisation_policy = lower

[sqlfluff:rules:capitalisation.functions]
capitalisation_policy = lower

[sqlfluff:rules:capitalisation.literals]
capitalisation_policy = lower

[sqlfluff:rules:layout.long_lines]
max_line_length = 150

[sqlfluff:rules:convention.select_trailing_comma]
select_clause_trailing_comma = require
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
Thanks for the bug report - I've confirmed this is also still an issue on the recently release 2.0.4 too. I've got a solution coming for this shortly.
