### ISSUE TITLE
CV11 - Critical Error when converting NULL to longhand cast

### ISSUE THREAD

**Issue by WittierDinosaur** [sqlfluff/sqlfluff#4805]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

`sqlfluff fix` on the following file

```sql
SELECT
  CAST(m.bar AS DATETIME)
  , NULL::TIMESTAMP_NTZ
FROM foo.bar m
;
```

### Expected Behaviour

`NULL::TIMESTAMP_NTZ` should change to `CAST(NULL AS TIMESTAMP_NTZ)`

### Observed Behaviour

```bash
CRITICAL   [CV11] Applying rule CV11 to 'test_2.sql' threw an Exception: tuple index out of range                                                                                                                       
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/rules/base.py", line 796, in crawl
    res = self._eval(context=context)
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/rules/convention/CV11.py", line 270, in _eval
    expression_datatype_segment[1],
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/utils/functional/segments.py", line 155, in __getitem__
    result = super().__getitem__(item)
IndexError: tuple index out of range
```

### How to reproduce

sqlfluff fix the above script

### Dialect

Snowflake

### Version

2.0.7

### Configuration

I believe this'll hold true on default config (as CV11 being `consistent` is the key thing), but my config is here
```
[sqlfluff]
# https://docs.sqlfluff.com/en/stable/configuration.html#default-configuration
verbose = 0
nocolor = False
dialect = snowflake
templater = jinja
rules = None
exclude_rules = AL01,AM04,LT05,RF06,ST01,ST06
recurse = 0
output_line_length = 120
runaway_limit = 10
ignore = None
ignore_templated_areas = True
encoding = autodetect
disable_noqa = False
sql_file_exts = .sql,.sql.j2,.dml
fix_even_unparsable = False
large_file_skip_byte_limit = 200000
max_line_length = 120

[sqlfluff:indentation]
indented_joins = False
indented_ctes = False
indented_using_on = True
indent_unit = space
tab_space_size = 2
template_blocks_indent = True
allow_implicit_indents = True

[sqlfluff:templater]
unwrap_wrapped_queries = True

[sqlfluff:templater:jinja]
apply_dbt_builtins = True

[sqlfluff:templater:jinja:macros]
# Macros provided as builtins for dbt projects
dbt_ref = {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
dbt_source = {% macro source(source_name, table) %}{{source_name}}_{{table}}{% endmacro %}
dbt_config = {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}
dbt_var = {% macro var(variable, default='') %}item{% endmacro %}
dbt_is_incremental = {% macro is_incremental() %}True{% endmacro %}

# Some rules can be configured directly from the config common to other rules.
[sqlfluff:rules]
allow_scalar = True
single_table_references = consistent
unquoted_identifiers_policy = all

[sqlfluff:layout:type:comma]
line_position = leading

[sqlfluff:layout:type:binary_operator]
line_position = leading

[sqlfluff:rules:aliasing.column]
aliasing = explicit

[sqlfluff:rules:aliasing.expression]
allow_scalar = False

[sqlfluff:rules:aliasing.table]
aliasing = implicit

[sqlfluff:rules:capitalisation.functions]
extended_capitalisation_policy = upper

[sqlfluff:rules:capitalisation.identifiers]
extended_capitalisation_policy = lower

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.literals]
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.types]
extended_capitalisation_policy = upper

[sqlfluff:rules:convention.count_rows]
prefer_count_1 = False
prefer_count_0 = False

[sqlfluff:rules:convention.select_trailing_comma]
select_clause_trailing_comma = forbid

[sqlfluff:rules:convention.terminator]
multiline_newline = True
require_final_semicolon = True

[sqlfluff:rules:layout.long_lines]
ignore_comment_lines = False

[sqlfluff:rules:references.keywords]
unquoted_identifiers_policy = aliases
ignore_words = timestamp

[sqlfluff:rules:references.quoting]
ignore_words = date

[sqlfluff:rules:structure.subquery]
# By default, allow subqueries in FROM clauses, but not JOIN clauses.
forbid_subquery_in = join
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by MatthijsKok** [comment]
Just encountered this as well on the latest version `3.5.0`

Here is a minimal reproduction example
`.sqlfluff`
```.sqlfluff
[sqlfluff]
dialect = postgres
rules = convention.casting_style

[sqlfluff:rules:convention.casting_style]
preferred_type_casting_style = convert
```

`reproduction.sql`
```sql
select null::varchar from foo;
```

and terminal as follows
```
/projects/bugreport ❱ eza -ahl  
Mode  Size Date Modified Name
-a---  145 29 Oct 14:21  .sqlfluff
-a---   32 29 Oct 14:23  reproduction.sql
/projects/bugreport ❱ sqlfluff --version
sqlfluff, version 3.5.0
/projects/bugreport ❱ sqlfluff lint
CRITICAL   [CV11] Applying rule CV11 to '/projects/bugreport/reproduction.sql' threw an Exception: tuple index out of range                                                      
Traceback (most recent call last):
  File "/packages/uv/data/tools/sqlfluff/Lib/site-packages/sqlfluff/core/rules/base.py", line 518, in crawl
    res = self._eval(context=context)
  File "/packages/uv/data/tools/sqlfluff/Lib/site-packages/sqlfluff/rules/convention/CV11.py", line 407, in _eval
    expression_datatype_segment[1],
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/packages/uv/data/tools/sqlfluff/Lib/site-packages/sqlfluff/utils/functional/segments.py", line 173, in __getitem__
    result = super().__getitem__(item)
IndexError: tuple index out of range
== [/projects/bugreport/reproduction.sql] FAIL                                                                                                                                        
L:   1 | P:   8 | CV11 | Unexpected exception: tuple index out of range;
Could
                       | you open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ?
You can
                       | ignore this exception for now, by adding '-- noqa: CV11'
                       | at the end
of line 1

                       | [convention.casting_style]
All Finished 📜 🎉!

```

**Comment by peterbud** [comment]
Fixed with #7568, latest sqlfluff properly fixes this statement.
