### ISSUE TITLE
Error with `sqlfluff==2.1.0` and `dbt-postgres==1.4.6`

### ISSUE THREAD

**Issue by dave-connors-3** [sqlfluff/sqlfluff#4843]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

After upgrading to the latest sqlfluff version (of `sqlfluff` and `sqlfluff-templater-dbt`), using dbt version 1.4 throws and error when running `sqlfluff lint models/my_first_dbt_model.sql`

```
❯ sqlfluff lint models/my_first_dbt_model.sql              
=== [dbt templater] Sorting Nodes...
Traceback (most recent call last):
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 605, in lint
    result = lnt.lint_paths(
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 1206, in lint_paths
    for i, linted_file in enumerate(runner.run(expanded_paths, fix), start=1):
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 106, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 59, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 42, in iter_rendered
    for fname in self.linter.templater.sequence_files(
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 276, in sequence_files
    for key, node in self.dbt_manifest.nodes.items():
  File "/Users/daveconnors/.pyenv/versions/3.9.16/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 148, in dbt_manifest
    self.dbt_manifest = ManifestLoader.get_full_manifest(self.dbt_config)
  File "/Users/daveconnors/.pyenv/versions/3.9.16/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 110, in dbt_config
    self.dbt_config = DbtRuntimeConfig.from_args(
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/dbt/config/runtime.py", line 263, in from_args
    project, profile = cls.collect_parts(args)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/dbt/config/runtime.py", line 205, in collect_parts
    cli_vars: Dict[str, Any] = parse_cli_vars(getattr(args, "vars", "{}"))
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/dbt/config/utils.py", line 16, in parse_cli_vars
    return parse_cli_yaml_string(var_string, "vars")
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/dbt/config/utils.py", line 21, in parse_cli_yaml_string
    cli_vars = yaml_helper.load_yaml_text(var_string)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/dbt/clients/yaml_helper.py", line 56, in load_yaml_text
    return safe_load(contents)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/dbt/clients/yaml_helper.py", line 51, in safe_load
    return yaml.load(contents, Loader=SafeLoader)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/yaml/cyaml.py", line 26, in __init__
    CParser.__init__(self, stream)
  File "yaml/_yaml.pyx", line 288, in yaml._yaml.CParser.__init__
TypeError: a string or stream input is required
```

### Expected Behaviour

Expected behavior is that this would run as expected without error!

### Observed Behaviour

Looks to be an issue with the implementation in `DbtRuntimeConfig()`

```
File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/doug/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 110, in dbt_config
    self.dbt_config = DbtRuntimeConfig.from_args(
...
```

### How to reproduce

1. `pip install dbt-postgres==1.4.6`
1. `dbt init new_project`
1. `pip install sqlfluff==2.1.0 sqlfluff-templater-dbt==2.1.0` 
2. `sqlfluff lint model/my_first_dbt_model.sql`

### Dialect

postgres

### Version

2.1.0

### Configuration
```
[sqlfluff]
dialect = postgres
templater = dbt
; templater = jinja
runaway_limit = 10
rules = L002, L004, L005, L010, L011, L012, L013, L014, L016, L018, L019, L022, L023, L027, L030, L031, L032, L033, L034, L040, L046, L048, L042, L051, L054, L065
max_line_length = 80
indent_unit = space

# Rule definitions:
# L002: Mixed Tabs and Spaces in single whitespace
# L004: Incorrect indentation type (should be space)
# L004: Commas should not have whitespace directly before them.
# L010: Inconsistent capitalisation of keywords (should be lowercase)
# L011: Implicit/explicit aliasing of table (use 'as' for alias)
# L012: Implicit/explicit aliasing of columns (use 'as' for alias)
# L013: Column expression without alias (use 'as' for alias)
# L014: Inconsistent capitalisation of unquoted identifiers (should be lowercase)
# L016: Line is too long
# L018: WITH clause closing bracket should be on a new line.
# L019: Trailing comma enforcement
# L022: Blank line expected but not found after CTE closing bracket.
# L023: Single whitespace expected after AS in WITH clause.
# L027: References should be qualified if select has more than one referenced table/view
# L030: Inconsistent capitalisation of function names (should be lowercase)
# L031: Avoid table aliases in from clauses and join conditions 
# L032: Prefer specifying join keys instead of using USING. 
# L033: UNION [DISTINCT|ALL] is preferred over just UNION
# L034: Select wildcards then simple targets before calculations and aggregates
# L040: Inconsistent capitalisation of boolean/null literal (should be lowercase)
# L042: Join/From clauses should not contain subqueries. Use CTEs instead.
# L046: Jinja tags should have a single whitespace on either side.
# L048: Quoted literals should be surrounded by a single whitespace.
# L051: Join clauses should be fully qualified (LEFT/RIGHT/FULL/INNER)
# L054: Use numbers in GROUP BY and ORDER BY
# L065: Set operators should be surrounded by newlines.



[sqlfluff:indentation]
tab_space_size = 4

[sqlfluff:layout:type:comma]
spacing_before = touch
line_position = trailing

#[sqlfluff:templater:jinja]
#load_macros_from_path = macros

[sqlfluff:rules:capitalisation.keywords]  # Keywords
capitalisation_policy = lower

[sqlfluff:rules:aliasing.table]  # Explicit table alias
aliasing = explicit

[sqlfluff:rules:aliasing.column]  # Explicit column alias
aliasing = explicit

[sqlfluff:rules:aliasing.expression]  # Column expressions must have alias
allow_scalar = False

[sqlfluff:rules:capitalisation.identifiers]  # Unquoted identifiers
extended_capitalisation_policy = lower

[sqlfluff:rules:capitalisation.functions]  # Function names
capitalisation_policy = lower

[sqlfluff:rules:capitalisation.literals]  # Boolean names
capitalisation_policy = lower

[sqlfluff:rules:ambiguous.column_references]  # Number in group by
group_by_and_order_by_style = implicit
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by derik-roby** [comment]
Were you able to get it to work ?

**Comment by awoehrl** [comment]
I have the same problem with dbt-bigquery==1.4.3

**Comment by matfior-finn** [comment]
Pinning to the previous version (2.0.7) helped me resolve the issue for now.

**Comment by tonicebrian** [comment]
Same issue with `dbt-athena-community`. Pinning to 2.0.7 also resolved the issue.

**Comment by courentin** [comment]
Same issue with dbt-snowflake==1.3.3. Pinning sqlfluff to 2.0.7 resolved for me.

**Comment by tonicebrian** [comment]
It seems like 2.1.1 solves the issue (or at least I cannot see it anymore)

**Comment by WittierDinosaur** [comment]
I believe this is resolved, closing. Feel free to reopen if this problem persists on the latest version
