### ISSUE TITLE
Ugly error when `dbt deps` required to run

### ISSUE THREAD

**Issue by alanmcruickshank** [sqlfluff/sqlfluff#5069]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

This is more a quality of life improvement. When using the `dbt` templater, but `dbt deps` is required to run, the error traceback is pretty ugly:

```
> pipenv run sqlfluff lint .\models\marts\data_ops\
=== [dbt templater] Sorting Nodes...
file models\marts\data_ops\dim_customer_deletion_horizon.sql:   0%|                     | 0/6 [00:06<?, ?it/s]10:12:05  Registered adapter: snowflake=1.6.0
Traceback (most recent call last):
  File "C:\Users\alanc\.virtualenvs\data_warehouse-quLENCc_\Scripts\sqlfluff-script.py", line 33, in <module>
    sys.exit(load_entry_point('sqlfluff', 'console_scripts', 'sqlfluff')())
  File "C:\Users\alanc\.virtualenvs\data_warehouse-quLENCc_\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\alanc\.virtualenvs\data_warehouse-quLENCc_\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\alanc\.virtualenvs\data_warehouse-quLENCc_\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\alanc\.virtualenvs\data_warehouse-quLENCc_\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\alanc\.virtualenvs\data_warehouse-quLENCc_\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\alanc\dev\sqlfluff\src\sqlfluff\cli\commands.py", line 639, in lint
    result = lnt.lint_paths(
  File "c:\users\alanc\dev\sqlfluff\src\sqlfluff\core\linter\linter.py", line 1078, in lint_paths
    for i, linted_file in enumerate(runner.run(expanded_paths, fix), start=1):
  File "c:\users\alanc\dev\sqlfluff\src\sqlfluff\core\linter\runner.py", line 143, in run
    for lint_result in self._map(
  File "C:\Python39\lib\multiprocessing\pool.py", line 870, in next
    raise value
dbt.exceptions.UninstalledPackagesFoundError: Compilation Error
  dbt found 5 package(s) specified in packages.yml, but only 4 package(s) installed in dbt_packages. Run "dbt deps" to install package dependencies.
```

I think explicitly handling this exception (or perhaps a slightly broader class of them) - and making this a bit prettier and less aggressive.

### Dialect

all

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
This was resolved by #5072
