### ISSUE TITLE
sqlfluff errors on v2.2.0 (pip3/Ubuntu) with "name 'completion' is not defined"

### ISSUE THREAD

**Issue by jdahlbom** [sqlfluff/sqlfluff#5195]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I upgraded from 2.1.3 to latest version and running sqlfluff started giving this error:
Traceback (most recent call last):
  File "/home/x/.local/bin/sqlfluff", line 5, in <module>
    from sqlfluff.cli.commands import cli
  File "/home/x/.local/lib/python3.8/site-packages/sqlfluff/cli/commands.py", line 23, in <module>
    from sqlfluff.cli.autocomplete import shell_completion_enabled, dialect_shell_complete
  File "/home/x/.local/lib/python3.8/site-packages/sqlfluff/cli/autocomplete.py", line 16, in <module>
    def dialect_shell_complete(ctx, param, incomplete) -> List[completion.CompletionItem]:
NameError: name 'completion' is not defined

I have installed sqlfluff via pip3 on Ubuntu LTS 20.04

Version 2.1.4 is the last tagged version that works as expected, and starting from version 2.2.0 the above error
occurs whenever I try to run sqlfluff parse or sqlfluff lint

### Expected Behaviour

Running sqlfluff lint <file> should start processing the file(s).

### Observed Behaviour

The sqlfluff breaks with this error message:
Traceback (most recent call last):
  File "/home/x/.local/bin/sqlfluff", line 5, in <module>
    from sqlfluff.cli.commands import cli
  File "/home/x/.local/lib/python3.8/site-packages/sqlfluff/cli/commands.py", line 23, in <module>
    from sqlfluff.cli.autocomplete import shell_completion_enabled, dialect_shell_complete
  File "/home/x/.local/lib/python3.8/site-packages/sqlfluff/cli/autocomplete.py", line 16, in <module>
    def dialect_shell_complete(ctx, param, incomplete) -> List[completion.CompletionItem]:
NameError: name 'completion' is not defined

### How to reproduce

Running on Ubuntu:
pip3 install sqlfluff==2.1.4
sqlfluff lint <file.sql>
--> Should start running the linting

pip3 uninstall sqlfluff
pip3 install sqlfluff==2.2.0
sqlfluff lint <file.sql>
Breaks with the error about the completion.

### Dialect

Redshift, but the error occurs even when not defining the dialiect and using default configuration.

### Version

Observed the error first with 2.3.2
Tested to see that error first occurs with 2.2.0
Last working version is 2.1.4

### Configuration

Does not seem to affect the error.

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by jdahlbom** [comment]
I checked the requirements.txt to see that `click` is not given a specific required version.
Running `pip3 install -U click` installed v8.1.7 with which the sqlfluff 2.3.2 worked fine.

Verified that this really was the fix I 
- uninstalled sqlfluff and click, 
- installed `click==7.0` which I had previously installed.
- installed sqlfluff
- Ran the linter, and got the same error.

To me it seems that new enough click version should be required, and that the code checking the backwards compatibility is broken because the function definition itself breaks because `completion` is not defined.
