### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe returned when running sqlfluff in Gitlab CI/CD environment

### ISSUE THREAD

**Issue by akshayajbani** [sqlfluff/sqlfluff#5248]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When running sqlfluff lint in verbose mode locally on my machine (macOS), on my dbt codebase, I am able to successfully lint the repo without any issues. However, when our CI job (using Gitlab's CI/CD) attempts to run the exact same command in a similarly configured environment, it is able to lint several files before it eventually errors throwing a `BrokenPipeError: [Errno 32] Broken pipe` error. I tried running different subsets of the project to determine if there was an issue with linting a specific code file, but it appears to trigger seemingly randomly after linting several files.

Both on my local machine and in gitlab ci the python versions match, the packages are installed into a venv using the same requirements file. As far as I am aware they are setup to be relatively identical environments

### Expected Behaviour

I would anticipate that the running `sqlfluff lint` in a CI/CD environment would successfully run as it does locally given the environments are similarly configured.

### Observed Behaviour

Logs in Gitlab CI/CI 

```
$ sqlfluff lint ./snapshots ./models -vv
==== sqlfluff ====
sqlfluff:                2.3.2 python:                 3.11.2
implementation:        cpython verbosity:                   2
dialect:             snowflake templater:                 dbt
dbt:                    =1.6.0
rules:                                all
== Raw Config:
core:                                   
    dialect:            snowflake           
    disable_noqa:       False               
    encoding:           autodetect          
    exclude_rules:      ambiguous.column_count, structure.column_order, references.keywords, aliasing.length
    fix_even_unparsable:False               
    ignore:             []                  
    ignore_templated_areas:True                
    large_file_skip_byte_limit:0                   
    large_file_skip_char_limit:0                   
    max_line_length:    160                 
    nocolor:            False               
    output_line_length: 80                  
    processes:          -1                  
    rules:              all                 
    runaway_limit:      10                  
    sql_file_exts:      .sql,.sql.j2,.dml,.ddl
    templater:          dbt                 
    verbose:            2                   
    warn_unused_ignores:False               
    warnings:           []                  
indentation:                            
    allow_implicit_indents:True                
    indent_unit:        space               
    indented_ctes:      False               
    indented_joins:     False               
    indented_on_contents:True                
    indented_then:      True                
    indented_then_contents:True                
    indented_using_on:  True                
    skip_indentation_in:script_content      
    tab_space_size:     4                   
    template_blocks_indent:True                
    trailing_comments:  before              
layout:                                 
    type:                                   
        array_accessor:                         
            spacing_before:     touch:inline        
        array_type:                             
            spacing_within:     touch:inline        
        assignment_operator:                    
            line_position:      leading             
            spacing_within:     touch               
        binary_operator:                        
            line_position:      leading             
            spacing_within:     touch               
        bracketed_arguments:                    
            spacing_before:     touch:inline        
        casting_operator:                       
            spacing_after:      touch:inline        
            spacing_before:     touch               
        colon:                                  
            spacing_before:     touch               
        comma:                                  
            line_position:      trailing            
            spacing_before:     touch               
        comment:                                
            spacing_after:      any                 
            spacing_before:     any                 
        common_table_expression:                    
            spacing_within:     single:inline       
        comparison_operator:                    
            line_position:      leading             
            spacing_within:     touch               
        end_angle_bracket:                      
            spacing_before:     touch               
        end_bracket:                            
            spacing_before:     touch               
        end_of_file:                            
            spacing_before:     touch               
        end_square_bracket:                     
            spacing_before:     touch               
        from_clause:                            
            line_position:      alone               
        function_name:                          
            spacing_after:      touch:inline        
            spacing_within:     touch:inline        
        groupby_clause:                         
            line_position:      alone               
        having_clause:                          
            line_position:      alone               
        join_clause:                            
            line_position:      alone               
        limit_clause:                           
            line_position:      alone               
        numeric_literal:                        
            spacing_within:     touch:inline        
        object_reference:                       
            spacing_within:     touch:inline        
        orderby_clause:                         
            line_position:      leading             
        placeholder:                            
            spacing_after:      any                 
            spacing_before:     any                 
        select_clause:                          
            line_position:      alone               
        semi_structured_expression:                    
            spacing_before:     touch:inline        
            spacing_within:     touch:inline        
        set_operator:                           
            line_position:      alone:strict        
        sign_indicator:                         
            spacing_after:      touch:inline        
        sized_array_type:                       
            spacing_within:     touch               
        slice:                                  
            spacing_after:      touch               
            spacing_before:     touch               
        start_angle_bracket:                    
            spacing_after:      touch               
        start_bracket:                          
            spacing_after:      touch               
        start_square_bracket:                    
            spacing_after:      touch               
        statement_terminator:                    
            line_position:      trailing            
            spacing_before:     touch               
        struct_type:                            
            spacing_within:     touch:inline        
        template_loop:                          
            spacing_after:      any                 
            spacing_before:     any                 
        tilde:                                  
            spacing_after:      touch:inline        
        typed_array_literal:                    
            spacing_within:     touch               
        typed_struct_literal:                    
            spacing_within:     touch               
        where_clause:                           
            line_position:      alone               
rules:                                  
    allow_scalar:       True                
    single_table_references:consistent          
    unquoted_identifiers_policy:all                 
    aliasing.column:                        
        aliasing:           explicit            
    aliasing.forbid:                        
        force_enable:       False               
    aliasing.length:                        
        min_alias_length:   3                   
    aliasing.table:                         
        aliasing:           explicit            
    ambiguous.column_references:                    
        group_by_and_order_by_style:consistent          
    ambiguous.join:                         
        fully_qualify_join_types:inner               
    capitalisation.functions:                    
        extended_capitalisation_policy:lower               
    capitalisation.identifiers:                    
        capitalisation_policy:lower               
        extended_capitalisation_policy:consistent          
    capitalisation.keywords:                    
        capitalisation_policy:lower               
    capitalisation.literals:                    
        capitalisation_policy:lower               
    capitalisation.types:                    
        extended_capitalisation_policy:lower               
    convention.blocked_words:                    
        match_source:       False               
    convention.casting_style:                    
        fully_qualify_join_types:both                
        preferred_type_casting_style:shorthand           
    convention.count_rows:                    
        prefer_count_0:     False               
        prefer_count_1:     False               
    convention.quoted_literals:                    
        force_enable:       False               
        preferred_quoted_literal_style:consistent          
    convention.select_trailing_comma:                    
        select_clause_trailing_comma:forbid              
    convention.terminator:                    
        multiline_newline:  False               
        require_final_semicolon:False               
    layout.long_lines:                      
        ignore_comment_clauses:False               
        ignore_comment_lines:False               
    layout.select_targets:                    
        wildcard_policy:    single              
    references.consistent:                    
        force_enable:       False               
    references.from:                        
        force_enable:       False               
    references.keywords:                    
        unquoted_identifiers_policy:aliases             
    references.qualification:                    
    references.quoting:                     
        force_enable:       False               
        prefer_quoted_identifiers:False               
        prefer_quoted_keywords:False               
    references.special_chars:                    
        allow_space_in_identifier:False               
        quoted_identifiers_policy:all                 
        unquoted_identifiers_policy:all                 
    structure.join_condition_order:                    
        preferred_first_table_in_join_clause:earlier             
    structure.subquery:                     
        forbid_subquery_in: join                
templater:                              
    unwrap_wrapped_queries:True                
    dbt:                                    
        project_dir:        /builds/*******/*********/***********-dbt/./
    jinja:                                  
        apply_dbt_builtins: True                
==== readout ====
effective configured processes:  31
=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
== [models/staging/information_schema/stg_information_schema__columns.sql] PASS
== [models/staging/information_schema/stg_information_schema__tables.sql] PASS
== [snapshots/int_all_dag_relationships_snapshot.sql] PASS
== [models/staging/fivetran_log/stg_fivetran_log__credits_used.sql] PASS
== [models/staging/fivetran_log/stg_fivetran_log__usage_cost.sql] PASS
== [models/staging/fivetran_log/stg_fivetran_log__incremental_mar.sql] PASS
Process ForkPoolWorker-29:
/scripts-34200749-517[97](https://gitlab.com/sondermind/analytics/sondermind-dbt/-/jobs/5179704665#L97)04665/step_script: line 249:   104 Killed                  sqlfluff lint ./snapshots ./models/staging -vv
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/usr/local/lib/python3.11/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 1[99](https://gitlab.com/sondermind/analytics/sondermind-dbt/-/jobs/5179704665#L99), in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(buf)
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 367, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line [108](https://gitlab.com/sondermind/analytics/sondermind-dbt/-/jobs/5179704665#L108), in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/usr/local/lib/python3.11/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 199, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 410, in _send_bytes
    self._send(header + buf)
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 367, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line [131](https://gitlab.com/sondermind/analytics/sondermind-dbt/-/jobs/5179704665#L131), in worker
    put((job, i, result))
  File "/usr/local/lib/python3.11/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 199, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 403, in _send_bytes
    self._send(header)
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 367, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line [136](https://gitlab.com/sondermind/analytics/sondermind-dbt/-/jobs/5179704665#L136), in worker
    put((job, i, (False, wrapped)))
  File "/usr/local/lib/python3.11/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line [199](https://gitlab.com/sondermind/analytics/sondermind-dbt/-/jobs/5179704665#L199), in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 410, in _send_bytes
    self._send(header + buf)
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 367, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
Cleaning up project directory and file based variables
00:01
Process ForkPoolWorker-31:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
ERROR: Job failed: command terminated with exit code 1

```

### How to reproduce

in gitlab CI/CD, the following commands are run
- python -m venv venv
- source ./venv/bin/activate
- pip3 install -q -r ./requirements.txt
- dbt deps
- sqlfluff lint ./snapshots ./models -vv

In my local dev environment I ran all of these steps as well, but I was able to run successfully.

I imagine that this will need to be reproduced in Gitlab CI/CD

### Dialect

snowflake

### Version

sqlfluff:                2.3.2
python:                 3.11.2
implementation:        cpython
verbosity:                   2
dialect:             snowflake
templater:                 dbt
dbt:                    =1.6.0

### Configuration

```
[sqlfluff]

dialect = snowflake

# jinja templater better for speed in IDE, CI/CD should use the dbt templater for accuracy
templater = dbt

# Comma separated list of rules to exclude, or None
# See https://docs.sqlfluff.com/en/stable/configuration.html#enabling-and-disabling-rules
# references.keywords - sometimes we use keywords as column names, while this isnt the best practice occasionally it is unavoidable
exclude_rules = ambiguous.column_count, structure.column_order, references.keywords, aliasing.length

max_line_length = 160

large_file_skip_byte_limit = 0

processes = -1

[sqlfluff:templater:dbt]
project_dir = ./
# profiles_dir = ./

[sqlfluff:indentation]
allow_implicit_indents = true

[sqlfluff:rules:aliasing.table]
aliasing = explicit
[sqlfluff:rules:aliasing.column]
aliasing = explicit
[sqlfluff:rules:aliasing.length]
min_alias_length = 3

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = lower
[sqlfluff:rules:capitalisation.identifiers]
capitalisation_policy = lower
[sqlfluff:rules:capitalisation.functions]
extended_capitalisation_policy = lower
[sqlfluff:rules:capitalisation.literals]
capitalisation_policy = lower
[sqlfluff:rules:capitalisation.types]
extended_capitalisation_policy = lower

# We generally prefer using ::type to cast rather than cast(col as type)
[sqlfluff:rules:convention.casting_style]
preferred_type_casting_style = shorthand

fully_qualify_join_types = both
```

```
analysis/
data/
dbt_packages/
macros/
target/
tests/
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by pdebelak** [comment]
The `effective configured processes:  31` line in your logs makes me suspect that you're running into some sort of resource limit in gitlab and some of your forked processes are being killed. Have you tried setting the `processes` config to a specific number like `4` rather than `-1` (which means use all available cores) and seeing if that resolves your error?

**Comment by akshayajbani** [comment]
Thanks for the suggestion! I was just about to close this because I was able to resolve this by setting the `processes` to 2.
