### ISSUE TITLE
Catch uncaught exception jinja2.exceptions.TemplateSyntaxError

### ISSUE THREAD

**Issue by jeremyyeo** [sqlfluff/sqlfluff#5276]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Largely this is similar to https://github.com/sqlfluff/sqlfluff/issues/3199 where there is an uncaught exception which is crashing sqlfluff. Because sqlfluff crashed - instead of say reporting a templating error instead - the dbt Cloud IDE does not return any errors to the end user (dbt Cloud does not return Python stack traces).

### Expected Behaviour

Have such errors be caught and reported as templating errors instead so that sqlfluff doesn't crash :)

### Observed Behaviour

sqlfluff runs into an uncaught exception.

### How to reproduce

Add the following files to a folder:

```yaml
# dbt_project.yml
name: my_dbt_project
profile: all
config-version: 2
version: 1.0

models:
  my_dbt_project:
    +materialized: table
```

```sql
-- models/foo.sql
select 1 id
```

Then lint:

```sh
$ sqlfluff lint models/foo.sql

Traceback (most recent call last):
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 635, in lint
    result = lnt.lint_paths(
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 1070, in lint_paths
    for i, linted_file in enumerate(runner.run(expanded_paths, fix), start=1):
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 107, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 60, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 47, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 739, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 710, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/sqlfluff/core/templaters/base.py", line 54, in _wrapped
    return func(self, in_str=in_str, fname=fname, config=config, **kwargs)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/sqlfluff/core/templaters/jinja.py", line 410, in process
    env, live_context, render_func = self.construct_render_func(
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/sqlfluff/core/templaters/jinja.py", line 352, in construct_render_func
    live_context = self.get_context(fname=fname, config=config, env=env)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/sqlfluff/core/templaters/jinja.py", line 339, in get_context
    self._extract_macros_from_config(
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/sqlfluff/core/templaters/jinja.py", line 129, in _extract_macros_from_config
    self._extract_macros_from_template(value, env=env, ctx=ctx)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/sqlfluff/core/templaters/jinja.py", line 60, in _extract_macros_from_template
    macro_template = env.from_string(template, globals=ctx)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: expected token '(', got '.'
```

### Dialect

snowflake

### Version

```
sqlfluff, version 2.3.2
```

### Configuration

```
# .sqlfluff
[sqlfluff]
templater = jinja
dialect = snowflake

[sqlfluff:templater:jinja:macros]
a_macro_def = {% macro pkg.my_macro() %}pass{% endmacro %}
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
Hmmm good question. The issue here is the config file, rather than the sql file, so I don't think we should report it as a templating issue, because all templating issues are issues with sql files themselves.

I do think this should be reported with a clearer error than with a stacktrace however - this could very easily happen again for other users. If you're on dbt cloud, can you report this issue to their support too?
