### ISSUE TITLE
SqlFluff breaks when linting T-SQL construct "FUNCTION x RETURNS TABLE"

### ISSUE THREAD

**Issue by geepy** [sqlfluff/sqlfluff#5301]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When linting a construct like
```sql
CREATE FUNCTION x
RETURNS TABLE
AS
  RETURN 
  SELECT
    something
  FROM sometable
```
sqlfluff throws an exception "AssertionError".

### Expected Behaviour

sqlfluff lints the function without execption.

### Observed Behaviour

An Exception with content:
```
CRITICAL   [RF01] Applying rule RF01 to 'c:\\temp\\sqlfluff_error.sql' threw an Exception: 
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\conda\envs\sqlfluff\Lib\site-packages\sqlfluff\core\rules\base.py", line 864, in crawl
    res = self._eval(context=context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\conda\envs\sqlfluff\Lib\site-packages\sqlfluff\rules\references\RF01.py", line 107, in _eval
    self._analyze_table_references(
  File "C:\Users\me\AppData\Local\conda\envs\sqlfluff\Lib\site-packages\sqlfluff\rules\references\RF01.py", line 152, in _analyze_table_references
    if not self._should_ignore_reference(r, selectable):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\conda\envs\sqlfluff\Lib\site-packages\sqlfluff\rules\references\RF01.py", line 168, in _should_ignore_reference
    ref_path = selectable.selectable.path_to(reference)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\conda\envs\sqlfluff\Lib\site-packages\sqlfluff\core\parser\segments\base.py", line 1184, in path_to
    elif not self.get_start_loc() <= midpoint.get_start_loc() <= self.get_end_loc():
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\conda\envs\sqlfluff\Lib\site-packages\sqlfluff\core\parser\segments\base.py", line 877, in get_start_loc
    assert self.pos_marker
AssertionError
```
is thrown.

### How to reproduce

* create an environment with sqlfluff (I used `conda create`)
* create a file "sqlfluff_error.sql" containing the following SQL:
```sql
CREATE FUNCTION [ETL].[ufnProvokesSqlFluffError] ()
RETURNS TABLE
AS
  RETURN 
  SELECT
    [i].[AssetID]
  FROM [sometable] [i]
GO
```

### Dialect

tsql

### Version

Python 3.11.5 and sqlfluff 2.3.2 

### Configuration

no config file

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by keraion** [comment]
Fixed in 2.3.3 release
