### ISSUE TITLE
CLI is broken in master branch?

### ISSUE THREAD

**Issue by pwildenhain** [sqlfluff/sqlfluff#532]
The simplest query
test.sql
```sql
select 1
```

Can't lint (or parse) it 😱 
```
$ pip install --upgrade https://github.com/sqlfluff/sqlfluff/archive/master.zip
$ sqlfluff lint .\test.sql

Traceback (most recent call last):
  File "C:\Users\wildenhaip\AppData\Local\Programs\Python\Python38\Scripts\sqlfluff-script.py", line 33, in <module>
    sys.exit(load_entry_point('sqlfluff==0.3.6', 'console_scripts', 'sqlfluff')())
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\sqlfluff\cli\commands.py", line 297, in lint
    c = get_config(**kwargs)
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\sqlfluff\cli\commands.py", line 193, in get_config
    return FluffConfig.from_root(overrides=overrides)
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\sqlfluff\core\config.py", line 355, in from_root
    return cls(configs=c, overrides=overrides)
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\sqlfluff\core\config.py", line 344, in __init__
    self._configs["core"]["dialect"]
KeyError: 'dialect'
```

Can someone else verify this?

**Comment by pwildenhain** [comment]
Did a little more debugging, and I don't _think_ I'm crazy (at least in this issue 😝 )

The **current** error seems to go back to f38b6fb6b0069a3483861fda07d3bcfd565dfcb5 merged in #513 
```
$ pip install --upgrade https://github.com/sqlfluff/sqlfluff/archive/f38b6fb.zip
$ sqlfluff lint test.sql
Traceback (most recent call last):
  File "C:\Users\wildenhaip\AppData\Local\Programs\Python\Python38\Scripts\sqlfluff-script.py", line 33, in <module>
    sys.exit(load_entry_point('sqlfluff==0.3.6', 'console_scripts', 'sqlfluff')())
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\sqlfluff\cli\commands.py", line 297, in lint
    c = get_config(**kwargs)
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\sqlfluff\cli\commands.py", line 193, in get_config
    return FluffConfig.from_root(overrides=overrides)
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\sqlfluff\core\config.py", line 355, in from_root
    return cls(configs=c, overrides=overrides)
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\sqlfluff\core\config.py", line 344, in __init__
    self._configs["core"]["dialect"]
KeyError: 'dialect'
```

From there, another merge seems to be broken in a _different_ way:
Commit: be885072abac897a72bd98af567bfe01a04caa65 merged in #501 
```
$ pip install --upgrade https://github.com/sqlfluff/sqlfluff/archive/be88507.zip
$ sqlfluff lint test.sql

Traceback (most recent call last):
  File "C:\Users\wildenhaip\AppData\Local\Programs\Python\Python38\Scripts\sqlfluff-script.py", line 33, in <module>
    sys.exit(load_entry_point('sqlfluff==0.3.6', 'console_scripts', 'sqlfluff')())
  File "C:\Users\wildenhaip\AppData\Local\Programs\Python\Python38\Scripts\sqlfluff-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\wildenhaip\appdata\local\programs\python\python38\lib\site-packages\sqlfluff\__init__.py", line 5, in <module>
    from .api import lint, fix, parse  # noqa: F401
ModuleNotFoundError: No module named 'sqlfluff.api'
```

The last commit that works when I install from GitHub is: 66e8d533549cd85c01c0ff76331de7eb7fdec0dd merged in #497
```
$ pip install --upgrade https://github.com/sqlfluff/sqlfluff/archive/66e8d53.zip
$ sqlfluff lint test.sql


```

**Comment by alanmcruickshank** [comment]
Wierd, I thought I fixed that issue in this commit: https://github.com/sqlfluff/sqlfluff/commit/0057eb17d56660e53856c4c3d844a4e8716e90ca

My current dev branch is working, which last merged with master on 0c1d9e0e6596feed23791069b198b7204d55f457, that being said, my dev env is cluttered with all kinds of testing files which could be masking any issues.

@pwildenhain , can you check which modules are listed in your `setup.py`?

**Comment by pwildenhain** [comment]
How do I inspect the `setup.py`  of an installed package? The commit I referenced is the merge commit with those changes you mentioned 🤷‍♂️ 

@alanmcruickshank Can you recreate this by installing from GitHub in a fresh env?

**Comment by pwildenhain** [comment]
`pip install -e git+https://github.com/sqlfluff/sqlfluff#egg=sqlfluff` worked 🤷‍♂️ so maybe it was `pip install --upgrade https://github.com/sqlfluff/sqlfluff/archive/master.zip` that was the issue? either way, this isn't an issue
