### ISSUE TITLE
Cannot use `dbt_utils.at_least_one` with `group_by_columms`

### ISSUE THREAD

**Issue by friendofasquid** [sqlfluff/sqlfluff#5486]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I have a test using `dbt_utils.at_least_one` with `group_by_columms`. When I run this with dbt, it's fine. But when I use sqlfluff with dbt templater,

I was unable to figure out the right incantation in `.sqlfluff` to stub this, but did manage to work around this by create the macro in my project like so:

```
{#
    This is to make sqlfluff happy, and serves no other purpose.
#}
{% macro test_at_least_one(model, column_name, group_by_columns=None, having=None) %}select 1{% endmacro %}
```

### Expected Behaviour

I would expect sqlfluff to use the macro from my `packages.yml` file and not to error.

### Observed Behaviour

```
> sqlfluff lint
==== sqlfluff ====
sqlfluff:                2.3.5 python:                 3.11.7
implementation:        cpython verbosity:                   1
dialect:             snowflake templater:                 dbt
dbt:                    =1.7.4
rules:                                all
==== readout ====

=== [dbt templater] Sorting Nodes...                                               
file /workspace/dbt/analysis/DH-130/avg_payment_times_from_payment_collection_to_diTraceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/dbt/clients/jinja.py", line 302, in exception_handler
    yield
  File "/usr/local/lib/python3.11/site-packages/dbt/clients/jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/runtime.py", line 752, in __call__
    raise TypeError(
TypeError: macro 'dbt_macro__test_at_least_one' takes no keyword argument 'group_by_columms'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlfluff/cli/commands.py", line 633, in lint
    result = lnt.lint_paths(
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlfluff/core/linter/linter.py", line 1084, in lint_paths
    for i, linted_file in enumerate(runner.run(expanded_paths, fix), start=1):
  File "/usr/local/lib/python3.11/site-packages/sqlfluff/core/linter/runner.py", line 107, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/usr/local/lib/python3.11/site-packages/sqlfluff/core/linter/runner.py", line 60, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/usr/local/lib/python3.11/site-packages/sqlfluff/core/linter/runner.py", line 43, in iter_rendered
    for fname in self.linter.templater.sequence_files(
  File "/usr/local/lib/python3.11/site-packages/sqlfluff_templater_dbt/templater.py", line 386, in sequence_files
    for key, node in self.dbt_manifest.nodes.items():
                     ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlfluff_templater_dbt/templater.py", line 235, in dbt_manifest
    self.dbt_manifest = ManifestLoader.get_full_manifest(self.dbt_config)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/parser/manifest.py", line 318, in get_full_manifest
    manifest = loader.load()
               ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/parser/manifest.py", line 495, in load
    self.parse_project(
  File "/usr/local/lib/python3.11/site-packages/dbt/parser/manifest.py", line 671, in parse_project
    parser.parse_file(block, dct=dct)
  File "/usr/local/lib/python3.11/site-packages/dbt/parser/schemas.py", line 177, in parse_file
    self.generic_test_parser.parse_tests(test_block)
  File "/usr/local/lib/python3.11/site-packages/dbt/parser/schema_generic_tests.py", line 388, in parse_tests
    self.parse_column_tests(block, column, None)
  File "/usr/local/lib/python3.11/site-packages/dbt/parser/schema_generic_tests.py", line 79, in parse_column_tests
    self.parse_test(block, test, column, version)
  File "/usr/local/lib/python3.11/site-packages/dbt/parser/schema_generic_tests.py", line 384, in parse_test
    self.parse_node(block)
  File "/usr/local/lib/python3.11/site-packages/dbt/parser/schema_generic_tests.py", line 322, in parse_node
    node = self.parse_generic_test(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/parser/schema_generic_tests.py", line 225, in parse_generic_test
    self.render_test_update(node, config, builder, schema_file_id)
  File "/usr/local/lib/python3.11/site-packages/dbt/parser/schema_generic_tests.py", line 303, in render_test_update
    get_rendered(node.raw_code, context, node, capture_macros=True)
  File "/usr/local/lib/python3.11/site-packages/dbt/clients/jinja.py", line 600, in get_rendered
    rendered = render_template(template, ctx, node)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/clients/jinja.py", line 546, in render_template
    return template.render(ctx)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/clients/jinja.py", line 330, in __call__
    return self.call_macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/clients/jinja.py", line 255, in call_macro
    with self.exception_handler():
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/dbt/clients/jinja.py", line 304, in exception_handler
    raise CaughtMacroErrorWithNodeError(exc=e, node=self.macro)
dbt.exceptions.CaughtMacroErrorWithNodeError: Compilation Error in test dbt_utils_at_least_one_targets_marketing__month_region_segment_measure_value__month__region__segment__measure_name (data/targets/marketing/_schema.yml)
  macro 'dbt_macro__test_at_least_one' takes no keyword argument 'group_by_columms'
```

### How to reproduce

My packages.yml:

```
packages:
  - package: dbt-labs/dbt_utils
    version: [">=1.1.1", "<2.0.0"]

  - package: calogica/dbt_expectations
    version: [">=0.10.0", "<0.11.0"]
```

A model:

`select 1`

A test:

```
models:
  table: foo
  columns:
      - name: measure_value
        tests:
              group_by_columms: [month, region, segment, measure_name]
```

### Dialect

Snowflake

### Version

sqlfluff: 2.3.5
python: 3.11.7

### Configuration

```
[sqlfluff]
dialect = snowflake
templater = dbt
verbose = 1

# Comma separated list of rules to exclude, or None
# See https://docs.sqlfluff.com/en/stable/configuration.html#enabling-and-disabling-rules
# AM04 (ambiguous.column_count) and ST06 (structure.column_order) are
# two of the more controversial rules included to illustrate usage.
exclude_rules = ambiguous.column_count, structure.column_order

warnings = RF04

# The standard max_line_length is 80 in line with the convention of
# other tools and several style guides. Many projects however prefer
# something a little longer.
# Set to zero or negative to disable checks.
max_line_length = 160

# CPU processes to use while linting.
# The default is "single threaded" to allow easy debugging, but this
# is often undesirable at scale.
# If positive, just implies number of processes.
# If negative or zero, implies number_of_cpus - specified_number.
# e.g. -1 means use all processors but one. 0 means all cpus.
# processes = -1

[sqlfluff:indentation]
allow_implicit_indents = True
indented_on_contents = False
indented_using_on = True
indent_unit = space
tab_space_size = 4

# The default configuration for aliasing rules is "consistent"
# which will auto-detect the setting from the rest of the file. This
# is less desirable in a new project and you may find this (slightly
# more strict) setting more useful.
[sqlfluff:rules:aliasing.table]
aliasing = explicit
[sqlfluff:rules:aliasing.column]
aliasing = explicit
[sqlfluff:rules:aliasing.length]
min_alias_length = 3

# Fully qualify JOIN clause
[sqlfluff:rules:ambiguous.join]
fully_qualify_join_types = inner

# The default configuration for capitalisation rules is "consistent"
# which will auto-detect the setting from the rest of the file. This
# is less desirable in a new project and you may find this (slightly
# more strict) setting more useful.
# Typically we find users rely on syntax highlighting rather than
# capitalisation to distinguish between keywords and identifiers.
# Clearly, if your organisation has already settled on uppercase
# formatting for any of these syntax elements then set them to "upper".
# See https://stackoverflow.com/questions/608196/why-should-i-capitalize-my-sql-keywords-is-there-a-good-reason
[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = lower
[sqlfluff:rules:capitalisation.identifiers]
capitalisation_policy = lower
[sqlfluff:rules:capitalisation.functions]
extended_capitalisation_policy = lower
[sqlfluff:rules:capitalisation.literals]
capitalisation_policy = lower
[sqlfluff:rules:capitalisation.types]
extended_capitalisation_policy = lower

# The default configuration for casting rule is consistent,
# we often use shorthand in our models.
[sqlfluff:convention:casting_style]
preferred_type_casting_style = shorthand

# Very large files can make the parser effectively hang.
# The more efficient check is the _byte_ limit check which
# is enabled by default. The previous _character_ limit check
# is still present for backward compatibility. This will be
# removed in a future version.
# Set either to 0 to disable.
large_file_skip_char_limit = 0
large_file_skip_byte_limit = 0

# dbt project configuration
# for more, see: https://docs.sqlfluff.com/en/stable/configuration.html#dbt-project-configuration
[sqlfluff:templater:dbt]
project_dir = ./
profiles_dir = ./
profile = practice_ignition

[sqlfluff:templater:jinja]
apply_dbt_builtins = True

[sqlfluff:templater:jinja:macros]
# Macros provided as builtins for dbt projects
dbt_ref = {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
dbt_source = {% macro source(source_name, table) %}{{source_name}}_{{table}}{% endmacro %}
dbt_config = {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}
dbt_var = {% macro var(variable, default='') %}item{% endmacro %}
dbt_is_incremental = {% macro is_incremental() %}True{% endmacro %}
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by friendofasquid** [comment]
Actually, I'm now seeing this error when I run dbt directly. Strange!
