### ISSUE TITLE
'CompilationException' from 'dbt.exceptions' 

### ISSUE THREAD

**Issue by moseleyi** [sqlfluff/sqlfluff#5535]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I found all the similar issues and it was said that it had been fixed but I installed everything from scratch and I get this error:

```
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\sqlfluff.exe\__main__.py", line 4, in <module>
  File "C:\Python38\lib\site-packages\sqlfluff\__init__.py", line 6, in <module>
    from sqlfluff.api import lint, fix, parse, list_rules, list_dialects
  File "C:\Python38\lib\site-packages\sqlfluff\api\__init__.py", line 4, in <module>
    from sqlfluff.api.simple import lint, fix, parse, APIParsingError
  File "C:\Python38\lib\site-packages\sqlfluff\api\simple.py", line 4, in <module>
    from sqlfluff.core import (
  File "C:\Python38\lib\site-packages\sqlfluff\core\__init__.py", line 9, in <module>
    from sqlfluff.core.linter import Linter
  File "C:\Python38\lib\site-packages\sqlfluff\core\linter\__init__.py", line 6, in <module>
    from sqlfluff.core.linter.linter import Linter
  File "C:\Python38\lib\site-packages\sqlfluff\core\linter\linter.py", line 32, in <module>
    from sqlfluff.core.rules import get_ruleset
  File "C:\Python38\lib\site-packages\sqlfluff\core\rules\__init__.py", line 12, in <module>
    for plugin_rules in get_plugin_manager().hook.get_rules():
  File "C:\Python38\lib\site-packages\sqlfluff\core\plugin\host.py", line 12, in get_plugin_manager
    pm.load_setuptools_entrypoints(project_name)
  File "C:\Python38\lib\site-packages\pluggy\_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "C:\Python38\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Python38\lib\site-packages\sqlfluff_templater_dbt\__init__.py", line 3, in <module>
    from sqlfluff_templater_dbt.templater import DbtTemplater
  File "C:\Python38\lib\site-packages\sqlfluff_templater_dbt\templater.py", line 17, in <module>
    from dbt.exceptions import (
ImportError: cannot import name 'CompilationException' from 'dbt.exceptions' (C:\Python38\lib\site-packages\dbt\exceptions.py)
```

with any command of `sqlfluff`

### Expected Behaviour

Be able to use SQLFluff

### Observed Behaviour

`'CompilationException' from 'dbt.exceptions'` error shows up with any sqlfluff command

### How to reproduce

Installed Python 3.8
Installed sqlfluff with pip
Installed dbt-core (1.7.4) and dbt-bigquery (1.7.2)

### Dialect

bigquery

### Version

I can't run it as I get an error but installed it only yesterday

### Configuration

```
[sqlfluff]
templater = dbt
sql_file_exts = .sql
dialect = bigquery

[sqlfluff:templater:dbt]
project_dir = ./

[sqlfluff:indentation]
tab_space_size = 2
indent_unit = space
indented_joins = false
indented_using_on = false
allow_implicit_indents = true
indented_on_contents = false
indented_ctes = true

[sqlfluff:rules:aliasing.table]
aliasing = explicit

[sqlfluff:rules:aliasing.column]
aliasing = explicit

[sqlfluff:rules:aliasing.length]
min_alias_length = 3

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.identifiers]
capitalisation_policy = lower

[sqlfluff:rules:capitalisation.functions]
extended_capitalisation_policy = upper

[sqlfluff:rules:capitalisation.literals]
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.types]
extended_capitalisation_policy = upper
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by fredrikaverpil** [comment]
Does it help to install setuptools?
