### ISSUE TITLE
0.4.0a1 fails with empty file

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#587]
```
Traceback (most recent call last):
  File "/Users/niallwoodward/dev/tails-analytics-dbt/.tox/sqlfluff/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/Users/niallwoodward/dev/tails-analytics-dbt/.tox/sqlfluff/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/niallwoodward/dev/tails-analytics-dbt/.tox/sqlfluff/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/niallwoodward/dev/tails-analytics-dbt/.tox/sqlfluff/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/niallwoodward/dev/tails-analytics-dbt/.tox/sqlfluff/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/niallwoodward/dev/tails-analytics-dbt/.tox/sqlfluff/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/niallwoodward/dev/tails-analytics-dbt/.tox/sqlfluff/lib/python3.8/site-packages/sqlfluff/cli/commands.py", line 320, in lint
    result = lnt.lint_paths(
  File "/Users/niallwoodward/dev/tails-analytics-dbt/.tox/sqlfluff/lib/python3.8/site-packages/sqlfluff/core/linter.py", line 1154, in lint_paths
    self.lint_path(
  File "/Users/niallwoodward/dev/tails-analytics-dbt/.tox/sqlfluff/lib/python3.8/site-packages/sqlfluff/core/linter.py", line 1135, in lint_path
    self.lint_string(
  File "/Users/niallwoodward/dev/tails-analytics-dbt/.tox/sqlfluff/lib/python3.8/site-packages/sqlfluff/core/linter.py", line 936, in lint_string
    parsed = self.parse_string(in_str=in_str, fname=fname, config=config)
  File "/Users/niallwoodward/dev/tails-analytics-dbt/.tox/sqlfluff/lib/python3.8/site-packages/sqlfluff/core/linter.py", line 748, in parse_string
    indent_balance = sum(getattr(elem, "indent_val", 0) for elem in tokens)
TypeError: 'NoneType' object is not iterable
```

**Comment by NiallRees** [comment]
Think we're unsafely trying to iterate through `token` without checking if there are any.
