### ISSUE TITLE
ValueError: 'managed_shallow_clone' is not a valid DatabricksRelationType

### ISSUE THREAD

**Issue by martindlarsson** [sqlfluff/sqlfluff#5922]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

SQLFluff crashes when I run it on my dbt project that uses Databricks adapter.

### Expected Behaviour

Linter would work without crashing

### Observed Behaviour

This is the log from when running the linter at git commit:
```
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
Traceback (most recent call last):
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/sqlfluff/cli/commands.py", line 643, in lint
    result = lnt.lint_paths(
             ^^^^^^^^^^^^^^^
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/sqlfluff/core/linter/linter.py", line 1124, in lint_paths
    for i, linted_file in enumerate(runner.run(expanded_paths, fix), start=1):
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/sqlfluff/core/linter/runner.py", line 108, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/sqlfluff/core/linter/runner.py", line 61, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/sqlfluff/core/linter/runner.py", line 48, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/sqlfluff/core/linter/linter.py", line 792, in render_file
    return self.render_string(raw_file, fname, config, encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/sqlfluff/core/linter/linter.py", line 748, in render_string
    for variant, templater_errs in self.templater.process_with_variants(
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/sqlfluff/core/templaters/jinja.py", line 952, in process_with_variants
    templated_file, violations = self.process(
                                 ^^^^^^^^^^^^^
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/sqlfluff/core/templaters/base.py", line 54, in _wrapped
    return func(self, in_str=in_str, fname=fname, config=config, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/sqlfluff_templater_dbt/templater.py", line 491, in process
    processed_result = self._unsafe_process(fname_absolute_path, in_str, config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/sqlfluff_templater_dbt/templater.py", line 661, in _unsafe_process
    with self.connection():
  File "/home/martin/.local/share/hatch/env/virtual/.pythons/3.12/python/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/sqlfluff_templater_dbt/templater.py", line 826, in connection
    adapter.set_relations_cache(self.dbt_manifest.nodes.values())
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/dbt/adapters/base/impl.py", line 523, in set_relations_cache
    self._relations_cache_for_schemas(relation_configs, required_schemas)
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/dbt/adapters/base/impl.py", line 499, in _relations_cache_for_schemas
    for relation in future.result():
                    ^^^^^^^^^^^^^^^
  File "/home/martin/.local/share/hatch/env/virtual/.pythons/3.12/python/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.local/share/hatch/env/virtual/.pythons/3.12/python/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/martin/.local/share/hatch/env/virtual/.pythons/3.12/python/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/dbt_common/utils/executor.py", line 13, in connected
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.cache/pre-commit/repoad5ra567/py_env-python3.12/lib/python3.12/site-packages/dbt/adapters/databricks/impl.py", line 238, in list_relations_without_caching
    type=self.Relation.get_relation_type(kind),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.local/share/hatch/env/virtual/.pythons/3.12/python/lib/python3.12/enum.py", line 740, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.local/share/hatch/env/virtual/.pythons/3.12/python/lib/python3.12/enum.py", line 1154, in __new__
    raise ve_exc
ValueError: 'managed_shallow_clone' is not a valid DatabricksRelationType
```
### How to reproduce

Set up a dbt project that uses Databricks adapter. The source tables are shallow clones from the original tables.

### Dialect

dbt and Databricks

### Version

SQLFluff: 3.0.7, sqlfluff-templater-dbt==3.0.7 and dbt-databricks==1.8.0

### Configuration

[sqlfluff]
dialect = databricks
templater = dbt
rules = all
exclude_rules = ST06
max_line_length = 150

[sqlfluff:templater:jinja]
apply_dbt_builtins = True

[sqlfluff:templater:dbt]
project_dir = ./
profiles_dir = .
profile = leap
target = dev

[sqlfluff:rules]
allow_scalar = True
single_table_references = consistent
unquoted_identifiers_policy = all

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.types]
extended_capitalisation_policy = upper

[sqlfluff:rules:capitalisation.identifiers]
extended_capitalisation_policy = lower

[sqlfluff:rules:capitalisation.functions]
extended_capitalisation_policy = upper

[sqlfluff:rules:capitalisation.literals]
extended_capitalisation_policy = upper

[sqlfluff:rules:convention.count_rows]
prefer_count_1 = True

ignore:
target/
dbt_packages/
macros/

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by WittierDinosaur** [comment]
Based on that stack trace, it looks like this is an issue with the dbt adapter for databricks, not sqlfluff

**Comment by martindlarsson** [comment]
Your right
