### ISSUE TITLE
pre-commit hook fails to run

### ISSUE THREAD

**Issue by nils-van-zuijlen** [sqlfluff/sqlfluff#5962]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When running the pre-commit hook `sqlfluff-fix`, sqlfluff crashed.

### Expected Behaviour

I expect it to fix my SQL or validate it.

### Observed Behaviour

```
sqlfluff-fix.............................................................Failed
- hook id: sqlfluff-fix
- exit code: 1

Traceback (most recent call last):
  File "/home/nils/.cache/pre-commit/repok4onds0n/py_env-python3.11/bin/sqlfluff", line 5, in <module>
    from sqlfluff.cli.commands import cli
  File "/home/nils/.cache/pre-commit/repok4onds0n/py_env-python3.11/lib/python3.11/site-packages/sqlfluff/__init__.py", line 6, in <module>
    import pytest
  File "/home/nils/.cache/pre-commit/repok4onds0n/py_env-python3.11/lib/python3.11/site-packages/pytest/__init__.py", line 7, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/home/nils/.cache/pre-commit/repok4onds0n/py_env-python3.11/lib/python3.11/site-packages/_pytest/assertion/__init__.py", line 11, in <module>
    from _pytest.assertion import rewrite
  File "/home/nils/.cache/pre-commit/repok4onds0n/py_env-python3.11/lib/python3.11/site-packages/_pytest/assertion/rewrite.py", line 36, in <module>
    from _pytest.assertion import util
  File "/home/nils/.cache/pre-commit/repok4onds0n/py_env-python3.11/lib/python3.11/site-packages/_pytest/assertion/util.py", line 24, in <module>
    from _pytest.config import Config
  File "/home/nils/.cache/pre-commit/repok4onds0n/py_env-python3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 59, in <module>
    import _pytest.hookspec
  File "/home/nils/.cache/pre-commit/repok4onds0n/py_env-python3.11/lib/python3.11/site-packages/_pytest/hookspec.py", line 302, in <module>
    @hookspec(
     ^^^^^^^^^
TypeError: HookspecMarker.__call__() got an unexpected keyword argument 'warn_on_impl_args'
```

### How to reproduce

Install sqlfluff in a python 3.11 repo as a pre-commit hook:

`.pre-commit-config.yaml`
```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
default_language_version:
  python: "python3.11"
repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: "3.0.7"
    hooks:
      - id: sqlfluff-fix
```

Run the pre-commit hooks: `pre-commit run -a`.

### Dialect

TSQL

### Version

Installed using pre-commit, I do not have the CLI installed.

### Configuration

```
[sqlfluff]
exclude_rules = CP02,ST06,RF04
templater = placeholder
dialect = tsql

[sqlfluff:indentation]
allow_implicit_indents = True
indented_ctes = True
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by nils-van-zuijlen** [comment]
I found issue https://github.com/pytest-dev/pytest/issues/12351 on the pytest repo with the same error message, but I do not know how they relate to each other.
