### ISSUE TITLE
Linting some files results in IndexError: list index out of range slicing error 

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#600]
Using dbt templater and 0.4.0a3. Full stacktrace:

```
Traceback (most recent call last):
  File "/Users/niallwoodward/dev/pull_requests/dbt_sqlfluff_venv/bin/sqlfluff", line 11, in <module>
    load_entry_point('sqlfluff', 'console_scripts', 'sqlfluff')()
  File "/Users/niallwoodward/dev/pull_requests/dbt_sqlfluff_venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/niallwoodward/dev/pull_requests/dbt_sqlfluff_venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/niallwoodward/dev/pull_requests/dbt_sqlfluff_venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/niallwoodward/dev/pull_requests/dbt_sqlfluff_venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/niallwoodward/dev/pull_requests/dbt_sqlfluff_venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/cli/commands.py", line 323, in lint
    ignore_files=not disregard_sqlfluffignores,
  File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/core/linter.py", line 1161, in lint_paths
    ignore_files=ignore_files,
  File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/core/linter.py", line 1139, in lint_path
    target_file.read(), fname=fname, fix=fix, config=config
  File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/core/linter.py", line 939, in lint_string
    parsed = self.parse_string(in_str=in_str, fname=fname, config=config)
  File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/core/linter.py", line 723, in parse_string
    tokens, lex_vs = lexer.lex(templated_file)
  File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/core/parser/lexer.py", line 343, in lex
    return self.enrich_segments(segment_buff, raw), violations
  File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/core/parser/lexer.py", line 373, in enrich_segments
    templated_slice
  File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/core/templaters/base.py", line 283, in templated_slice_to_source_slice
    elif start_slices[0][0] == "literal":
IndexError: list index out of range
```

**Comment by NiallRees** [comment]
Also getting:
```
Traceback (most recent call last):
  File "/Users/niallwoodward/dev/pull_requests/dbt_sqlfluff_venv/bin/sqlfluff", line 11, in <module>
    load_entry_point('sqlfluff', 'console_scripts', 'sqlfluff')()
  File "/Users/niallwoodward/dev/pull_requests/dbt_sqlfluff_venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/niallwoodward/dev/pull_requests/dbt_sqlfluff_venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/niallwoodward/dev/pull_requests/dbt_sqlfluff_venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/niallwoodward/dev/pull_requests/dbt_sqlfluff_venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/niallwoodward/dev/pull_requests/dbt_sqlfluff_venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/cli/commands.py", line 323, in lint
    ignore_files=not disregard_sqlfluffignores,
  File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/core/linter.py", line 1161, in lint_paths
    ignore_files=ignore_files,
  File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/core/linter.py", line 1139, in lint_path
    target_file.read(), fname=fname, fix=fix, config=config
  File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/core/linter.py", line 939, in lint_string
    parsed = self.parse_string(in_str=in_str, fname=fname, config=config)
  File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/core/linter.py", line 723, in parse_string
    tokens, lex_vs = lexer.lex(templated_file)
  File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/core/parser/lexer.py", line 343, in lex
    return self.enrich_segments(segment_buff, raw), violations
  File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/core/parser/lexer.py", line 373, in enrich_segments
    templated_slice
  File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/core/templaters/base.py", line 257, in templated_slice_to_source_slice
    template_slice.stop, inclusive=False
  File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/core/templaters/base.py", line 184, in _find_slice_indices_of_templated_pos
    raise ValueError("Position Not Found")
ValueError: Position Not Found
```

on another file. Interestingly, both are test sql files, as in dbt data tests, defined in the project with `test-paths`.

**Comment by NiallRees** [comment]
Progress!

A file `failing.sql` with the contents `select * from a` results in the `IndexError: list index out of range` error when defined as a data test in the `test-paths`, however the same file defined in a model directory passes. Same file, just different directory.

@dmateusp did you try the dbt templater with dbt tests? Tomorrow I'll see if I can reproduce this bug in a test in the sqlfluff repo in the dbt_project fixture.

**Comment by dmateusp** [comment]
Ah good catch! we actually don't use data tests at Earnest because our dbt project is quite new and we also use Great Expectations. (we use the out of the box schema tests)
So I completely forgot to test data tests :(

**Comment by NiallRees** [comment]
> Ah good catch! we actually don't use data tests at Earnest because our dbt project is quite new and we also use Great Expectations. (we use the out of the box schema tests)
> So I completely forgot to test data tests :(

No worries! Great expectations is arguably a lot more useful imo. I managed to reproduce the exact error in the PR after a bit of wrestling 😅

**Comment by NiallRees** [comment]
New error on a non-test file, but likely the same issue:

```
Traceback (most recent call last):
  File "/Users/niallwoodward/.local/share/virtualenvs/data_warehouse-5lmQyzNX/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/Users/niallwoodward/.local/share/virtualenvs/data_warehouse-5lmQyzNX/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/niallwoodward/.local/share/virtualenvs/data_warehouse-5lmQyzNX/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/niallwoodward/.local/share/virtualenvs/data_warehouse-5lmQyzNX/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/niallwoodward/.local/share/virtualenvs/data_warehouse-5lmQyzNX/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/niallwoodward/.local/share/virtualenvs/data_warehouse-5lmQyzNX/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/niallwoodward/.local/share/virtualenvs/data_warehouse-5lmQyzNX/lib/python3.8/site-packages/sqlfluff/cli/commands.py", line 320, in lint
    result = lnt.lint_paths(
  File "/Users/niallwoodward/.local/share/virtualenvs/data_warehouse-5lmQyzNX/lib/python3.8/site-packages/sqlfluff/core/linter.py", line 1274, in lint_paths
    self.lint_path(
  File "/Users/niallwoodward/.local/share/virtualenvs/data_warehouse-5lmQyzNX/lib/python3.8/site-packages/sqlfluff/core/linter.py", line 1251, in lint_path
    self.lint_string(
  File "/Users/niallwoodward/.local/share/virtualenvs/data_warehouse-5lmQyzNX/lib/python3.8/site-packages/sqlfluff/core/linter.py", line 1043, in lint_string
    parsed = self.parse_string(in_str=in_str, fname=fname, config=config)
  File "/Users/niallwoodward/.local/share/virtualenvs/data_warehouse-5lmQyzNX/lib/python3.8/site-packages/sqlfluff/core/linter.py", line 815, in parse_string
    tokens, lex_vs = lexer.lex(templated_file)
  File "/Users/niallwoodward/.local/share/virtualenvs/data_warehouse-5lmQyzNX/lib/python3.8/site-packages/sqlfluff/core/parser/lexer.py", line 343, in lex
    return self.enrich_segments(segment_buff, raw), violations
  File "/Users/niallwoodward/.local/share/virtualenvs/data_warehouse-5lmQyzNX/lib/python3.8/site-packages/sqlfluff/core/parser/lexer.py", line 372, in enrich_segments
    source_slice = templated_file.templated_slice_to_source_slice(
  File "/Users/niallwoodward/.local/share/virtualenvs/data_warehouse-5lmQyzNX/lib/python3.8/site-packages/sqlfluff/core/templaters/base.py", line 289, in templated_slice_to_source_slice
    if stop_slices[-1][0] == "literal":
IndexError: list index out of range
```

**Comment by NiallRees** [comment]
Hope you don't mind me assigning this to you @alanmcruickshank, there's an open PR which recreates the first issue here https://github.com/sqlfluff/sqlfluff/pull/603

**Comment by alanmcruickshank** [comment]
I think the comment I added to #603 about slicing and the missing bits is probably spot on in what's causing this issue. The templating code wasn't designed to deal with query *wrapping* like this because the bits aren't in the source at all.

@NiallRees - want me to pick this up or are those pointers enough for you to have a go?

**Comment by NiallRees** [comment]
@alanmcruickshank Happy to have a go myself, though it won't be for a few days likely. If you get there first I'm happy with that too :)

**Comment by NiallRees** [comment]
Having just looked a bit further into the code - I think it will take me so long to get my head around it it might not be worth it as you wrote it relatively recently. I'll keep my efforts focused where I can contribute more effectively for now - you ok to pick this one up?
