### ISSUE TITLE
Double quote table name followed by `ON` clause without space results in error even with ignore parsing

### ISSUE THREAD

**Issue by Sherm4nLC** [sqlfluff/sqlfluff#607]
One of the lines I have been linting has the following statement (note missing space between table name and `ON`

`INNER JOIN "my_dababase"."my_schema"."my_table"ON [...]`

This runs on Redshift, possibly also on postgres, however when linting with the command

`sqlfluff lint myfile.sql --ignore parsing --dialect postgres`

...I get the following error

```
Traceback (most recent call last):
  File "/home/sherm4nlc/redshift-warehouse-structure/env/bin/sqlfluff", line 11, in <module>
    load_entry_point('sqlfluff==0.3.6', 'console_scripts', 'sqlfluff')()
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/cli/commands.py", line 172, in lint
    result = lnt.lint_paths(paths, verbosity=verbose, ignore_non_existent_files=False)
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/linter.py", line 911, in lint_paths
    result.add(self.lint_path(path, verbosity=verbosity, fix=fix,
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/linter.py", line 896, in lint_path
    self.lint_string(target_file.read(), fname=fname,
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/linter.py", line 713, in lint_string
    parsed, vs, time_dict = self.parse_string(s=s, fname=fname, verbosity=verbosity, config=config)
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/linter.py", line 647, in parse_string
    parsed = file_segment.parse(parse_context=context)
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/parser/segments_base.py", line 456, in parse
    self.segments = self.expand(
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/parser/segments_base.py", line 703, in expand
    res = stmt.parse(parse_context=parse_context)
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/parser/segments_base.py", line 456, in parse
    self.segments = self.expand(
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/parser/segments_base.py", line 703, in expand
    res = stmt.parse(parse_context=parse_context)
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/parser/segments_base.py", line 456, in parse
    self.segments = self.expand(
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/parser/segments_base.py", line 703, in expand
    res = stmt.parse(parse_context=parse_context)
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/parser/segments_base.py", line 456, in parse
    self.segments = self.expand(
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/parser/segments_base.py", line 703, in expand
    res = stmt.parse(parse_context=parse_context)
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/parser/segments_base.py", line 409, in parse
    m = g._match(
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/parser/grammar.py", line 108, in _match
    m = self.match(segments, parse_context=parse_context)
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/parser/grammar.py", line 1113, in match
    elem_match = elem._match(
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/parser/grammar.py", line 108, in _match
    m = self.match(segments, parse_context=parse_context)
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/parser/grammar.py", line 1229, in match
    pre_content, delimiter_match, m = self._bracket_sensitive_look_ahead_match(
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/parser/grammar.py", line 530, in _bracket_sensitive_look_ahead_match
    pre, match, matcher = cls._look_ahead_match(
  File "/home/sherm4nlc/redshift-warehouse-structure/env/lib/python3.8/site-packages/sqlfluff/parser/grammar.py", line 355, in _look_ahead_match
    raise ValueError(
ValueError: Segment matched in simple parsing, but failed later. Report this.
```

Adding the space prior to the `ON` clause seems to allow sqlfluff to run

**Comment by alanmcruickshank** [comment]
Thanks for posting this @Sherm4nLC . I *think* this should be possible to fix 👍 . I'll have a play with the lexer....
