### ISSUE TITLE
sqlfluff fix with dbt templater doesn't in subdirectories and processes > 1

### ISSUE THREAD

**Issue by eschrock** [sqlfluff/sqlfluff#6188]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Attempting to use sqlfluf with the dbt template fails:

```Traceback (most recent call last):
  File "/root/.cache/pre-commit/repo3n6osu3e/py_env-python3.12/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/root/.cache/pre-commit/repo3n6osu3e/py_env-python3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pre-commit/repo3n6osu3e/py_env-python3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/.cache/pre-commit/repo3n6osu3e/py_env-python3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pre-commit/repo3n6osu3e/py_env-python3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pre-commit/repo3n6osu3e/py_env-python3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pre-commit/repo3n6osu3e/py_env-python3.12/lib/python3.12/site-packages/sqlfluff/cli/commands.py", line 1108, in fix
    _paths_fix(
  File "/root/.cache/pre-commit/repo3n6osu3e/py_env-python3.12/lib/python3.12/site-packages/sqlfluff/cli/commands.py", line 879, in _paths_fix
    result: LintingResult = linter.lint_paths(
                            ^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pre-commit/repo3n6osu3e/py_env-python3.12/lib/python3.12/site-packages/sqlfluff/core/linter/linter.py", line 1048, in lint_paths
    linted_file.persist_tree(
  File "/root/.cache/pre-commit/repo3n6osu3e/py_env-python3.12/lib/python3.12/site-packages/sqlfluff/core/linter/linted_file.py", line 383, in persist_tree
    self._safe_create_replace_file(
  File "/root/.cache/pre-commit/repo3n6osu3e/py_env-python3.12/lib/python3.12/site-packages/sqlfluff/core/linter/linted_file.py", line 417, in _safe_create_replace_file
    with tempfile.NamedTemporaryFile(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/tempfile.py", line 582, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/tempfile.py", line 579, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/dbt/nightly/dbt/nightly/models/***'
```

### Expected Behaviour

sqlfluff will correctly fix issues

### Observed Behaviour

sqlfluff fails while trying to fix issues

### How to reproduce

The issue can be seen in the path, where there is a duplicate `dbt/nightly` (`/usr/src/dbt/nightly/dbt/nightly/models...`). Adding some debug print statements, I can see that sometimes the cwd is `/usr/src` and other times it's `/usr/src/dbt/nightly`). Looking at the dbt  templater code, it does a `chdir()` in the `process()` function:

```
        try:
            os.chdir(self.project_dir)
            processed_result = self._unsafe_process(fname_absolute_path, in_str, config)
...
        finally:
            os.chdir(self.working_dir)
```

The failure was not predictable, failing in different places on runs. This, combined with other debugging print statements, made me suspect parallelism. The concept of current working directory is a process-wide concept, so if one thread changes the working directory, it will affect others in the same process. I tried to dissect the runner parallelism but couldn't really figure out how it was working. But I did determine if I set `--processes 1` on the command line, the problem went away. So it seems like parallelism is fundamentally broken with the dbt templater if you have dbt projects in a subdirectory. Since it's not predictable, you'll need multiple files needing fixes and those not (we have >300 SQL models).   

### Dialect

snowflake with dbt templater

### Version

```
$ sqlfluff --version
sqlfluff, version 3.1.1
$ python --version
Python 3.12.6
```

### Configuration

[sqlfluff]
templater = dbt
runaway_limit = 10
max_line_length = 240
indent_unit = space
dialect = snowflake

# Keywords as references is overly strict (e.g. "start_timestamp" is flagged)
# Column ordering can break set operations and doesn't let us group semantically relevant things together
# Ambiguous column references seem to generate false positives for no apparent reason
# Consistent casting is over constraining as ::string is convenient, but sometimes you also need to_decimal() with arguments
# Forcing an extra empty newline is not really necessary and just adds noise
exclude_rules = references.keywords, structure.column_order, ambiguous.column_references, convention.casting_style, layout.end_of_file

[sqlfluff:templater:dbt]
project_dir = ./dbt/nightly
profiles_dir = ./dbt/nightly

[sqlfluff:indentation]
tab_space_size = 4
indented_joins = True
indented_using_on = False
allow_implicit_indents = True

[sqlfluff:layout:type:comma]
spacing_before = touch
line_position = trailing

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = lower

[sqlfluff:rules:aliasing.table]
aliasing = explicit

[sqlfluff:rules:aliasing.column]
aliasing = explicit

[sqlfluff:rules:aliasing.expression]
allow_scalar = False

[sqlfluff:rules:capitalisation.identifiers]
extended_capitalisation_policy = lower

[sqlfluff:rules:capitalisation.functions]
extended_capitalisation_policy = lower

[sqlfluff:rules:capitalisation.literals]
capitalisation_policy = lower

[sqlfluff:rules:ambiguous.column_references]  # Number in group by
group_by_and_order_by_style = implicit

[sqlfluff:rules:capitalisation.types]
extended_capitalisation_policy = lower

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by wircho** [comment]
@eschrock Have you figured out the cause of this issue, or a workaround?

**Comment by alanmcruickshank** [comment]
It sounds like this might be similar to #3849 and #2848. Thanks for the debugging you've done! I hadn't appreciated that `chdir()` might be the cause - but that fits very much with the pattern of failure.

In theory, that part of the code should only be executed in the main thread, but I'm realising that isn't necessarily reliable.

**Comment by alonsopdani** [comment]
Hello! Any news about this issue? Thanks.

**Comment by keraion** [comment]
This should be resolved by #7029
