### ISSUE TITLE
dbt_utils.union_relation generates unparsable section error

### ISSUE THREAD

**Issue by sziolko** [sqlfluff/sqlfluff#629]
The current (0.6.2) dbt_utils package has a union_relations macro. 

When used with the dbt templater in sqlfluff the following error is displayed (0.4.0a3 sqlfluff build).

== [models/staging/test/union_test.sql] FAIL
L:   7 | P:   9 |  PRS | Found unparsable section: '(\n select\n\n ca...'

The toy example setup in this case was three files:
test_a.sql
```
{{ config(materialized='view') }}
SELECT 
  'a' AS alpha,
  0 AS amount
```

test_b.sql
```
{{ config(materialized='view') }}
SELECT 
  1 AS amount
```

union_test.sql
```
WITH

test_events AS (

  {{ dbt_utils.union_relations(
      relations=[
       ref('test_a'),
       ref('test_b')
      ],
      include=[
        "alpha",
        "amount"
      ]
    )
  }}

)

SELECT
  alpha,
  amount
FROM test_events
```

Then run: 
`dbt run --models +union_test` (the union_relations macro requires views or materialized tables to exist to perform the union)

After that the `sqlfluff lint models/staging/test` command produces the error above.

Error from a similar, but more complicated production model:
```
Traceback (most recent call last):
  File "/usr/local/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/cli/commands.py", line 323, in lint
    ignore_files=not disregard_sqlfluffignores,
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/core/linter.py", line 1278, in lint_paths
    ignore_files=ignore_files,
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/core/linter.py", line 1252, in lint_path
    target_file.read(), fname=fname, fix=fix, config=config
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/core/linter.py", line 1043, in lint_string
    parsed = self.parse_string(in_str=in_str, fname=fname, config=config)
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/core/linter.py", line 797, in parse_string
    in_str=in_str, fname=fname, config=config
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/core/templaters/dbt.py", line 181, in process
    return self._unsafe_process(fname, in_str, config)
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/core/templaters/dbt.py", line 227, in _unsafe_process
    raw_sliced, sliced_file = self.slice_file(node.raw_sql, node.injected_sql)
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/core/templaters/python.py", line 284, in slice_file
    split_sliced, raw_occurrences, templated_occurances, templated_str
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/core/templaters/python.py", line 808, in _split_uniques_coalesce_rest
    "        Attempting Subsplit [post]: %s", sub_section
UnboundLocalError: local variable 'sub_section' referenced before assignment
```

**Comment by dmateusp** [comment]
Thanks for reporting the issue @sziolko would you mind pasting the SQL that was compiled by dbt? You can find it under `target/compiled/`

**Comment by dmateusp** [comment]
Could you also share which dialect you are using ?

**Comment by sziolko** [comment]
`dialect: postgres`

generated sql
```
WITH

test_events AS (

  

        (
            select

                cast('"warehouse"."dbt_sziolko_dbt_staging"."test_a"' as varchar) as _dbt_source_relation,
                
                    cast("alpha" as character varying(1)) as "alpha" ,
                    cast("amount" as integer) as "amount" 

            from "warehouse"."dbt_sziolko_dbt_staging"."test_a"
        )

        union all
        

        (
            select

                cast('"warehouse"."dbt_sziolko_dbt_staging"."test_b"' as varchar) as _dbt_source_relation,
                
                    cast(null as character varying(1)) as "alpha" ,
                    cast("amount" as integer) as "amount" 

            from "warehouse"."dbt_sziolko_dbt_staging"."test_b"
        )

        

)

SELECT
  alpha,
  amount  
FROM test_events
```

**Comment by NiallRees** [comment]
I've just tested this query and it seems to now parse fine in 0.4.0. If that's still not the case for you let me know and we can work it out!
