### ISSUE TITLE
UnboundLocalError: local variable 'sub_section' referenced before assignment

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#630]
From slack:

```
Traceback (most recent call last):
  File "/usr/local/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/cli/commands.py", line 323, in lint
    ignore_files=not disregard_sqlfluffignores,
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/core/linter.py", line 1278, in lint_paths
    ignore_files=ignore_files,
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/core/linter.py", line 1252, in lint_path
    target_file.read(), fname=fname, fix=fix, config=config
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/core/linter.py", line 1043, in lint_string
    parsed = self.parse_string(in_str=in_str, fname=fname, config=config)
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/core/linter.py", line 797, in parse_string
    in_str=in_str, fname=fname, config=config
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/core/templaters/dbt.py", line 181, in process
    return self._unsafe_process(fname, in_str, config)
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/core/templaters/dbt.py", line 227, in _unsafe_process
    raw_sliced, sliced_file = self.slice_file(node.raw_sql, node.injected_sql)
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/core/templaters/python.py", line 284, in slice_file
    split_sliced, raw_occurrences, templated_occurances, templated_str
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/core/templaters/python.py", line 808, in _split_uniques_coalesce_rest
    "        Attempting Subsplit [post]: %s", sub_section
UnboundLocalError: local variable 'sub_section' referenced before assignment
```

Scott Ziolko  1 day ago
the simplest logic in one of these instances that errors is basically:
```
WITH 
foo AS (
  {{ dbt_utils.union_relations( relations=[ ref('a'), ref('b')], include=["x","y","z"]) }}
)
SELECT x, y, COALESCE(z, 'default_value') AS z
FROM foo
```

I (Niall) also just ran into the same bug.

**Comment by optroodt** [comment]
Running into this issue too. I need to reduce the 350 line sql file to the simplest form in which the error occurs. Will report back!

**Comment by alanmcruickshank** [comment]
I'm having real trouble recreating this error locally, but I think it's because the `union_relations` macro requires a database to query and so my test examples aren't compiling at all.

To debug this could someone confirm the error with a relatively simple query, then post both the sql file *and the compiled version of the file* which is created with `dbt compile`. With those two sets of sql I'll be able to debug the issue without needing a connection to a backend. 👍 

This issue is coming from the code which uses the raw and the templated sql to slice it up into bits.

**Comment by tunetheweb** [comment]
Closing as not heard anything back. Can reopen if we get feedback.
