### ISSUE TITLE
Applying rule L031 threw an Exception: 'NoneType' object has no attribute 'raw' 

### ISSUE THREAD

**Issue by emekdahl** [sqlfluff/sqlfluff#635]
Rule L031 throws an exception: 

The offending line 3:
`SELECT ID::VARCHAR as id,`

```
(base) ➜  sqlfluff lint models/staging/dw/intermediate/offer_usage.sql
CRITICAL   [L031] Applying rule L031 threw an Exception: 'NoneType' object has no attribute 'raw' 
Traceback (most recent call last):
  File "/Users/emekdahl/opt/anaconda3/lib/python3.8/site-packages/sqlfluff/core/rules/base.py", line 282, in crawl
    res = self._eval(
  File "/Users/emekdahl/opt/anaconda3/lib/python3.8/site-packages/sqlfluff/core/rules/std.py", line 3110, in _eval
    self._lint_aliases_in_join(
  File "/Users/emekdahl/opt/anaconda3/lib/python3.8/site-packages/sqlfluff/core/rules/std.py", line 3133, in _lint_aliases_in_join
    and base_table.raw == table_ref.raw
AttributeError: 'NoneType' object has no attribute 'raw'
== [models/staging/fetchdw/intermediate/offer_usage.sql] FAIL
L:   3 | P:   1 | L031 | Unexpected exception: 'NoneType' object has no attribute
                       | 'raw'; Could you open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '--noqa: L031'
                       | at the end of line 3
```

.sqlfluff

```
[sqlfluff]
templater = dbt
dialect = snowflake
exclude_rules = L009,L010
```

.sqlfluffignore

```
target/
dbt_modules/
macros/
```

**Comment by pwildenhain** [comment]
Thanks for submitting this -- can you post the first like 5-10 lines of your query for testing purposes?

**Comment by NiallRees** [comment]
What @pwildenhain said, but please include the `from` clause and any joins as there's something in there which is throwing things off!

**Comment by emekdahl** [comment]
Thanks! @pwildenhain @NiallRees ! Here's the query you requested. 
```
{{ config(materialized = 'ephemeral') }}

SELECT
    ID::VARCHAR AS id,
    OBJ:userId::VARCHAR AS user_id,
    OBJ:offerId::VARCHAR AS offer_id,
    redemptions.value:awardedReceiptId::VARCHAR AS awarded_receipt_id,
    TO_TIMESTAMP(
        redemptions.value:awardedDate:"$date"::INT / 1000
    ):: TIMESTAMP AS awarded_date,
    redemptions.value:pointsAwarded::NUMBER AS points_awarded,
    redemptions.value:contributingReceipts::VARIANT AS contributing_receipts
    FROM
        {{ source('fastpipe', 'OFFER_USAGE') }} AS source,
        LATERAL FLATTEN(input => source.OBJ:redemptions) redemptions
```

**Comment by NiallRees** [comment]
Thanks @emekdahl - I'll try and reproduce the error and work out what's going on! Out of curiosity, how come you're casting value:awardedDate to a timestamp twice? Is that deliberate?

**Comment by emekdahl** [comment]
@NiallRees I wondered the same myself. I recently because responsible for maintaining and extending this code as one of my teammates transitioned off the team. I don't know the answer right now but I can ask a teammate for clarification.
