### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by jars** [sqlfluff/sqlfluff#641]
Hello sqlfluff devs! :sheep:

Even with `recurse = 0` config setting (no limit), we are getting the following error on `sqlfluff lint -vvvv .`

```bash
root@ac590e6ff46d:/app# sqlfluff lint -vvvvv .
==== sqlfluff ====
sqlfluff:         0.4.0a3 python:             3.8.5
dialect:         bigquery verbosity:              5
== Raw Config:
core:                                   
    bench:              False               
    dialect:            bigquery            
    ignore:             []                  
    nocolor:            False               
    output_line_length: 80                  
    recurse:            True                
    runaway_limit:      10                  
    templater:          dbt                 
    verbose:            5                   
indentation:                            
    indented_joins:     False               
    template_blocks_indent:True                
rules:                                  
    allow_scalar:       True                
    comma_style:        trailing            
    indent_unit:        space               
    max_line_length:    80                  
    only_aliases:       True                
    single_table_references:consistent          
    tab_space_size:     2                   
    L003:                                   
        lint_templated_tokens:True                
    L010:                                   
        capitalisation_policy:upper               
    L014:                                   
        capitalisation_policy:consistent          
    L029:                                   
        only_aliases:       False               
    L030:                                   
        capitalisation_policy:consistent          
templater:                              
    jinja:                                  
        apply_dbt_builtins: True                
        load_macros_from_path:/app/macros         
        macros:                                 
            dbt_config:         {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}
            dbt_is_incremental: {% macro is_incremental() %}True{% endmacro %}
            dbt_ref:            {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
            dbt_source:         {% macro source(source_name, table) %}{{source_name}}_{{table}}{% endmacro %}
            dbt_var:            {% macro var(variable) %}item{% endmacro %}

==== readout ====

=== [ path: . ] ===

== [analysis/dir1/dir1/file.sql] PARSING
INFO       TEMPLATING RAW [dbt] (analysis/dir1/dir2/file.sql)
...
...
...
L:1013 | P:   5 | L003 | Indentation not consistent with line #903
L:1014 | P:   5 | L003 | Indentation not consistent with line #903
Traceback (most recent call last):
  File "/usr/local/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1025, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 955, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1517, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1279, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 710, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/cli/commands.py", line 320, in lint
    result = lnt.lint_paths(
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/linter.py", line 1274, in lint_paths
    self.lint_path(
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/linter.py", line 1251, in lint_path
    self.lint_string(
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/linter.py", line 1043, in lint_string
    parsed = self.parse_string(in_str=in_str, fname=fname, config=config)
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/linter.py", line 796, in parse_string
    templated_file, templater_violations = self.templater.process(
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/templaters/dbt.py", line 181, in process
    return self._unsafe_process(fname, in_str, config)
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/templaters/dbt.py", line 227, in _unsafe_process
    raw_sliced, sliced_file = self.slice_file(node.raw_sql, node.injected_sql)
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/templaters/python.py", line 282, in slice_file
    sliced_file = list(
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/templaters/python.py", line 600, in _split_uniques_coalesce_rest
    yield from cls._split_uniques_coalesce_rest(
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/templaters/python.py", line 600, in _split_uniques_coalesce_rest
    yield from cls._split_uniques_coalesce_rest(
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/templaters/python.py", line 600, in _split_uniques_coalesce_rest
    yield from cls._split_uniques_coalesce_rest(
  [Previous line repeated 975 more times]
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/templaters/python.py", line 486, in _split_uniques_coalesce_rest
    head_buffer, int_file_slice, tail_buffer = int_file_slice.trim_ends(
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/templaters/python.py", line 117, in trim_ends
    new_slice, head_buffer = self._trim_end(
  File "/usr/local/lib/python3.8/dist-packages/sqlfluff/core/templaters/python.py", line 105, in _trim_end
    new_intermediate = self.__class__(
  File "<string>", line 1, in __new__
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by barrywhart** [comment]
Can you provide a `file.sql` that reproduces this issue?

**Comment by cnolanminich** [comment]
came across this issue, and here is an example that reproduces this error (this is on `sqlfluff 0.4.0` alpha but it's the same behavior).

The SQL is ugly but it's something I've come across within my org several times.

```sql
 select
        1
    from
        test_table
    where
        test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%' --5
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%' -- 10
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%' -- 15
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%' -- 20
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%' --30
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%'
        or test_table.string_field like 'some string%' -- 40
```

**Comment by barrywhart** [comment]
@cnolanminich: Thanks for the example SQL. Can you provide a stack trace for the error you're getting? I think there may be more than one issue resulting in `RecursionError`. Your SQL query looks like one in this other issue, #669. Note the difference between the stack traces there and here...
* This one has a bunch of `_split_uniques` calls in the stack.
* The other issue has a bunch of `wrapped_match_method` calls in the stack.

**Comment by alanmcruickshank** [comment]
Great example query @cnolanminich  - I can replicate the issue on my machine. I'll pick this one up, I think it's going to involve some fairly deep surgery in the new source mapping code.
