### ISSUE TITLE
Parser crash using test query from issue #356

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#653]
Today I tested the first query in #356 using the latest code in `master`:
```
select ts from unnest(generate_timestamp_array('2020-01-01', '2020-01-30', interval 1 day)) as ts
```

The parse crashed with:

```
Traceback (most recent call last):
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/core/rules/base.py", line 289, in crawl
    dialect=dialect,
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/core/rules/std.py", line 3120, in _eval
    segment,
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/core/rules/std.py", line 3177, in _lint_aliases_in_join
    for alias in [alias_identifier_ref, *ids_refs]
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/core/rules/std.py", line 3177, in <listcomp>
    for alias in [alias_identifier_ref, *ids_refs]
AttributeError: 'NoneType' object has no attribute 'raw'
```

**Comment by GeoffTK** [comment]
I am seeing the same thing when using this test
```
SELECT
    y AS woy
FROM
    UNNEST(GENERATE_ARRAY(1, 53)) AS y
```

I first noticed it in a lot of my sql files and then tried to use this simple example and still get an error.

This looks like it is specifically an error in 0.4.0a3, and works in 3.

**Comment by NiallRees** [comment]
Yup these are both resolved by https://github.com/sqlfluff/sqlfluff/issues/653
