### ISSUE TITLE
Rule L014 does not recognize capitalisation_policy = capitalise

### ISSUE THREAD

**Issue by Elliot2718** [sqlfluff/sqlfluff#662]
## Expected Behaviour
The [documentation ](https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.rules.std.Rule_L014) states that rule L014 should allow 'capitalise' as a parameter.

## Observed Behaviour
Using 'capitalise' as a parameter results in a ValueError, while using any one of ‘consistent’, ‘upper’, or ‘lower’ is successful.

## Steps to Reproduce

Create a file called `test.sql` containing:
```sql
select a
from mytable
```

Create a `.sqlfluff` configuration file containing: 
```
[sqlfluff:rules:L014]
capitalisation_policy = capitalise
```

Run the lint command:
```
>sqlfluff lint test.sql
Traceback (most recent call last):
  File "C:\Users\ELWARG\AppData\Local\Programs\Python\Python3.8.6\Scripts\sqlfluff-script.py", line 33, in <module>
    sys.exit(load_entry_point('sqlfluff==0.3.6', 'console_scripts', 'sqlfluff')())
  File "c:\users\elwarg\appdata\local\programs\python\python3.8.6\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\elwarg\appdata\local\programs\python\python3.8.6\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\elwarg\appdata\local\programs\python\python3.8.6\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\elwarg\appdata\local\programs\python\python3.8.6\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\elwarg\appdata\local\programs\python\python3.8.6\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\elwarg\appdata\local\programs\python\python3.8.6\lib\site-packages\sqlfluff\cli\commands.py", line 172, in lint
    result = lnt.lint_paths(paths, verbosity=verbose, ignore_non_existent_files=False)
  File "c:\users\elwarg\appdata\local\programs\python\python3.8.6\lib\site-packages\sqlfluff\linter.py", line 911, in lint_paths
    result.add(self.lint_path(path, verbosity=verbosity, fix=fix,
  File "c:\users\elwarg\appdata\local\programs\python\python3.8.6\lib\site-packages\sqlfluff\linter.py", line 896, in lint_path
    self.lint_string(target_file.read(), fname=fname,
  File "c:\users\elwarg\appdata\local\programs\python\python3.8.6\lib\site-packages\sqlfluff\linter.py", line 748, in lint_string
    lerrs, _, _, _ = crawler.crawl(parsed, dialect=config.get('dialect_obj'))
  File "c:\users\elwarg\appdata\local\programs\python\python3.8.6\lib\site-packages\sqlfluff\rules\base.py", line 268, in crawl
    dvs, raw_stack, child_fixes, memory = self.crawl(
  File "c:\users\elwarg\appdata\local\programs\python\python3.8.6\lib\site-packages\sqlfluff\rules\base.py", line 268, in crawl
    dvs, raw_stack, child_fixes, memory = self.crawl(
  File "c:\users\elwarg\appdata\local\programs\python\python3.8.6\lib\site-packages\sqlfluff\rules\base.py", line 268, in crawl
    dvs, raw_stack, child_fixes, memory = self.crawl(
  [Previous line repeated 3 more times]
  File "c:\users\elwarg\appdata\local\programs\python\python3.8.6\lib\site-packages\sqlfluff\rules\base.py", line 233, in crawl
    res = self._eval(
  File "c:\users\elwarg\appdata\local\programs\python\python3.8.6\lib\site-packages\sqlfluff\rules\std.py", line 1171, in _eval
    LintFix('edit', segment, make_replacement(
  File "c:\users\elwarg\appdata\local\programs\python\python3.8.6\lib\site-packages\sqlfluff\rules\std.py", line 1145, in make_replacement
    raise ValueError("Unexpected capitalisation policy: {0!r}".format(policy))
ValueError: Unexpected capitalisation policy: 'capitalise'
```

This results in an error. Now update the `.sqlfluff` file to:
```
[sqlfluff:rules:L014]
capitalisation_policy = upper
```

This results in a successful (failed) lint check:
```
>sqlfluff lint test.sql
== [test.sql] FAIL
L:   1 | P:   8 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:   2 | P:   6 | L014 | Inconsistent capitalisation of unquoted identifiers.
```

## Version
```
>python --version
Python 3.8.6

>sqlfluff --version
sqlfluff, version 0.3.6
```

**Comment by pwildenhain** [comment]
Can you try upgrading to the latest pre-release `pip install --pre sqlfluff` and see if the issue perisits?

**Comment by Elliot2718** [comment]
@pwildenhain thanks for looking at this. Yes, that solves the issue. 

I upgraded to the pre-release: `pip install --upgrade sqlfluff --pre` 

and it ran:

```PS C:\Users\elwarg\Documents\python\sql_fluff_testing> sqlfluff lint test.sql
== [test.sql] FAIL
L:   1 | P:   8 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:   2 | P:   6 | L014 | Inconsistent capitalisation of unquoted identifiers.```

I think you can close this (or do I)?

**Comment by pwildenhain** [comment]
Great, glad it's working for you -- feel free to close it out 👍

**Comment by Elliot2718** [comment]
Closing this based on above conversation.
