### ISSUE TITLE
dbt templater incompatible with dbt 0.19

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#715]
Using SQLFluff 0.4.0a3 with the dbt templater and dbt 0.19 leads to the following error when running `sqlfluff lint`:

```
Traceback (most recent call last):
  File "/usr/local/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/cli/commands.py", line 320, in lint
    result = lnt.lint_paths(
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/linter.py", line 1274, in lint_paths
    self.lint_path(
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/linter.py", line 1251, in lint_path
    self.lint_string(
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/linter.py", line 1043, in lint_string
    parsed = self.parse_string(in_str=in_str, fname=fname, config=config)
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/linter.py", line 796, in parse_string
    templated_file, templater_violations = self.templater.process(
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/templaters/dbt.py", line 181, in process
    return self._unsafe_process(fname, in_str, config)
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/templaters/dbt.py", line 212, in _unsafe_process
    selected = self.dbt_selector_method.search(
  File "/usr/local/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/templaters/dbt.py", line 111, in dbt_selector_method
    self.dbt_manifest, previous_state=None
  File "/usr/local/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/templaters/dbt.py", line 92, in dbt_manifest
    self.dbt_manifest = load_manifest(
  File "/usr/local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 854, in load_manifest
    return ManifestLoader.load_all(config, macro_manifest, macro_hook)
  File "/usr/local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 444, in load_all
    loader.track_project_load()
  File "/usr/local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 159, in track_project_load
    invocation_id = dbt.tracking.active_user.invocation_id
AttributeError: 'NoneType' object has no attribute 'invocation_id'
```

**Comment by NiallRees** [comment]
For anyone looking for a workaround, I suggest using tox where you can specify a test environment with dbt pinned to an older, working version (0.18.0 being the most recent).

```
[testenv]
deps =
  sqlfluff == 0.4.0a3
  dbt == 0.18.0

commands=
  sqlfluff --version
  dbt --version
  sqlfluff lint --ignore parsing -v
```

**Comment by alanmcruickshank** [comment]
@NiallRees - I can definitely confirm I'm experiencing this too. Any suggestions on how we handle this? Do we need to raise a big report with the dbt folks?

**Comment by NiallRees** [comment]
> @NiallRees - I can definitely confirm I'm experiencing this too. Any suggestions on how we handle this? Do we need to raise a big report with the dbt folks?

I think first step is to add a version check in the dbt templater so we explicitly handle this rather than the current dbt 'invocation_id' error. They must have changed the methods in dbt 0.19.0, and as dbt only officially support interaction through the cli I think it's on us rather than them to resolve. Hopefully shouldn't be too complicated to overcome though. I'll investigate this weekend.

**Comment by NiallRees** [comment]
> @NiallRees - I can definitely confirm I'm experiencing this too. Any suggestions on how we handle this? Do we need to raise a big report with the dbt folks?

Ok this is weird. I was having some issues with my python environment so totally uninstalled python and reinstalled (pyenv). I'm now using the latest commit on master with dbt 0.19.0 without issue!

**Comment by barrywhart** [comment]
On rare occasions, I've wondered if I may have a corrupt "compiled" Python file sitting around. Recently, I helped somebody with a wacky pre-commit issue (unrelated to SQLFluff) that went away after we forced pre-commit to re-download all the hook tools. 😬

**Comment by NiallRees** [comment]
I'm going to close this as we've proved in the above pr that it isn't true and I'm no longer getting the error in my environment. There may be something else going on here but it's out of scope of this issue

**Comment by dmateusp** [comment]
I'm not totally clear on the conclusion, are we saying sqlfluff is actually compatible with dbt0.19 ?

**Comment by NiallRees** [comment]
> I'm not totally clear on the conclusion, are we saying sqlfluff is actually compatible with dbt0.19 ?

Yep - https://github.com/sqlfluff/sqlfluff/pull/789
