### ISSUE TITLE
Critical Linting Error - L003

### ISSUE THREAD

**Issue by dwallace0723** [sqlfluff/sqlfluff#833]
Came across this `CRITICAL` error when linting our dbt project. Details below:

```sh
$ sqlfluff lint models/content/products/products_daily_fanout.sql

CRITICAL   [L003] Applying rule L003 threw an Exception: Unexpected case, please report bug, including the query you are linting! 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/rules/base.py", line 282, in crawl
    res = self._eval(
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/rules/std/L003.py", line 408, in _eval
    raise RuntimeError(
RuntimeError: Unexpected case, please report bug, including the query you are linting!
```

#### Verbose Output:
[sqlfluff_out.txt](https://github.com/sqlfluff/sqlfluff/files/6064863/sqlfluff_out.txt)

#### Version
```sh
$ sqlfluff --version
sqlfluff, version 0.4.1
```

#### Configuration
```
[sqlfluff]
dialect = snowflake
templater = dbt
# dbt templating does not keep trailing new lines (L009)
exclude_rules = L007,L009,L031,L033,L034

[sqlfluff:rules]
max_line_length = 120
comma_style = trailing

[sqlfluff:rules:L010]
capitalisation_policy = upper
```

#### SQL
```sql
{{
  config(
    materialized='incremental',
    schema='intermediate',
    unique_key='snapshot_fanout_pk',
    cluster_by=['valid_date_pt'],
    automatic_clustering=true,
    snowflake_warehouse='DBT_WH_M'
    )
}}

with 
products as (select * from {{ ref('stg_products_snapshot__dbt') }}),
dates as (select date_day from {{ ref('dates') }})

select
  {#- Attributes #}
  products.product_id,
  products.name,
  products.brand_name,
  products.type as category,
  products.subcategory,
  products.description,
  products.dispensary_id,
  products.status,
  products.score,
  products.created_at,
  products.updated_at,
  products.brand_id,
  products.brand_description,
  products.duplicated_product_id,
  products.thc_content,
  products.cbd_content,
  products.updated_by,
  products.created_by,
  products.rec_only,
  products.weight,
  products.rec_prices,
  products.medical_prices,
  products.reviewed_at,
  products.reviewed_by,
  products.strain,
  products.strain_id,
  products.integration,
  products.overrides,

  {#- Metadata #}
  products.dbt_scd_id as snapshot_id,
  dates.date_day as valid_date_pt,
  products.dbt_valid_from_pt,
  products.dbt_valid_to_pt,
  products._fivetran_synced,
  products._fivetran_deleted,
  md5(products.product_id || '-' || dates.date_day) as snapshot_fanout_pk
from products
inner join dates
on products.dbt_valid_from_pt <= dates.date_day
and (products.dbt_valid_to_pt > dates.date_day
or products.dbt_valid_to_pt is null)
{% if is_incremental() -%}
where dates.date_day >= (select max(valid_date_pt) from {{ this }})
{% endif -%}
```

#### Compiled SQL
```sql
with 
 __dbt__CTE__stg_products_snapshot__dbt as (


select
    snap.dbt_scd_id,
    snap.dbt_valid_from,
    snap.dbt_valid_to,
    convert_timezone('America/Los_Angeles', snap.dbt_valid_from) as dbt_valid_from_pt,
    convert_timezone('America/Los_Angeles', snap.dbt_valid_to) as dbt_valid_to_pt,
    snap._fivetran_synced,
    snap._fivetran_deleted,
    snap._id as product_id,
    snap.name,
    snap.type,
    snap.subcategory,
    snap.dispensary_id,
    snap.status,
    snap.description,
    snap.score,
    coalesce(snap.created_at, try_to_timestamp_tz(snap.date_created)) as created_at,
    snap.brand_id,
    snap.brand_name,
    snap.brand_description,
    snap.duplicated_product_id,
    snap.thccontent as thc_content,
    snap.cbdcontent as cbd_content,
    snap.updated_by,
    snap.created_by,
    snap.rec_only,
    snap.weight,
    snap.options,
    snap.rec_prices,
    snap.medical_prices,
    snap.description_html,
    snap.updated_at,
    snap.reviewed_at,
    snap.reviewed_by,
    snap.matched_library_items_confidence as max_confidence_score,
    snap.matched_library_items,
    snap.matched_brand_against,
    snap.matched_strain_against,
    snap.matched_product_against,
    snap.sales_all_time,
    snap.strain,
    snap.strain_id,
    snap.old_strain_id,
    snap.synced_at,
    snap.integration,
    snap.last_sync_tracked_attrs,
    snap.posmeta_data as pos_metadata,
    snap.overrides
from analytics.public_snapshots.mongo_products_snapshot as snap
),products as (select * from __dbt__CTE__stg_products_snapshot__dbt),
dates as (select date_day from ANALYTICS_DWALLACE.PUBLIC.dates)

select
  products.product_id,
  products.name,
  products.brand_name,
  products.type as category,
  products.subcategory,
  products.description,
  products.dispensary_id,
  products.status,
  products.score,
  products.created_at,
  products.updated_at,
  products.brand_id,
  products.brand_description,
  products.duplicated_product_id,
  products.thc_content,
  products.cbd_content,
  products.updated_by,
  products.created_by,
  products.rec_only,
  products.weight,
  products.rec_prices,
  products.medical_prices,
  products.reviewed_at,
  products.reviewed_by,
  products.strain,
  products.strain_id,
  products.integration,
  products.overrides,
  products.dbt_scd_id as snapshot_id,
  dates.date_day as valid_date_pt,
  products.dbt_valid_from_pt,
  products.dbt_valid_to_pt,
  products._fivetran_synced,
  products._fivetran_deleted,
  md5(products.product_id || '-' || dates.date_day) as snapshot_fanout_pk
from products
inner join dates
on products.dbt_valid_from_pt <= dates.date_day
and (products.dbt_valid_to_pt > dates.date_day
or products.dbt_valid_to_pt is null)
```

**Comment by alanmcruickshank** [comment]
@dwallace0723 - In #888 I've just removed this error because I don't think it's relevant anymore. That should hopefully solve the `CRITICAL` error, however it does make me wonder that SQLFluff might be attempting a more unusual fix. Would you mind checking out that branch (or just installing from `master` after it's merged) to see whether a) you're still getting an error (I hope you're not) and b) what the proposed fix is if you run `sqlfluff fix`.

**Comment by alanmcruickshank** [comment]
@dwallace0723 - The changes I referred to above are now released as part of 0.5.0. Could you report in on how this is now behaving with the new release? I wonder whether it might be attempting something strange which I'd love to fix if it is.

**Comment by dwallace0723** [comment]
>The changes I referred to above are now released as part of 0.5.0. Could you report in on how this is now behaving with the new release? I wonder whether it might be attempting something strange which I'd love to fix if it is

Thanks for the update @alanmcruickshank! Will test this out today or tomorrow and report back 👍

**Comment by dwallace0723** [comment]
@alanmcruickshank I can confirm that the error is no longer raised on the model in question. Here are the proposed fixes now:

```
$ sqlfluff fix models/content/products/products_daily_fanout.sql 
==== finding fixable violations ====
== [models/content/products/products_daily_fanout.sql] FAIL
L:  13 | P:  67 | L018 | WITH clause closing bracket should be aligned with WITH
                       | keyword.
L:  14 | P:   1 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  14 | P:   7 | L010 | Inconsistent capitalisation of keywords.
L:  14 | P:  11 | L010 | Inconsistent capitalisation of keywords.
L:  14 | P:  18 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  14 | P:  27 | L010 | Inconsistent capitalisation of keywords.
L:  16 | P:   1 | L010 | Inconsistent capitalisation of keywords.
L:  17 | P:  20 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  17 | P:  20 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  18 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  18 | P:  23 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  18 | P:  23 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  19 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  19 | P:  17 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  19 | P:  17 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  20 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  20 | P:  23 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  20 | P:  23 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  21 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  21 | P:  14 | L010 | Inconsistent capitalisation of keywords.
L:  21 | P:  17 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  21 | P:  29 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  21 | P:  29 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  22 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  22 | P:  24 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  22 | P:  24 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  23 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  23 | P:  24 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  23 | P:  24 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  24 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  24 | P:  26 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  24 | P:  26 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  25 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  25 | P:  19 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  25 | P:  19 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  26 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  26 | P:  18 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  26 | P:  18 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  27 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  27 | P:  23 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  27 | P:  23 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  28 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  28 | P:  23 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  28 | P:  23 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  29 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  29 | P:  21 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  29 | P:  21 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  30 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  30 | P:  30 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  30 | P:  30 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  31 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  31 | P:  34 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  31 | P:  34 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  32 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  32 | P:  24 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  32 | P:  24 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  33 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  33 | P:  24 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  33 | P:  24 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  34 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  34 | P:  23 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  34 | P:  23 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  35 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  35 | P:  23 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  35 | P:  23 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  36 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  36 | P:  21 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  36 | P:  21 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  37 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  37 | P:  19 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  37 | P:  19 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  38 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  38 | P:  23 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  38 | P:  23 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  39 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  39 | P:  27 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  39 | P:  27 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  40 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  40 | P:  24 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  40 | P:  24 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  41 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  41 | P:  24 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  41 | P:  24 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  42 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  42 | P:  19 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  42 | P:  19 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  43 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  43 | P:  22 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  43 | P:  22 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  44 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  44 | P:  24 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  44 | P:  24 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  45 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  47 | P:  14 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  47 | P:  14 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  48 | P:   5 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  48 | P:  16 | L010 | Inconsistent capitalisation of keywords.
L:  48 | P:  19 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  48 | P:  34 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  48 | P:  34 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  49 | P:   2 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  49 | P:  11 | L010 | Inconsistent capitalisation of keywords.
L:  49 | P:  14 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  49 | P:  31 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  49 | P:  31 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  50 | P:   5 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  50 | P:  26 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  50 | P:  26 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  51 | P:   5 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  51 | P:  24 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  51 | P:  24 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  52 | P:   5 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  52 | P:  25 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  52 | P:  25 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  53 | P:   5 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  53 | P:  26 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  53 | P:  30 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  54 | P:   9 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  54 | P:  30 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  54 | P:  36 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  54 | P:  46 | L010 | Inconsistent capitalisation of keywords.
L:  54 | P:  49 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  54 | P:  68 | L010 | Inconsistent capitalisation of keywords.
L:  54 | P:  73 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  55 | P:   8 | L010 | Inconsistent capitalisation of keywords.
L:  55 | P:  14 | L010 | Inconsistent capitalisation of keywords.
L:  56 | P:   5 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  56 | P:  11 | L003 | Indent expected and not found compared to line #96
L:  56 | P:  11 | L010 | Inconsistent capitalisation of keywords.
L:  56 | P:  14 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  57 | P:   6 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  57 | P:  27 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  57 | P:  33 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  57 | P:  42 | L003 | Indent expected and not found compared to line #96
L:  57 | P:  42 | L010 | Inconsistent capitalisation of keywords.
L:  57 | P:  47 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  58 | P:   8 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  58 | P:  26 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  58 | P:  32 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  58 | P:  41 | L003 | Indent expected and not found compared to line #96
L:  58 | P:  41 | L010 | Inconsistent capitalisation of keywords.
L:  58 | P:  44 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  59 | P:   6 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  59 | P:  22 | L010 | Inconsistent capitalisation of keywords.
L:  59 | P:  25 | L010 | Inconsistent capitalisation of keywords.
L:  60 | P:  21 | L010 | Inconsistent capitalisation of keywords.
L:  56 | P:   4 | L022 | Blank line expected but not found after CTE closing
                       | bracket.
L:  60 | P:  27 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  61 | P:   6 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  61 | P:  19 | L010 | Inconsistent capitalisation of keywords.
L:  61 | P:  30 | L014 | Inconsistent capitalisation of unquoted identifiers.
L:  61 | P:  45 | L010 | Inconsistent capitalisation of keywords.
L:  58 | P:   1 | L022 | Blank line expected but not found after CTE closing
                       | bracket.
==== fixing violations ====
153 fixable linting violations found
Are you sure you wish to attempt to fix these? [Y/n] ...
```

**Comment by alanmcruickshank** [comment]
Excellent. If you just run `sqlfluff fix models/content/products/products_daily_fanout.sql --rules L003` to limit it to L003 and then apply the fixes, does the file look acceptable or is there any questionable re-indentation applied?

**Comment by dwallace0723** [comment]
@alanmcruickshank oof - here are the results of `sqlfluff fix models/content/products/products_daily_fanout.sql --rules L003`:

```sql
{{
  config(
    materialized='incremental',
    schema='intermediate',
    unique_key='snapshot_fanout_pk',
    cluster_by=['valid_date_pt'],
    automatic_clustering=true,
    snowflake_warehouse='DBT_WH_M'
    )
}}

with 
products as (select * from {{ ref('stg_products_snapshot__dbt') }}),
dates as (select date_day from {{ ref('dates') }})

select
  {#- Attributes     
  products.product_i    
  products.nam    
  products.brand_nam    
  products.type as categor    
  products.subcategor    
  products.descriptio    
  products.dispensary_i    
  products.statu    
  products.scor    
  products.created_a    
  products.updated_a    
  products.brand_i    
  products.brand_descriptio    
  products.duplicated_product_i    
  products.thc_conten    
  products.cbd_conten    
  products.updated_b    
  products.created_b    
  products.rec_onl    
  products.weigh    
  products.rec_price    
  products.medical_price    
  products.reviewed_a    
  products.reviewed_b    
  products.strai    
  products.strain_i    
  products.integratio    
  products.overrides,

  {#- Metad    a #}
  products.dbt_scd_id as snapsh    _id,
  dates.date_day as valid_da    _pt,
  products.dbt_valid_fr    _pt,
  products.dbt_valid_    _pt,
  products._fivetran_s    ced,
  products._fivetran_de    ted,
  md5(products.product_id || '-' || dates.date_day) as snapshot_fanfrom products
inner join dates
    on products.dbt_valid_from_pt <= dates.date_day
        and (products.dbt_valid_to_pt > dates.date_day
            or products.dbt_valid_to_pt is null)s null)
{% if is_incremental() -%}
where dates.date_day >= (select max(valid_date_pt) from {{ this }})
{% endif -%}
```

Not sure if you can tell from that snippet, but this results in the entire model being placed within jinja comments:

<img width="618" alt="Screen Shot 2021-04-12 at 4 46 38 PM" src="https://user-images.githubusercontent.com/20053731/114476218-b1879680-9bae-11eb-83c1-490edf2ebfba.png">

**Comment by barrywhart** [comment]
@dwallace0723: Can this issue be closed?

I saw that you said:
>I can confirm that the error is no longer raised on the model in question.

But later said:
>oof - here are the results of sqlfluff fix models/content/products/products_daily_fanout.sql --rules L003:

What does "oof" mean?
